### ISSUE TITLE
Environment Identification

### ISSUE THREAD

**Issue by fabiofilz** [tchiotludo/akhq#1009]
Hi,

Would it be possible to change the appearance of AKHQ by changing the configuration in the value.yaml?

We are using AKHQ in different environments and having an option to change the colour (or having a banner with environment name) would be very useful to identify easily in which environment you logged in.

Thank you.
Fabio

**Comment by tchiotludo** [comment]
enjoy on `dev` branch: https://akhq.io/docs/configuration/akhq.html#inject-some-css-or-javascript
