### ISSUE TITLE
Can't authenticate with large topic list

### ISSUE THREAD

**Issue by gigiquery** [tchiotludo/akhq#1027]
Hi,
We are using LDAP authentication and default JWT configuration.
JWT token is sent using cookie with the topics in it.
In our case we have a huuuge list of topics in the "topics-filter-regexp" parameter of the application.yml (about 1280).
When this list is sent in the cookie with the authentication information, it's blocked by Chrome because the size exceeds 4096 bytes.

We found a workaround by forcing an empty list in LocalSecurityClaimProvider.java:107 but not sure it won't have any side effects.

We also tried to change the authentication (pass using header or in the HTTP response instead of the cookie) without success.

Do you have any idea?

**Comment by tchiotludo** [comment]
This is a limitation of browser that we can't change. 
Not really sure, but you may need to configure the topic directly on AKHQ configuration and directly use the group on the auth to avoid to have such large jwt token ?

**Comment by gigiquery** [comment]
I'm not sure what you mean by "configure the topic directly on AKHQ configuration"
Our topic list is in the "akhq.security.groups.key.attributes.topics-filter-regexp"

We are aware that we can't change the browser cookie size but we were tying to explore other solutions like passing the topic list in another way.
Do you think that changing the authentication method in micronaut (session, bearer...) would be a solution as it's not sent using the cookies? We tried that using your documentation but without success. Can you help us on that?

Another solution may be to retrieve the topic lists separately from the login process itself using, for example, a dedicated rest endpoint called by the front-end just after a successful login. What do you think of this solution?

**Comment by schaubce** [comment]
Hi, we're having a similar issue to this. I wanted to confirm with you that the only workaround is managing access through the application.yml? If so, is there a limit to how may groups/topics can be returned there?

**Comment by tchiotludo** [comment]
done in #1472
