### ISSUE TITLE
pressing 'Enter' when creating a topic disconnects from the AKHQ (connection reset by peer)

### ISSUE THREAD

**Issue by edenkoveshi** [tchiotludo/akhq#1030]
Hi,
I tried to create a topic and when I entered a name for the topic I pressed 'Enter' and I got disconnected from the GUI (had to put my AKHQ credentials again).
The error I saw in the logs was: 'Connection reset by peer'.
My AKHQ is deployed on openshift

**Comment by tchiotludo** [comment]
I think it will be really hard to debug. Connection reset by peer in an openshit env can be a lot of stuff (LB, container, ...). 

Are you able to reproduce the issue easily or not ?

**Comment by rbr101** [comment]
Hi,

I'm having maybe the same error, this has to do with openshift routes and user authorisation.
The AKHQ web interfaced is exposed using an openshift route. When adding or viewing topics and other stuff i get:

 ```
2022-03-30 08:29:41,309 [31mWARN [0;39m [35mhread-1214[0;39m [36morg.akhq.log.access       [0;39m [Date: 2022-03-30T08:29:41.308615+02:00] [Duration: 1 ms] [Url: GET /akhq/api/kafka-prod/topic] [Status: 500] [Ip: /10.128.8.2] [User: admin]
2022-03-30 08:29:41,310 [1;31mERROR[0;39m [35mhread-1212[0;39m [36mo.a.c.ErrorController     [0;39m Connection reset by peer
java.io.IOException: Connection reset by peer
```

Now the docs mention this: https://akhq.io/docs/configuration/authentifications/header.html
But how to configure this for use in openshift ?

**Comment by rbr101** [comment]
Ok, i found this was related to strimzi KAFKA setting:
The authentication.type: tls was missing
```
    listeners:
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
```
