### ISSUE TITLE
configure session expiration

### ISSUE THREAD

**Issue by BarFoos81** [tchiotludo/akhq#1036]
Hi,

I have the same issue like https://github.com/tchiotludo/akhq/issues/318

Unfortunately the suggested solution does not work for me. 

```
micronaut:
  session:
    max-inactive-interval:2h
```

Any idea, how I could extend the session expiration?

Thank you very much

**Comment by tchiotludo** [comment]
hello :) 
I think this is [this configuration](https://micronaut-projects.github.io/micronaut-security/latest/guide/#jwtGenerator) for will be working :

**Comment by KirschenStas** [comment]
Hi!

I've just set:
`micronaut.security.token.jwt.generator.access-token.expiration`
and it work for me!
@tchiotludo, thanks!

**Comment by tchiotludo** [comment]
Nice 👍

**Comment by BarFoos81** [comment]
I can confirm - it works. Nice. Thanks.
