### ISSUE TITLE
UI becomes super laggy after enabling "external roles and attributes mapping"

### ISSUE THREAD

**Issue by baganokodo** [tchiotludo/akhq#1039]
Hi,

With "external roles and attributes mapping" enabled, akhq makes ~50 repeated RPC calls to the remote REST endpoint after a user logs in. Even though each RPC call takes sub-second to return, these repeated RPC calls makes akhq very slow. Especially the topic/data screen often times out when listing messages of a topic, oddly, this action only invokes the remote RPC twice, it still shows significant lag and leads the UI timeout. Reducing the list size to 20 didn't help. It makes the UI barely usable. Any advice is highly appreciated.

thank you

**Comment by baganokodo** [comment]
Hi [tchiotludo](https://github.com/tchiotludo),

thanks again for your quick response. I can't post a screenshoot due to my company's policy. When I search "akhq.security.rest", I landed on "akhq.security.rest.RestApiClaimProvider" interface, could not find its implementations. I would like add a caffeine cache layer to reduce the number of REST calls. Could you shed some light on it?

Thank you

**Comment by tchiotludo** [comment]
I can't help you since I don't understand the issue without any screenshot or log (even anonymised, blurred)

**Comment by tchiotludo** [comment]
Don't help me, I need 
- devtools screenshot (chrome + f12 + network tab + refresh page to see the request your are talking) 
- akhq server log
- akhq version used
- deployment method (docker / jar / k8s / ...) 

Without that I couldn't help

**Comment by baganokodo** [comment]
Thank @tchiotludo, after I enabled cache on RestApiClaimProvider, the REST server side only saw one request per user login, and that fixed the slowness problem for me.

Cheers

**Comment by tchiotludo** [comment]
Still not really see the issue but if it works for you fine 😉
