### ISSUE TITLE
Ldap user access

### ISSUE THREAD

**Issue by jessetandor** [tchiotludo/akhq#1040]
Can we use a wildcard to represent any user like so ---- *

This line here - https://github.com/tchiotludo/akhq/blob/59e78f5a2b0215095dd883fb7e6f67eb7c094459/application.example.yml#L248.

Makes sense to allow access if the user is already in the right ldap group instead of specifying each user that should be given access. Or is it that the whole ldap user section can be skipped?

**Comment by jessetandor** [comment]
Indeed, access does work without specifying the ldap user's. But can we disable anonymous access? 

Would like to force login, always.

**Comment by tchiotludo** [comment]
yes, just make [default-groups to no-roles](https://akhq.io/docs/configuration/authentifications/groups.html)

**Comment by jessetandor** [comment]
How can i get advanced logs for LDAP (group detection and mapping). Im currently using `TRACE' but it's not very informative.

**Comment by tchiotludo** [comment]
Following this [doc](https://akhq.io/docs/debug.html#monitoring-endpoint)
