### ISSUE TITLE
[UI] Error message for "Produce to topic" could be more helpful

### ISSUE THREAD

**Issue by bartektartanus** [tchiotludo/akhq#1052]
Producing to topic with schema gives errors that don't really tell what's wrong.

1. message is empty (like empty string, not empty JSON)
error: `Internal Server Error: Cannot serialize value`
Maybe simple "message is empty" should be returned here?
2. some fields are missing in schema
error: `Internal Server Error: null`
Should at least tell that fields are missing or schema is wrong. Ideally - which fields are missing.
3. field has wrong type
error: `Internal Server Error: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')`
Should also include name of the field

**Comment by rdanielwetan** [comment]
I would like to take this issue please

**Comment by tchiotludo** [comment]
@rdanielwetan you are assigned, thanks!

**Comment by GnanaJeyam** [comment]
@rdanielwetan Are you still working on this issue..?

@tchiotludo  I have raised a PR for this issue. 
Please take a look https://github.com/tchiotludo/akhq/pull/1233

**Comment by GnanaJeyam** [comment]
This is my first PR to OSS. Feel free provide any feedbacks to me. :)

**Comment by tchiotludo** [comment]
done in https://github.com/tchiotludo/akhq/pull/1233
