### ISSUE TITLE
Sending tombstones with 'Produce to topic'

### ISSUE THREAD

**Issue by neoscaler** [tchiotludo/akhq#1072]
We can't produce valid tombstones using the 'Produce to topic' functionality. I tried already leaving the value empty or using 'null'. As far as I interpret the code at https://github.com/tchiotludo/akhq/blob/40f90041ca71c186a4dc37669a25ec05da1a4b9f/client/src/containers/Topic/TopicProduce/TopicProduce.jsx#L173, the value is simply used as string, so you can't create a valid tombstone with a null value currently.

Tested with AKHQ v0.20.0

**Comment by tchiotludo** [comment]
Seems that we simply need to add a GUI options to produce tombstone. 
PR are welcome

**Comment by neoscaler** [comment]
> Seems that we simply need to add a GUI options to produce tombstone. PR are welcome

Working on a PR.
