### ISSUE TITLE
Multiple Search values of a topic data isn't working

### ISSUE THREAD

**Issue by vis08** [tchiotludo/akhq#1073]
Running on akhq 0.20.0

Topic Data Lookup isn't working. Multi search criteria on a topic data is not working as expected. Search is performing an OR instead of AND. 

Example: Trying to lookup for the messages having the values  "CusId": "12345678"  "action": "DISABLED" isn't returning intended data, instead returning all the messages.  

This capabilities used to work and exist in older version of akhq. Is it bug on akhq v0.20.0 ?

**Comment by vis08** [comment]
![Uploading Screenshot 2022-04-19 at 9.33.17 PM.png…]()

**Comment by tchiotludo** [comment]
Must be ok on last release : https://github.com/tchiotludo/akhq/releases/tag/0.21.0

Can you try and reopen if not please ?
