### ISSUE TITLE
Push images to GitHub Container Registry

### ISSUE THREAD

**Issue by MatteoJoliveau** [tchiotludo/akhq#1080]
[As you may know](https://docs.docker.com/docker-hub/download-rate-limit/), Docker Hub imposes severe rate limits on unauthenticated and free accounts. These limits can cause severe downtimes in environments without a paying Docker Hub subscription.

Adding a second container registry like [ghcr.io](https://ghcr.io), which is free and already included with this GitHub repo, would allow users to choose the registry to pull from. Adding a second registry to the GitHub Actions workflow would be very easy and wouldn't even require maintaining a new set of credentials.

I can submit a PR to update the workflow if you wish.

**Comment by tchiotludo** [comment]
hey @MatteoJoliveau, 
No problems for me, this make sense, PR are welcome :+1:

**Comment by MatteoJoliveau** [comment]
It worked 😄 
https://github.com/tchiotludo/akhq/pkgs/container/akhq
