### ISSUE TITLE
IAMClientCallbackHandler could not be found

### ISSUE THREAD

**Issue by 1063238280** [tchiotludo/akhq#1089]
my configure:
...
        properties:
          bootstrap.servers: ***:9098
          security.protocol: SASL_SSL
          sasl.mechanism: AWS_MSK_IAM
          sasl.jaas.config: software.amazon.msk.auth.iam.IAMLoginModule required awsDebugCreds=true;
          sasl.client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler
          ssl.truststore.location: ${JAVA_HOME}/lib/security/cacerts
          ssl.truststore.password: changeit
...
when I access aws msk with IAM , akhq UI has error info :
Internal Server Error: Invalid value software.amazon.msk.auth.iam.IAMClientCallbackHandler for configuration sasl.client.callback.handler.class: Class software.amazon.msk.auth.iam.IAMClientCallbackHandler could not be found.

kafka version :2.6.2
akhq image version: 0.20.0
helm repo :  https://akhq.io/

**Comment by tchiotludo** [comment]
It must be ok on last release : https://github.com/tchiotludo/akhq/releases/tag/0.21.0

Reopen if not please
