### ISSUE TITLE
API: return 404 when cluster not configured

### ISSUE THREAD

**Issue by lostiniceland** [tchiotludo/akhq#1094]
Currently, when trying to access the API with a wrong (not configred cluster-name), an Exception will be thrown and 500 is returned.

http://localhost:8080/akhq/api/BROKEN/topic/foo/data
`"Internal Server Error: Missing required configuration \"bootstrap.servers\" which has no default value."`

The API handling will silently accept the given cluster-name and forward the request to the Kafka client which in this gets does not receive the proper configuration for `bootstrap.servers` and correctly fails.
Instead, the API should check if the given cluster exists (is configured) and only continue when successfull. Otherwise, short-circuit with a 404.

**Comment by rdrck47** [comment]
Hi, I want to contribute my good first issue. Can I start working on this?

**Comment by tchiotludo** [comment]
For sure 😊
