### ISSUE TITLE
subject does not have subject-level compatibility configured

### ISSUE THREAD

**Issue by juliangovender** [tchiotludo/akhq#1098]
Hi,

I am seeing errors in my schema-registry kubernetes pod when I use AKHQ to access my schema registry: 
`io.confluent.rest.exceptions.RestNotFoundException: Subject [] does not have subject-level compatibility configured`

The schemas still load correctly in the UI and there are no errors on the UI / akhq pod, only on the schema registry pod when accessed by akhq. When accessed by my backend, I see 200's on the schema registry pod logs.
 
I understand that defaultToGlobal=true querystring has been added in v0.18. I am currently using akhq:0.20.0

**Comment by tchiotludo** [comment]
Can you try with last version ? 0.21.0 please ?

**Comment by juliangovender** [comment]
> Can you try with last version ? 0.21.0 please ?

Thanks for getting back to me. I'm still experiencing the same issue on 0.21.0

**Comment by tchiotludo** [comment]
Looking at quickly, the pr [here](https://github.com/tchiotludo/akhq/pull/765) only remove the error from akhq but still send the query without `defaultToGlobal` 
I've made a try, you can try with dev version

**Comment by juliangovender** [comment]
Thanks a lot @tchiotludo, that fixed it! 🎉

**Comment by juliangovender** [comment]
Hi @tchiotludo, do you perhaps have an idea of when a new docker image will be ready with this fix?

**Comment by tchiotludo** [comment]
@juliangovender you can use the [dev](https://akhq.io/docs/dev.html#early-dev-image) image that is already available
