### ISSUE TITLE
manage more than one kafka broker

### ISSUE THREAD

**Issue by cforce** [tchiotludo/akhq#11]
Allow to manage more than one kafka broker (support for multiple environment's),

**Comment by tchiotludo** [comment]
It's already possible.

If you look at the README:
,```

  kafka {
    connections {
      plaintext {
          bootstrap.servers: "kafka:9092"
      }
      ssl {
        bootstrap.servers: "kafka:9093"
        security.protocol: SSL
        ssl.truststore.location: /app/truststore.jks
        ssl.truststore.password: password
        ssl.keystore.location: /app/keystore.jks
        ssl.keystore.password: password
        ssl.key.password: password
      }
    }
  }
}```

This configuration is for 2 cluster one with ssl and the other in plaintext.

Maybe the README is not clear enough ?

**Comment by senthil13** [comment]
If we want to add two plain text cluster then ?  It tried to add two but it taking the last line alone.

**Comment by tchiotludo** [comment]
This should work : 
```
  kafka {
    connections {
      my-cluster-1 {
          bootstrap.servers: "kafka-1:9092"
      }
      my-cluster-2 {
          bootstrap.servers: "kafka-2:9092"
      }
    }
  }
}
```

In fact the `my-cluster-1` and `my-cluster-2` is just a name for the current cluster (must be url friendly).
