### ISSUE TITLE
Consumer group with slash crashed the ui

### ISSUE THREAD

**Issue by baganokodo** [tchiotludo/akhq#1101]
Hi,

I suspect this issue is caused by special chars like "/" and ":" in our consumer group names. Could you confirm that special chars are not accepted in consumer group names?

sample consumer groups, "data/data-serving:forwarder", "local_test/hostname.local"

Thanks

**Comment by tchiotludo** [comment]
can you send a screenshot please?

**Comment by baganokodo** [comment]
Thanks @tchiotludo for the quick response. I feel it quickly popped a red error banner, and the entire page was gone instantaneously. I checked the AKHQ log, nothing special, no errors. The web page is totally blank, it is black mostly like because the chrome theme I selected. Page source only shows some Javascript references. 

Thanks

**Comment by tchiotludo** [comment]
It's seems that there is an hard JavaScript error, can you provide the error from JavaScript console from chrome ?

**Comment by baganokodo** [comment]
![Screen Shot 2022-05-26 at 1 49 11 PM](https://user-images.githubusercontent.com/78040512/170577718-2d43780a-e221-4a94-9513-420d23027180.png)
thanks a lot

**Comment by baganokodo** [comment]
found a good sample on URL encoder, https://www.baeldung.com/java-url-encoding-decoding, I will try to make a PR
thanks very much

**Comment by rdrck47** [comment]
Hello! Is anyone working on this? I would like to take this issue!

**Comment by tchiotludo** [comment]
No one is one it, it's assign to you 👍
