### ISSUE TITLE
Show Pattern Type Filter in ACLs Panel Information for: Topics, Groups, Clusters and Transactional IDs

### ISSUE THREAD

**Issue by javier-torres** [tchiotludo/akhq#1115]
Hi,

We have working with AKHQ several months and we are very happy with the application, it´s fantastic!! 

As we are using it every, we have been findind several little things to improve. Recently we have open and issue to show more information in ACLs panel how are: Cluster and TransactionalID. Now we believe that it would be quite interesting to show information for Pattern Type Filter in each resources as: Topics, Groups, Clusters and Transactional IDs.

Attached an image of what we have in mind that would be interesting to consult:

![image](https://user-images.githubusercontent.com/59615952/172865745-270fd0de-aba9-4921-afc5-2856161a76cf.png)

Thank you so much.
Javier Torres

**Comment by tchiotludo** [comment]
it's will be nice, PR are welcome :)

**Comment by jheinitz** [comment]
Hello!

Nice idea, but I'm just wondering why my ACLS screen for a given user only contains the tabs "Topics" and "Groups", but no "Cluster" and "Transactional Ids". Did you fake the screenshot or do I need to grant permissions for the user/group to see these acls? By the way, I'm using 0.21.0

Kind regards

Jens

**Comment by tchiotludo** [comment]
it's not release for now, you need to use the `dev` version for now

**Comment by 10xtechie** [comment]
@tchiotludo , @javier-torres ,
Is my understanding correct that a filter for _**Patter Type**_ needs to be add to each table under: **Topics**, **Groups**, **Clusters**, **Transactional Id** ? 
If so, there seems to be quite a bit of work involved for this issue. However, I would be happy to take this on :)

**Comment by tchiotludo** [comment]
I understand the same @10xtechie, I assign you the issue, Thanks :+1:

**Comment by 10xtechie** [comment]
@tchiotludo, @javier-torres,
Thanks for your replies!! Could you please provide me with sample/dummy data and some instructions on how to populate Kafka with those data? It would be helpful to test the feature while developing it :)
