### ISSUE TITLE
Hidden Credentials for Kafka Connectors

### ISSUE THREAD

**Issue by javier-torres** [tchiotludo/akhq#1116]
Hi,

We have working with AKHQ several months and we are very happy with the application, it´s fantastic!!

As we are using it every, we have been findind several little things to improve. Now, we are working with Kafka-Connect and creating multiples connector for differents purposes. When you access to connector configuration, you can see the passwords are displayed in plain text. We have vision reader over all the AKHQ to developers and it would be interesting that these credentials are not seen and are encrypted, for example: *************

Attached an image of what we have in mind that would be interesting to consult:

![image](https://user-images.githubusercontent.com/59615952/172867194-5228c287-3edc-471c-b289-95439990d6bb.png)

Thank you so much.
Javier Torres

**Comment by eddyv** [comment]
Hey! I'd recommend taking a look at adding a secrets' provider to your kafka connect instance. It'd be a more complete solution to prevent kafka connect from exposing those details via the rest api as opposed to only masking it in AKHQ.

Lenses offers a few open source ones that you can find [here](https://docs.lenses.io/5.0/integrations/connectors/secret-providers/)

**Comment by javier-torres** [comment]
Hey @eddyv, it is a nice tool which we will try, but nevertheless, it would not hurt to encrypt the credentials data in plain text as other tools like Kafka UI do.

![imagen](https://user-images.githubusercontent.com/59615952/174237589-428b7e9a-f5f3-4d5f-96a4-f0473d7f1cbe.png)

Thank you

**Comment by tchiotludo** [comment]
duplicate #505
