### ISSUE TITLE
KSQL supports

### ISSUE THREAD

**Issue by xs005** [tchiotludo/akhq#115]
I like KafkaHQ! If it supports KSQL that would be wonderful to integrate every part of Kafka stack in one management tool.

I don't know if this is in your roadmap. If not, I'd like to contribute for this project.

Some key functions are 

1. Execute KSQL statement sequentially from one file or one input string.
2. Get the status of stream/table from "DESCRIBE EXTENDED STREAM/TABLE".
3. List/terminate queries.
4. Batch delete streams/tables with automatically terminating related queries.
5. Show the content in the stream/table.
6. Visualize lags and speed of stream/table.
7. Add your own UDF/UADF to KSQL server in runtime??

**Comment by xs005** [comment]
Hi @tchiotludo ,

Congratulation to your new job! I am not a professional developer. It will take me a while to figure out the logic of KafkaHQ, and then do some coding.

Happy Friday! 👍 😄

**Comment by taufiqibrahim** [comment]
Hi @tchiotludo I was just thinking about having a KSQL clusters listing and some visualization based on queries dependencies. If I am going to contribute, how should I start? I am noob in Java, but has done some simple things in Flink and KSQL UDF.

**Comment by tchiotludo** [comment]
Hi @taufiqibrahim, 
I started to make a branch few month ago here : https://github.com/tchiotludo/akhq/tree/ksql.
The most important part is to start with a repository that allow to fetch data from a ksql server like here : https://github.com/tchiotludo/akhq/commit/4a94cf55a9a21e29820cbb0ea267d0a28cff6f5a#diff-9a8110f723614a1b85af376379d8d64d


There is a lot to do to be honest, the best will be to have some common query, map to internal model and expose some api via a Controller.

If you star from my branch, you could expose all the differents commun query from [here](https://docs.confluent.io/current/ksql/docs/developer-guide/syntax-reference.html#ksql-statements), mostly all `SHOW` & `DESCRIBE` on Repository mapped to internal Model and it will be a really good start to allow to go further.

**Comment by BruninkJ** [comment]
Don’t know if anybody is actively working on this at the moment. I too have the same request. Will see if i can help to accomplish this. Not that knowledgeable in react coding but Java is no problem.

**Comment by tchiotludo** [comment]
As I know, nobody works on this part.
If you are fluent with java, maybe you can start with repository and controller.
The react part is mostly simple following example in the codebase but if are not able (or allergic to front 😃) to do the ui, I think someone can do it.
