### ISSUE TITLE
Finer grain filtering on kafka connect attributes

### ISSUE THREAD

**Issue by apellegr06** [tchiotludo/akhq#1174]
Hi,

I'm using AKHQ 0.21.0 and recently adding Kafka Connect configuration that is a useful functionnality !

I use "connects-filter-regexp" to limit the view on some tasks for some users, but currently the behaviors of this filtering is not optimal :
If at least one regexp is set, the user have the visibility on all Kafka connect clusters configured for the Kafka cluster and can create tasks on all of them.
Is it possible to add a functionnality to filter also on Kafka connect clusters, for example with a "connect-clusters-filter-regexp" ?
And also is it possible to disable creation of tasks when it's not compliant to the "connects-filter-regexp" ?

Thanks
Alain

**Comment by apellegr06** [comment]
Not sure, this need is just to add a filter on the kafka connect cluster level (in addition with the existing one on tasks level) :
connect-clusters-filter-regexp

And that will filter the visibility of the Kafka connect instances in the list.

We really need this kind of filter because we have several kafka connect by kafka cluster, and not all used can access to all kafka connect instances.

**Comment by AlexisSouquiere** [comment]
@tchiotludo this one should be closed with the new permissions management

**Comment by tchiotludo** [comment]
done in #1472
