### ISSUE TITLE
New Feature: Download all messages in a topic to a json or csv file

### ISSUE THREAD

**Issue by jheinitz** [tchiotludo/akhq#1183]
Hello Ludovic!

Thanks again for this wonderful tool. We are currently wondering if there is a possibility to download all topic data to a single file. As far as I know it is only possible to download a single message using the download button when exploring the topic data. It would be very nice to have a feature like this. Ideally both formats are available or the format can be configured in the settings.

What do you think?

Thanks and best regards

Jens

**Comment by tchiotludo** [comment]
Hello @jheinitz, 

Excellent idea, PR is welcome on that!

**Comment by graciasrochelle** [comment]
Hi @tchiotludo, Is this ticket picked up? If not, I have a PR for it https://github.com/tchiotludo/akhq/pull/1384. Thanks in advance.

**Comment by graciasrochelle** [comment]
Can I please be assigned to this ticket as I got a solution in PR already? Thanks in advance
