### ISSUE TITLE
OIDC Azure provider - Username null

### ISSUE THREAD

**Issue by nparfait** [tchiotludo/akhq#1186]
I am trying to do SSO with azure via OIDC. I have managed to get groups working however the username displays as null.

I've tried setting
username-field: preferred_username
to multiple options, email, upn, etc. but it doesn't seem to make a difference.

Is there anyway to get the username to display with Azure?

**Comment by tchiotludo** [comment]
I was looking for the properties ;) 
Maybe you can add a PR with complete examples in the docs [here](https://github.com/tchiotludo/akhq/blob/dev/docs/docs/configuration/authentifications/oidc.md)?
