### ISSUE TITLE
Features: Scale-out instance more than one replicas

### ISSUE THREAD

**Issue by scila1996** [tchiotludo/akhq#1211]
Hi @tchiotludo 

Many thanks to AKHQ, it is the great application which support multiple cluster and authenticate over OIDC (OAuth2). I deploy on K8S with your official helm  (+10 star). But I want to scale up more than one instance (Pod) for HA, does micronauth support Redis Backend for user logged-in session data ? Thanks for reply !

**Comment by tchiotludo** [comment]
Hey @scila1996, you can scale without any issue. 
The storage for the auth is cookie based, there is no memory implication for the auth part and user management.
