### ISSUE TITLE
Bug: Can not search value in topic with sort (newest)

### ISSUE THREAD

**Issue by scila1996** [tchiotludo/akhq#1213]
Hi @tchiotludo 

I want to search data in topic. When I chose Sort (Newest), and select Search (fill any value in text box of key or value) and click Search icon, the Sort always back to (Oldest).

![Sep-20-2022 14-47-21](https://user-images.githubusercontent.com/17109300/191198914-60715e42-c3e5-4e0f-b104-7e0fc4128cd5.gif)

**Comment by HailToDodongo** [comment]
This feature was removed in  #473, i currently have an open PR for this + a general speedup for the search in #1209

**Comment by tchiotludo** [comment]
close in #1209
