### ISSUE TITLE
fetching messages from topic on m1 mac

### ISSUE THREAD

**Issue by Allan-Bray** [tchiotludo/akhq#1216]
I downloaded the akhq-0.22-all.jar

I used the following to launch it.

~/Library/Java/JavaVirtualMachines/openjdk-17.0.2/Contents/Home/bin/java -Dmicronaut.config.files=application.yml -jar akhq-0.22.0-all.jar  -Djava.io.tmpdir=.

I'm getting the following error

2022-09-22 08:07:01,602 ERROR r-thread-3 o.a.c.ErrorController      [FAILED_TO_LOAD_NATIVE_LIBRARY] no native library is found for os.name=Mac and os.arch=aarch64
org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] no native library is found for os.name=Mac and os.arch=aarch64

**Comment by tchiotludo** [comment]
Can you try with latest dev version please ? 
I've updated a lot of deps and it's seems it corrected here : https://github.com/xerial/snappy-java/releases/tag/1.1.8.2
reopen if not fixed
