### ISSUE TITLE
Feature request: JSON Pretty Printing messages 

### ISSUE THREAD

**Issue by edperry** [tchiotludo/akhq#1224]
This is a feature request to make usability better 

![Screenshot 2022-10-04 093403](https://user-images.githubusercontent.com/6684633/193834281-e455984c-b8d4-48de-bf91-fc573949930b.png)

When viewing large JSON messages, it would be nice if the display word wrapped, or even "Pretty print" formatting,

**Comment by tchiotludo** [comment]
I think it's done here : https://github.com/tchiotludo/akhq/pull/1246 and merge on latest dev. 
Reopen if not

**Comment by htbmw** [comment]
It is not working in the Live Tail view.
I created a new feature request specific for Live Tail view:

https://github.com/tchiotludo/akhq/issues/1444
