### ISSUE TITLE
All release files in the 0.22.0 release contains 0.21.0 directory and jar files

### ISSUE THREAD

**Issue by amoravek** [tchiotludo/akhq#1244]
All archives in the 0.22.0 release contains 0.21.0 directory. Also akhq jar file name contains the older version. File sizes are however different than the 0.21.0 so it seems to be some naming issue...

**Comment by tchiotludo** [comment]
Hey @amoravek, it's an issue during the release process, I forgot to change the version on gradle before releasing it, it will be fixed on next release
