### ISSUE TITLE
Tracking OpenSSL 3.0.2 Issue in AKHQ

### ISSUE THREAD

**Issue by eimarfandino** [tchiotludo/akhq#1245]
A new OpenSSL vulnerability affecting versions prior to 3.0.7 is present in the latest [AKHQ container image](https://github.com/tchiotludo/akhq/releases/tag/0.22.0).

Read more info about upcoming OpenSSL here: https://mta.openssl.org/pipermail/openssl-announce/2022-October/000238.html

Motivation
This issue is here to track the progress of the AKHQ community evaluating the issue when it released, and resolving, if appropriate.

**Comment by eimarfandino** [comment]
I have downgraded to version 0.21.0 where openssl 1.1.1 is used

**Comment by tchiotludo** [comment]
It's fixed on the dev version: 
```
openssl:
  Installed: 3.0.2-0ubuntu1.7
  Candidate: 3.0.2-0ubuntu1.7
  Version table:
 *** 3.0.2-0ubuntu1.7 500
        500 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages
        100 /var/lib/dpkg/status
     3.0.2-0ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages
```
see this : https://askubuntu.com/a/1438590
