### ISSUE TITLE
Support for `acls-filter-regexp`

### ISSUE THREAD

**Issue by LittleWat** [tchiotludo/akhq#1260]
Currently, `topics-filter-regex`, `connects-filter-regexp`, `consumer-groups-filter-regexp` are supported.
https://akhq.io/docs/configuration/authentifications/groups.html

We would like to hide some information in ACLs and it would be ideal if `acls-filter-regexp` is also supported.

**Comment by meeraj257** [comment]
@tchiotludo - can you pls assign this to me? I will work on this.

**Comment by tchiotludo** [comment]
Done 👍 thanks @meeraj257

**Comment by meeraj257** [comment]
@tchiotludo - PR https://github.com/tchiotludo/akhq/pull/1281 created for his issue. Pls review

**Comment by tchiotludo** [comment]
merged in https://github.com/tchiotludo/akhq/pull/1281
