### ISSUE TITLE
Optional fields are marked as missing when Producing messages

### ISSUE THREAD

**Issue by xontab** [tchiotludo/akhq#1265]
When producing new messages in AKHQ v0.23.0, fields that are not specified in the payload are marked as missing even if they are nullable or have default values.  

This feature looks related to a recent PR https://github.com/tchiotludo/akhq/pull/1233 which was released in v0.23.0.

I think that the `schemaFields` need to be filtered to exclude any fields with `default` and when the type can be `null`.  This used to work this way on previous versions of AKHQ.

**Comment by tchiotludo** [comment]
@GnanaJeyam maybe you can take this one ?

**Comment by GnanaJeyam** [comment]
@tchiotludo Sure I can pickup this issue.

**Comment by tchiotludo** [comment]
thanks @GnanaJeyam

**Comment by GnanaJeyam** [comment]
@tchiotludo I have a question about the schema.
Let's say the incoming schema has nested structure, do we need to recursively retrieve all the fields and do the comparison.. ? Can you share your thoughts.. ?

**Comment by tchiotludo** [comment]
In the better world, we need it! 
I didn't think with the PR you done that can be a stopper for some people, so maybe the best is to validate the whole thing globally. Maybe the best option will be to try to convert and throw the native exception ?

**Comment by GnanaJeyam** [comment]
@tchiotludo 
Which means validating all the fields recursively and throw exception.. ?

**Comment by tchiotludo** [comment]
yes ...

**Comment by GnanaJeyam** [comment]
@tchiotludo 
Cool, I will proceed on this.

Between, The PR which I raised before to akhq is my first Open Source Contribution :)

**Comment by tchiotludo** [comment]
We all have a first time 😇
