### ISSUE TITLE
Request: Only show message header information and not data.

### ISSUE THREAD

**Issue by johhue** [tchiotludo/akhq#1292]
I am using mirror maker 2 and need to ensure all messages on one cluster appear on another cluster.

To ensure messages are being replicated properly, we are checking the headers of all messages on both sides and comparing them.

We would like the ability to not pull in the topic data as some messages are larger as this slows down the request and parsing.

Can you please add to the query string the ability to not pull in the data for any message?

**Comment by tchiotludo** [comment]
It's not possible on the server side, the Kafka API will always return the whole data as I know

**Comment by johhue** [comment]
Thank you for responding so quickly. I am trying to find a way to check this for QA validation without needing to scan all the data.

**Comment by tchiotludo** [comment]
don't think it's possible, feel free to reopen if I'm wrong
