### ISSUE TITLE
java.io.IOException: Too many open files

### ISSUE THREAD

**Issue by johhue** [tchiotludo/akhq#1306]
Looking for some feedback on why I am getting this error and how to resolve? Is it an open issue?
I see many open files so maybe not using the correct java -- 

/usr/lib/jvm/java-11/bin/java -verbose -XX:SurvivorRatio=128 -XX:MaxTenuringThreshold=0 -XX:+UseTLAB -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:MaxNewSize=768m -XX:NewSize=768m -Xms10G -Xmx10G -server -Dmicronaut.config.files=application.yml -jar akhq.jar

Using RHEL7, open files limit is 10240

2022-12-14 08:45:13,366 WARN  pGroup-1-2 n.c.DefaultChannelPipeline An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Too many open files

**Comment by johhue** [comment]
I am using AKHQ 0.23 (latest one)

**Comment by tchiotludo** [comment]
- what is the installation type ? (jar, docker, kube)
- it's the only log on startup ? 
- if not, when the error happen (duration) ?

**Comment by johhue** [comment]
Running on physical RHEL server with jar file, this error happens after it has been up for more than 4+ hours.

It's almost like prior connections into it have not closed.

We also have a security scanner which may be slamming it. I have tried to whitelist the IP's.

John

**Comment by tchiotludo** [comment]
open files limit is 10240 is really low nowdays, why so low one? 
even on a desktop computer, it's unlimited : 
![image](https://user-images.githubusercontent.com/2064609/207694010-df2ae34a-e0e6-40de-8b0e-743716128575.png)

**Comment by johhue** [comment]
We can increase, but our UNIX admins are reluctant to increase if the app should be closing files and I need to explain why. Is there a way to know WHY we have the open files in use at any given time. What I see are copies of akhq.jar. Is it because of # of users/inbound connections, # of topics?. We are also behind a load balance which may be doing health checks as well ....

**Comment by tchiotludo** [comment]
Maybe you can have some information on [monitoring endpoint](https://akhq.io/docs/debug.html#monitoring-endpoint)? 
Has I know, there is multiple socket connection per kafka cluster, schema registry, kafka connect, etc ...  registered in AKHQ. Plus, add sockets for every http client (users and healthcheck).

**Comment by johhue** [comment]
Thank you I don't see in lsof too many TCP connections, just copies of akhq.jar.

John

**Comment by tchiotludo** [comment]
ok :+1:
