### ISSUE TITLE
Errors when encoding characters

### ISSUE THREAD

**Issue by maxm86545** [tchiotludo/akhq#1323]
When I remove a consumer group with a colon, I get a 409 error:

````
 /api/docker-kafka-server/group/topic%253Aname
 
 {"message":"The group id does not exist.","_links":{"self":{"href":"/api/docker-kafka-server/group/topic%253Aname","templated":false}}}
````

If I send a direct request without encoding, then the consumer group is removed successfully:
 
````
/api/docker-kafka-server/group/topic:name
````

Version 0.23.0

**Comment by tchiotludo** [comment]
This [pull request](https://github.com/tchiotludo/akhq/commit/8ddb9cb7ebc1d073a1d854087b57583dd26216ed) should have fix this. 
Do you have the issue with latest dev version?
