### ISSUE TITLE
Override configs deleted when updating connector

### ISSUE THREAD

**Issue by alozano3** [tchiotludo/akhq#1336]
I am using JDBC connector. I have properties that override the underlying kafka producer, for example _producer.override.sasl.jaas.config_ . 

When I update the configs using the form, these properties get deleted. The problem is that the form retrieves the specific connector properties using the /config/valdiate endpoint of Connect REST API and those properties are not included. When updating the connector, those properties are not sent and get deleted.

I have tried to include those configs in the form or even hidden so they get sent. But I am not fluent in React so I guess there is a better option.

**Comment by tchiotludo** [comment]
Strange I've the feeling this one was already fix in the past, but can't find it on the code. 
Mostly I think it's an equivalent of the [one]( https://github.com/tchiotludo/akhq/commit/8c908c99) but any properties that that is not on validate.
PR are welcome !
