### ISSUE TITLE
Some Kafka headers are not displayed if type is not String

### ISSUE THREAD

**Issue by gschmutz** [tchiotludo/akhq#1342]
Hi

First, thanks a lot for this great tool!

When using the Dead-Letter topic support of Spring Kafka, then a message which is sent to the dead-letter topic includes the original-partition and the original-offset of the message as Kafka Headers. Partition is of type Integer and Offset of type Long and therefore they are not visible when showing the header details. The same is true for the original timestamp. 

![akhq-with-header](https://user-images.githubusercontent.com/3357942/211204900-8d3b440f-d113-46ef-85f5-2c3587b6eeb9.png)

**Comment by tchiotludo** [comment]
Hi @gschmutz, 

Thanks for the report, but this one is really complicated it seems. 
For now, AKHQ don't have any mapping of type and you failed on the same [issues](https://github.com/tchiotludo/akhq/issues/842) than for the body, but for the headers. 
Except manual configuration for the topic, I don't have any clues to handle that. 
If you have an idea, it's welcome

**Comment by gschmutz** [comment]
@tchiotludo I did understand the difficult for both key and value, as their types are provided by the Kafka producer client. 

To be honest, until now (after checking the javadoc) I realized that the header value is a byte[] and not an Object. Which makes sense, so that it is Interoperable. That of course makes it impossible to handle the value without knowing how it has been serialized. 

First I thought you could display a special value instead of empty but even that will not work because it was only the case because both offset and partition were single digits. I just found it confusing because first I thought the DLQ message did not contain values for these two headers.

Lessons learnt I guess is, that if using headers of type other than String makes it really hard for a consumer to handle in a generic way. Now I understand why all the visualization tools I have tried have the same problem with headers.

**Comment by gschmutz** [comment]
Assuming that the Strings are encoded iin UTF-8, I found this java code here to detect it: <https://stackoverflow.com/questions/1193200/how-can-i-check-whether-a-byte-array-contains-a-unicode-string-in-java>.

```java
    static boolean looksLikeUTF8(byte[] utf8) throws UnsupportedEncodingException
    {
        Pattern p = Pattern.compile("\\A(\n" +
                "  [\\x09\\x0A\\x0D\\x20-\\x7E]             # ASCII\\n" +
                "| [\\xC2-\\xDF][\\x80-\\xBF]               # non-overlong 2-byte\n" +
                "|  \\xE0[\\xA0-\\xBF][\\x80-\\xBF]         # excluding overlongs\n" +
                "| [\\xE1-\\xEC\\xEE\\xEF][\\x80-\\xBF]{2}  # straight 3-byte\n" +
                "|  \\xED[\\x80-\\x9F][\\x80-\\xBF]         # excluding surrogates\n" +
                "|  \\xF0[\\x90-\\xBF][\\x80-\\xBF]{2}      # planes 1-3\n" +
                "| [\\xF1-\\xF3][\\x80-\\xBF]{3}            # planes 4-15\n" +
                "|  \\xF4[\\x80-\\x8F][\\x80-\\xBF]{2}      # plane 16\n" +
                ")*\\z", Pattern.COMMENTS);

        String phonyString = new String(utf8, "ISO-8859-1");
        return p.matcher(phonyString).matches();
    }
```

I have tested it and it works fine detecting Strings (True) and Long/Integer (False). I have also tested it as part of AKHQ and it looks good at least for my test.

![akhq-with-header-nostring](https://user-images.githubusercontent.com/3357942/211349666-f8994b52-af32-428b-8906-fede8a2d3721.png)

Might want to do some more testing, but it looks promising. 

I can also create a pull-request if you like, question is what kind of value would you want if it can not be converted to if it is not text?

**Comment by gschmutz** [comment]
BTW: I have also tested various other options such as `StringUtils` from commons-codec and Apache Tika but with less success.

**Comment by tchiotludo** [comment]
Everything that will allow us to better representation without hard configuration is better, so for sure, PR will be accepted ! :rocket:

**Comment by gschmutz** [comment]
Have created the PR, header values of type Long, Short and Integer are now handled and displayed correctly. 

![akhq-with-pr](https://user-images.githubusercontent.com/3357942/213923358-ae5a31e2-6e05-4284-b154-b1d1fe3d1424.png)
