### ISSUE TITLE
schema registry doesn't URL encode subject name

### ISSUE THREAD

**Issue by baganokodo2022** [tchiotludo/akhq#1353]
Hi team,

I found an issue in the Schema Registry view on those imported Protobuf schemas, which typically have forward slash in the subject name, as shown in the screen shot. We need to URL encode these subject names, otherwise, clicking on the subject will take you back to the topic view.

Cheers
![Screenshot 2023-01-24 at 2 16 31 PM](https://user-images.githubusercontent.com/116464387/214434695-f43f9de8-1379-425c-9f53-36464f57d61a.png)

**Comment by tchiotludo** [comment]
seems to be the same issue than this one from consumer groups: https://github.com/tchiotludo/akhq/pull/1184
PR are welcome :+1:

**Comment by baganokodo2022** [comment]
I have the fix working locally, will submit a PR today.

**Comment by baganokodo2022** [comment]
HI @tchiotludo ,

With I push my branch, I saw the following error, would you grant me permission to git push?
$ git push origin xinyuliu/fix-issues-1353

ERROR: Permission to tchiotludo/akhq.git denied to baganokodo2022.
fatal: Could not read from remote repository.

thank you

**Comment by tchiotludo** [comment]
you need to create a fork and create a pull request

**Comment by baganokodo2022** [comment]
@tchiotludo 

Here is the PR https://github.com/tchiotludo/akhq/pull/1354, please review.

thank you

Xinyu Liu
