### ISSUE TITLE
Copying failing events from DLT to main Topic causes infinite loop

### ISSUE THREAD

**Issue by NickWel** [tchiotludo/akhq#1377]
When using the "copy topic" function to copy an event from the DLT to the main topic this causes an infinite loop if the event immediatly fails and is republished to the DLT again.

The "copy topic" function seems to also copy any new events that are published to the topic after the copy action has started. If new events are published to this topic faster than these can be copied this copy action never ends.

This issue can be reproduced reliably by creating two topics with a service consuming events from one topic and publishing the same events to the other topic. Manually add 4 events to the second topic and start the "copy topic" action. Now watch the consumer lag increase rapidly.

**Comment by tchiotludo** [comment]
The bug is [here](https://github.com/tchiotludo/akhq/blob/c470b97462a54e969ed76dc419b718f39d48beb4/src/main/java/org/akhq/repositories/RecordRepository.java#L1008). We need to fetch the offset of the source top at first and stop after reaching this offset.
PR are welcome
