### ISSUE TITLE
[dev] Regressions on produce screen and forms layout

### ISSUE THREAD

**Issue by AlexisSouquiere** [tchiotludo/akhq#1381]
When I'm running to dev branch locally I'm facing somes issues that might be regressions since 0.23.0
- Dropdowns on the produce to topic screen seems to be broken due to #1335. The unused "options" parameter in renderDropdown has been removed but this parameter was sent in TopicProduce and it brokes the dropdowns on this page
![image](https://user-images.githubusercontent.com/2262145/219034616-f2333c37-9e5d-4bdb-89ec-5373663804ca.png)

- Multi / Tombstone checkboxes seems to be broken too due to #1254. When I click on it, nothing happens. There is a extra 2nd parameter given in the renderCheckbox that shifts all the other parameters and cause the issue
![image](https://user-images.githubusercontent.com/2262145/219034945-3bd9de69-7879-4256-8e31-77b7c30afdd8.png)

- Globaly the forms layout changed and some inputs are not displayed on the same line as the label
![image](https://user-images.githubusercontent.com/2262145/219035605-0f65dd04-749f-4f03-a1e7-a3a02d9b51f1.png)
![image](https://user-images.githubusercontent.com/2262145/219035855-54617077-101f-4d45-923b-f02003e4d821.png)

Am I the only one having the issue ? I just want to be sure of it (because it's frontend :sweat_smile:) before creating a PR for this branch https://github.com/AlexisSouquiere/akhq/commit/123870c5e4a186522efe33cc72cd37976a80c272.

I saw that one of my change is reverting one of your change @tchiotludo (https://github.com/tchiotludo/akhq/pull/1254/commits/9e2ee4ae82258c34e9fd90c9023ff0ed42c8eddf) so it's kind of strange

cc @lucapette as you seems to be the fronted expert !

**Comment by tchiotludo** [comment]
@lucapette do you will have time to look or not? This one is blocking a release

**Comment by lucapette** [comment]
@tchiotludo @AlexisSouquiere oh my. No idea how I missed this. I'll have a look now :)

**Comment by AlexisSouquiere** [comment]
@lucapette if you can the same issue then you can check my branch https://github.com/AlexisSouquiere/akhq/commit/123870c5e4a186522efe33cc72cd37976a80c272 where I fixed it. If you think that its the right fix I'll create the PR

**Comment by lucapette** [comment]
@AlexisSouquiere 👏 amazing work!

I'm not sure how I didn't catch this at the time I did the prs you mentioned. On one side, it was a lot work, on the other I tested the produce page every time... anyway, thanks to you, it's going to be fixed soon.


I'd open a pr as is. I thought I had changed the way we do default classes on input too but apparently I only did it on Select (something like `<div className={`${wrapperClass || 'form-group row'}`}>`) so if you want you can also do that (the code looks a little better I think but I can take care of it in a subsequent pr).


@tchiotludo Feb was a pretty busy month for me but, from the look of it, I may have some time in the coming weeks. I took lots of notes about a potential react upgrade. Should I open an issue so we make a plan? (no strings attached)

**Comment by tchiotludo** [comment]
@lucapette yes tracking in an issue or draft PR can be a good start (and no worries, we all have things that pay the bill to do :smile:)

**Comment by lucapette** [comment]
@tchiotludo I'll open an issue with a plan draft soon. It's quite some work but I think the end result would be pretty good for the frontend code

**Comment by AlexisSouquiere** [comment]
@lucapette thanks :) I won't have time to work on it today so I create the PR as it but yes we can still clean it in a future PR
