### ISSUE TITLE
No ksqldb in UI, is ksqldb already available or only in dev??

### ISSUE THREAD

**Issue by lzwaan** [tchiotludo/akhq#1389]
Hi,

We are happy users of AKHQ, the last feature missing was our ksqldb cluster available in AKHQ. We configured akhq in docker-compose, all working fine accept ksqldb is not visible in the UI. Do we miss something or is it not availbable yet?

Example config, using SCRAM-512 and kafka ACLs are configured. For kafka, schema-registry and our connect nodes this is working fine. Last question: it also possible to configure multiple schema-registries?

`connect:
  - name: nlut-kafkaconnect01
    url: "http://nlut-kafkaconnect01.mydomain:8083"
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-512
      ssl.keystore.location: /app/ssl/kafka.keystore.jks
      ssl.keystore.password: <PASSWORD>
      ssl.truststore.location: /app/ssl/kafka.truststore.jks
      ssl.truststore.password: <PASSWORD>
      ssl.key.password: <PASSWORD>
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="kafka" password="<PASSWORD>";
ksqldb:
  - name: nlut-kafkastreaming01
    url: "https://nlut-kafkastreaming01.mydomain:8088"
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-512
      ssl.keystore.location: /app/ssl/kafka.keystore.jks
      ssl.keystore.password: <PASSWORD>
      ssl.truststore.location: /app/ssl/kafka.truststore.jks
      ssl.truststore.password: <PASSWORD>
      ssl.key.password: <PASSWORD>
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="kafka" password="<PASSWORD>";
  - name: nlut-kafkastreaming02
    url: "https://nlut-kafkastreaming02.mydomain:8088"
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-512
      ssl.keystore.location: /app/ssl/kafka.keystore.jks
      ssl.keystore.password: <PASSWORD>
      ssl.truststore.location: /app/ssl/kafka.truststore.jks
      ssl.truststore.password: <PASSWORD>
      ssl.key.password: <PASSWORD>
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="kafka" password="<PASSWORD>";
`

We build our own docker image so it includes our root ca, as we otherwise have ssl issues with our schema-registry and ksqldb
docker-compose.yml
`version: '3.6'

services:
  akhq:
    build:
      context: ./build
    #image: tchiotludo/akhq
    image: localbuild/akhq
    container_name: akhq
    restart: always
    user: root
    ports:
      - 8080:8080
    volumes:
      - ./etc/application.yml:/app/application.yml:ro
      - /opt/cluster/ssl/ssl:/app/ssl:ro
    environment:
      TZ: "${TZ:-Europe/Amsterdam}"
`

**Comment by tchiotludo** [comment]
Yes it's not already available on the latest release, you can use the `dev` branch to give a try
