### ISSUE TITLE
html-head css insertion not working with version 0.24.0

### ISSUE THREAD

**Issue by jheinitz** [tchiotludo/akhq#1451]
Hello,

We have configured a section in our `application.yml` file to display a colored string under the AHKQ.io logo in the upper left corner of the menu. We followed the documentation from [here](https://akhq.io/docs/configuration/akhq.html#inject-some-css-or-javascript).  This worked well with version `0.23.0`, but does no longer work with version `0.24.0`. Is there anything I have to change in the configuration in order to make it work again or is it a bug? Here is the extract of my config:
```
akhq:
  html-head: |
    <style type="text/css">
     .logo-wrapper:after {
       display: block;
       content: "test";
       height: 24px;
       position: relative;
       text-transform: capitalize;
       font-weight: bold;
       text-align: center;
       background-color: darkgreen;
       color: white;
       font-size: 24px;
       margin-top: 8px;
     }
    </style>
``` 
Please let me know if you need more information.

Thanks and best regards

Jens
________________________________
O/S: RHEL 8.6
Docker Version: 20.10.17
Arch: x86_64

**Comment by jheinitz** [comment]
Hello!

Anyone with an idea on this? @tchiotludo @AlexisSouquiere 

I followed this part of the official documentation: https://akhq.io/docs/configuration/akhq.html#topic-data-1

It would be very helpful to get this feature back. Thanks.

Best regards

Jens

**Comment by AlexisSouquiere** [comment]
I'll check it by the end of the week and get back to you (I don't know this feature yet) :)

**Comment by jheinitz** [comment]
Any news on this? By the way, it's end of week again .... ;-)

**Comment by tchiotludo** [comment]
> Any news on this? By the way, it's end of week again .... ;-)

Or maybe, you can contribute instead of complaining ? :thinking:

**Comment by jheinitz** [comment]
> > Any news on this? By the way, it's end of week again .... ;-)
> 
> Or maybe, you can contribute instead of complaining ? 🤔

Sorry, if you got me wrong. I did not want to complain at all. I really appreciate all the efforts that are going into this project by all the people. That's why I have put the ";-)" behind my comments. Sorry again. 

Regarding contribution, I have no idea where to start looking ...

**Comment by AlexisSouquiere** [comment]
Issue seems to be with the / that has been added in the meta tag to replace
https://github.com/tchiotludo/akhq/blob/dev/client/public/index.html#L10

During this meta replacement, the pattern won't match because of this extract slash.
https://github.com/tchiotludo/akhq/blob/dev/src/main/java/org/akhq/controllers/StaticFilter.java#L75

I don't have time to update and test it but I'm 99% sure adding this slash in the replace will fix the issue

**Comment by jheinitz** [comment]
Hi!

Thanks for merging. I did a quick test with the new docker image, but it is still not working. I'm trying to dive deeper on Monday. Seems that the `/` has to be removed, because when I open the DevTools in the Chrome Brower, I still see a line like this:
```
<meta name="html-head" content="replace">
```

Sorry for the bad news. :-(

Have a nice weekend.
