### ISSUE TITLE
How to enable ksqldb in akhq?

### ISSUE THREAD

**Issue by VisionaryAries** [tchiotludo/akhq#1457]
AKHQ 0.24.0 support ksqldb, and I'm very looking forward to use ksqldb in AKHQ. but docs don't describe how to configure it in configuration.yml. Who can show me? Thanks in advance.

**Comment by AlexisSouquiere** [comment]
I didn't tried it but look in the application-dev.yml file for the new ksqldb settings
https://github.com/tchiotludo/akhq/blob/dev/application-dev.yml#L20

**Comment by VisionaryAries** [comment]
Thanks @AlexisSouquiere , I tried the ksqldb settings, but it doesn't work.
https://github.com/tchiotludo/akhq/blob/dev/application-dev.yml#L20

**Comment by AlexisSouquiere** [comment]
Do you have the new permissions (ksqldb/read and ksqldb/execute) in the application.yml file ? 
https://github.com/tchiotludo/akhq/blob/6e0deae6e3e588ac52535789a282b2c903491c4b/src/main/resources/application.yml#L160
