### ISSUE TITLE
Opening DLT topic does not show messages

### ISSUE THREAD

**Issue by LeeLenaleee** [tchiotludo/akhq#1460]
Using version [0.24.0](https://github.com/tchiotludo/akhq/releases/tag/0.24.0) of AKHQ.

A message gets pushed in a DLT topic. When I open that topic there are no messages visible. Only after I update the sort from `oldest` to `newest` the message's appear. After that I can change it back to `oldest` and it still works fine. It only seems to affect initial load.

**Comment by tchiotludo** [comment]
you need to increase `akhq.topic-data.poll-timeout`, see [here](https://akhq.io/docs/configuration/akhq.html)
