### ISSUE TITLE
Topic Page: Read actions are hidden behind an insert permissions check

### ISSUE THREAD

**Issue by meiamsome** [tchiotludo/akhq#1488]
On the Topic Page, the [Download](https://github.com/tchiotludo/akhq/blob/2f4b020dcbb1cb367885c6b29baafb8ab5b44a62/client/src/containers/Topic/Topic/Topic.jsx#L312-L323) and [Live Tail ](https://github.com/tchiotludo/akhq/blob/2f4b020dcbb1cb367885c6b29baafb8ab5b44a62/client/src/containers/Topic/Topic/Topic.jsx#L351-L356) buttons are hidden under a permissions check for `topic/data/insert` when they are read-only:

https://github.com/tchiotludo/akhq/blob/2f4b020dcbb1cb367885c6b29baafb8ab5b44a62/client/src/containers/Topic/Topic/Topic.jsx#LL309C67-L309C84

**Comment by tchiotludo** [comment]
Hey nice catch, PR are welcome !

**Comment by tchiotludo** [comment]
@AlexisSouquiere totally agree ;)

**Comment by tchiotludo** [comment]
done in #1472
