### ISSUE TITLE
Vulnerability in the akhq latest jar

### ISSUE THREAD

**Issue by ajbisht** [tchiotludo/akhq#1493]
Hi,

We are trying to deploy AKHQ in AKS cluster but we have a docker image scanner in the CICD pipeline, which is failing the pipeline because it has vulnerabilities. I have fixed the Base images vulnerabilities but the AKHQ jar vulnerabilities I am not able to fix. Below are the two vulnerabilities 

net.minidev_json-smart version 2.4.7 -- this is fixed in 2.4.9 version
com.fasterxml.jackson.core version 2.4.1 -- this is fixed in 2.5.0 version

Can you check if Jar can be build using above versions?

**Comment by tchiotludo** [comment]
duplicate #1447 & #1471
