### ISSUE TITLE
Delete on internal topic "connect-cluster-offsets" does not work anymore

### ISSUE THREAD

**Issue by koan-tunes** [tchiotludo/akhq#1498]
Hi there

With the new version, a "delete message" on the internal cluster topic "connect-cluster-offsets" in order to create an tombstone, does not seem to work anymore.

Steps to reproduce:

1. Navigate to an internal cluster topic "connect-cluster-offsets"
2. Click on the Delete-Button on any record in the list
3. A dialog pops up for user confirmation. However, clicking "Ok" has no effect.

![kafka-offsets-delete](https://github.com/tchiotludo/akhq/assets/58424554/cb431b8e-f003-44fe-a0a3-84a0c01679cc)

Cheers

**Comment by AlexisSouquiere** [comment]
@koan-tunes same as #1458
@tchiotludo can you tag these issues as bug ?
