### ISSUE TITLE
Topic Search Filter not work as expected

### ISSUE THREAD

**Issue by teimyBr** [tchiotludo/akhq#1532]
Im searching in Kafka Topic over the filter in akhq. 

Search 1: Value // Commercial // Contains 

```
{
  "id": "04e2da4c-26a2-4073-82cb-e90ab334fa0c",
  "model": "Commercial"
}

{
  "id": "fb280b17-76cb-4698-b075-edc9028f70e8",
  "model": "Commercial"
}
```

Search 2: Value // Commercial// Not Contains

```
{
  "id": "04e2da4c-26a2-4073-82cb-e90ab334fa0c",
  "model": "Commercial"
}

{
  "id": "fb280b17-76cb-4698-b075-edc9028f70e8",
  "model": "Commercial"
}
```

shows exact the same records. 

What i expect is that the AKHQ show in Query 2 non of this records.

AKHQ Version: 0.24 
Kafka Version 3.4

**Comment by AlexisSouquiere** [comment]
I experienced the same behaviour. I started to work on it (https://github.com/AlexisSouquiere/akhq/tree/feat/fix-search) and will propose a PR soon

**Comment by AlexisSouquiere** [comment]
@teimyBr can I have your feedback on the proposal I did in the mentioned PR just above ?

**Comment by teimyBr** [comment]
Yes tested it out seems like the filter works very good now
