### ISSUE TITLE
Error 502 with k8s and keycloak

### ISSUE THREAD

**Issue by dimonleksin** [tchiotludo/akhq#1585]
Hello. I'm using Kafka 2.7.1 with akhq 0.24.0 and keycloak 21.1. Deployed in k8s. Used "use-oidc-claim: true" and when I return 75+ topics (not regex, full topic name) in claim from keycloak, I see 502 error from akhq. I can't use a regular expression because there are 3000 topics stored in Kafka, and information security people don't allow the use of a regular expression because there is a risk of giving access to topics that shouldn't be available.
In logs i'm don't see errors

**Comment by dimonleksin** [comment]
micronaut:
  security:
    enabled: true
    oauth2:
      enabled: true
      clients.keycloak:
        client-id: {{ .Values.oidc.id }}
        client-secret: {{ .Values.oidc.secret }}
        openid:
          issuer: {{ .Values.oidc.issuer }}
          end-session:
            url: {{ .Values.oidc.logout }}
    token:
      jwt:
        enabled: true
akhq:   
  server:
    access-log: # Access log configuration (optional)
      enabled: true # true by default
      name: org.akhq.log.access # Logger name
      format: "[Date: {}] [Duration: {} ms] [Url: {} {}] [Status: {}] [Ip: {}] [User: {}]"
  connections:
    kafka-app-test:
      properties:
        bootstrap.servers: {{ .Values.kafka.brokers }}
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: SCRAM-SHA-256
        sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username={{ .Values.kafka.username }} password={{ .Values.kafka.password }};
  security:
    default-group: no-roles
    oidc:
      enabled: true
      providers:
        keycloak:
          username-field: preferred_username
          use-oidc-claim: true

In ingress manifest i`m add 
nginx.ingress.kubernetes.io/server-snippet: |
      client_header_buffer_size 512k;
      large_client_header_buffers 4 64k;

In log, if succesful login, i`m see JWT and deserialization claims, but if not succesful login, in log i see only deserialization claims and don`t see JWT.

**Comment by dimonleksin** [comment]
If i`m set authentication: bearer, AKHQ don`t redirect me to keycloack and in logs i`m see this:
2023-10-30 09:18:04,768 DEBUG pGroup-1-6 s.t.r.DefaultTokenResolver Request GET, /oauth/login/keycloak, no token found.
2023-10-30 09:18:04,768 DEBUG pGroup-1-6 i.m.s.rules.IpPatternsRule One or more of the IP patterns matched the host address [10.42.6.0]. Continuing request processing.
2023-10-30 09:18:04,768 DEBUG pGroup-1-6 .m.s.r.InterceptUrlMapRule No url map pattern exact match found for path [/oauth/login/keycloak] and method [GET]. Searching in patterns with no defined method.
2023-10-30 09:18:04,768 DEBUG pGroup-1-6 .m.s.r.InterceptUrlMapRule No url map pattern match found for path [/oauth/login/keycloak]. Returning unknown.
2023-10-30 09:18:04,768 DEBUG pGroup-1-6 i.m.s.f.SecurityFilter     Authorized request GET /oauth/login/keycloak. No rule provider authorized or rejected the request.
2023-10-30 09:18:04,818 DEBUG pGroup-1-6 .t.r.HttpHeaderTokenReader Looking for bearer token in Authorization header
2023-10-30 09:18:04,818 DEBUG pGroup-1-6 s.t.r.DefaultTokenResolver Request GET, /ui/login, no token found.

**Comment by dimonleksin** [comment]
Hi, is any news for this issue?

**Comment by AlexisSouquiere** [comment]
@dimonleksin issue about bearer auth with OIDC provider seems to be the same as #1621.
Unfortunately we can't get ride of the 4Kb cookie limit. And putting this amount of topics in your payload won't fit in any cases (unless using regex).

I plan to create a PR to support JWT payload compression but in your case, where the JWT token is sent by Keycloak, the only solution I can see will be to do the same compression (gzip compression then base64 encoding of the payload (`groups` field of the token)) on your side. I don't have real experience with Keycloak so I don't know how you are handling the token generation or if it's possible. What do you think ?

**Comment by dimonleksin** [comment]
I'm not sure if keycloak supportet gzip compression for sending JWT. I'll check it and come back with the result

**Comment by dimonleksin** [comment]
So, keycloak can't compress JWT. Anyway thanks for help

**Comment by AlexisSouquiere** [comment]
@dimonleksin I setup a keycloak on my dev environment and performed some tests to validate the JWT payload compression. 
I put my environment in the same condition as yours: `use-oidc-claim: true`. All the user groups are returned by keycloak. See the following screenshot for my keycloak user akhq 
![image](https://github.com/tchiotludo/akhq/assets/2262145/e58fcd13-14ae-4004-9a61-320604922c48)

Even in your case you will benefit from the JWT compression. I understand now how AKHQ handles OIDC (and direct mapping especially) and in fact it will also work for you.
