### ISSUE TITLE
"no-role" group is matched after authentication

### ISSUE THREAD

**Issue by YaroslavYakymenko** [tchiotludo/akhq#1586]
I can't re-open issue:  https://github.com/tchiotludo/akhq/issues/1562
Details are added here: https://github.com/tchiotludo/akhq/issues/1562#issuecomment-1737203121

**Comment by AlexisSouquiere** [comment]
@YaroslavYakymenko you are testing to login with a user without any permissions -> matching the no-role group, right ?
When I test it on my side I can reproduce the issue. I didn't managed correctly the default-group without any roles.

I can propose to put a message saying that the user is logged in but doesn't have any roles

![image](https://github.com/tchiotludo/akhq/assets/2262145/c0874108-bb37-4f3e-917f-070300971a14)

**Comment by YaroslavYakymenko** [comment]
Yes, you are right. I tested login without any roles

**Comment by AlexisSouquiere** [comment]
Thanks for the confirmation. I just submitted a PR to clarify this case
