### ISSUE TITLE
context-path failing when accessing via reverse proxy 

### ISSUE THREAD

**Issue by zencircle** [tchiotludo/akhq#1590]
We are trying to route traffic to akhq via api gateway [ambassador]. (https://www.getambassador.io/docs/emissary/latest/tutorials/getting-started)
See the helm configuration below
```
helm upgrade --install -f akhq-values.yaml -n strimzi akhq akhq/akhq
```
```
configuration:
    micronaut:
      server:
        context-path: "/akhq"
      security:
        enabled: false
    akhq:
      server:
        access-log:
          enabled: true
          name: org.akhq.log.access
      connections:
        strimzi:
          properties:
            bootstrap.servers: "strimzi-cluster-kafka-bootstrap.strimzi:9092"

readinessProbe:
  enabled: true
  prefix: "/akhq"

livenessProbe:
  enabled: true
  prefix: "/akhq"
```
Accessing via https://example.com/akhq we get the following error within the browser 
``
{"message":"Internal Server Error: Expected authority at index 2: //","_links":{"self":{"href":"/","templated":false}},"_embedded":{"stacktrace":[{"message":"java.net.URISyntaxException: Expected authority at index 2: //\n\tat java.base/java.net.URI$Parser.fail(Unknown Source)\n\tat java.base/java.net.URI$Parser.failExpecting(Unknown Source)\n\tat java.base/java.net.URI$Parser.parseHierarchical(Unknown Source)\n\tat java.base/java.net.URI$Parser.parse(Unknown Source)\n\tat java.base/java.net.URI.<init>(Unknown Source)\n\tat java.base/java.net.URI.create(Unknown Source)\n\tat io.micronaut.http.netty.AbstractNettyHttpRequest.<init>(AbstractNettyHttpRequest.java:76)\n\tat io.micronaut.http.server.netty.NettyHttpRequest.<init>(NettyHttpRequest.java:171)\n\tat io.micronaut.http.server.netty.decoders.HttpRequestDecoder.decode(HttpRequestDecoder.java:80)\n\tat io.micronaut.http.server.netty.decoders.HttpRequestDecoder.decode(HttpRequestDecoder.java:45)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)\n\tat io.micronaut.http.netty.stream.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:224)\n\tat io.micronaut.http.netty.stream.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:134)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)\n\tat io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)\n\tat io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:109)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)\n\tat io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)\n\tat io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)\n\tat io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)\n\tat io.netty.handler.codec.http.HttpServerKeepAliveHandler.channelRead(HttpServerKeepAliveHandler.java:64)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)\n\tat io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202)\n\tat io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)\n\tat io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)\n\tat io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)\n\tat io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)\n\tat io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)\n\tat io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)\n\tat io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)\n\tat io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)\n\tat io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.base/java.lang.Thread.run(Unknown Source)\n"}]}}
``
It seems its redirect that `https://example.com/akhq` is redirected to `https://example.com/akhq/`

**Comment by tchiotludo** [comment]
I don't think readiness livenessProbe can have a prefix and is not affected by `context-path`

**Comment by zencircle** [comment]
See the output if the remove the probes, `kubectl -n strimzi describe pods akhq`
```
Name:         akhq-95fc7d479-hv8rv
Namespace:    strimzi

Status:       Running

Controlled By:  ReplicaSet/akhq-95fc7d479
Containers:
  akhq:
    Container ID:   containerd://0cdf5817d007e1cfd189c126cf0925441f4de8a687d21165d83eadfb4c5e9a7a
    Image:          tchiotludo/akhq:0.24.0
    Image ID:       docker.io/tchiotludo/akhq@sha256:6ccf8323ae6e93a893107f857cd9f7210add3569743b2c8528c6567967cc636f
    Ports:          8080/TCP, 28081/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Tue, 10 Oct 2023 14:39:32 -0400
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Tue, 10 Oct 2023 14:38:32 -0400
      Finished:     Tue, 10 Oct 2023 14:39:32 -0400
    Ready:          False
    Restart Count:  1
    Liveness:       http-get http://:management/health delay=5s timeout=5s period=10s #success=1 #failure=3
    Readiness:      http-get http://:management/health delay=5s timeout=5s period=10s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /app/application.yml from config (rw,path="application.yml")
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-5dtwp (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      akhq
    Optional:  false
  kube-api-access-5dtwp:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                From               Message
  Normal   Scheduled  71s                default-scheduler  Successfully assigned strimzi/akhq-95fc7d479-hv8rv to ip-xxxl
  Normal   Pulled     70s                kubelet            Successfully pulled image "tchiotludo/akhq:0.24.0" in 217.682527ms (217.697357ms including waiting)
  Normal   Killing    40s                kubelet            Container akhq failed liveness probe, will be restarted
  Normal   Pulling    10s (x2 over 70s)  kubelet            Pulling image "tchiotludo/akhq:0.24.0"
  Normal   Created    10s (x2 over 70s)  kubelet            Created container akhq
  Normal   Started    10s (x2 over 70s)  kubelet            Started container akhq
  Normal   Pulled     10s                kubelet            Successfully pulled image "tchiotludo/akhq:0.24.0" in 234.165745ms (234.179179ms including waiting)
  Warning  Unhealthy  0s (x8 over 60s)   kubelet            Readiness probe failed: HTTP probe failed with statuscode: 404
  Warning  Unhealthy  0s (x4 over 60s)   kubelet            Liveness probe failed: HTTP probe failed with statuscode: 404
```

**Comment by tchiotludo** [comment]
ok my fault, the prefix exits, I totally forgot. 
The healthcheck is not accessible outside of the pods, you need to go inside the pod : 
```
curl http://localhost:28081/akhq/health 
```
when using the 
```yaml
readinessProbe:
  enabled: true
  prefix: "/akhq"
```
What is the result ?

**Comment by zencircle** [comment]
> curl http://localhost:28081/akhq/health
```
akhq@akhq-6b4846b667-z27k5:/app$ curl http://localhost:28081/akhq/health
{"name":"akhq","status":"UP","details":{"compositeDiscoveryClient()":{"name":"akhq","status":"UP"},"diskSpace":{"name":"akhq","status":"UP","details":{"total":53674487808,"free":38336397312,"threshold":10485760}},"service":{"name":"akhq","status":"UP"}}}
```

**Comment by tchiotludo** [comment]
so the health is ok, what is the current state of the pods (with describe)?

**Comment by zencircle** [comment]
Yes, this is the state when I am getting the error
```
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      akhq
    Optional:  false
  kube-api-access-mmtts:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  25m   default-scheduler  Successfully assigned strimzi/akhq-6b4846b667-z27k5 to ip-10-xx
  Normal  Pulling    25m   kubelet            Pulling image "tchiotludo/akhq:0.24.0"
  Normal  Pulled     25m   kubelet            Successfully pulled image "tchiotludo/akhq:0.24.0" in 216.608213ms (216.62413ms including waiting)
  Normal  Created    25m   kubelet            Created container akhq
  Normal  Started    25m   kubelet            Started container akhq
```

**Comment by zencircle** [comment]
Logs enteries in my API Gateway 
```
ACCESS [2023-10-10T20:59:03.165Z] "GET /akhq HTTP/1.1" 307 - 0 0 2 2 "XXX" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" "76f3ec1c-6cad-432f-b047-d837bc31873a" "example.com" "172.20.12.125:80"
ACCESS [2023-10-10T20:59:03.193Z] "GET /akhq/ HTTP/1.1" 500 - 0 976 3 3 "XXX" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36" "c27a8937-e8be-4d67-a623-5cbd8c70e201" "example" "172.20.12.125:80"  (this log entry is added automatically, it seems /akhq is redirected to /akhq/ )
```
How does akhq handle slashes ?

Ambassador kubernetes API Gateway configuration for akhq
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      apiVersion: ambassador/v2
      kind: Mapping
      name: ambassador-akhq
      ambassador_id: ambassador-default-1
      prefix: /akhq
      service: akhq.strimzi.svc.cluster.local:80
  name: ambassador-akhq
spec:
  clusterIP: None
```

**Comment by zencircle** [comment]
`kubectl -n strimzi port-forward svc/akhq 9090:80`
`http://localhost:9090/` redirects to `http://localhost:9090/akhq/ui/strimzi/topic` No errors

**Comment by zencircle** [comment]
Found, problem was emissary ingress configuration and not `akhq`, emissary was adding trailing slash`/`
https://www.getambassador.io/docs/emissary/latest/topics/using/rewrites#rewrite
``` 
apiVersion: v1
kind: Service
metadata:
  annotations:
    getambassador.io/config: |
      apiVersion: ambassador/v2
      kind: Mapping
      name: ambassador-akhq
      ambassador_id: ambassador-default-1
      prefix: /akhq
      rewrite: ""
      service: akhq.strimzi.svc.cluster.local:80
  name: ambassador-akhq
spec:
  clusterIP: None
```
