### ISSUE TITLE
Cannot copy message if user doesn't have SCHEMA READ permission

### ISSUE THREAD

**Issue by pw-lehre** [tchiotludo/akhq#1597]
Hi,

when trying to copy a message with a user that doesn't have SCHEMA READ permission, this fails because `getPreferredSchemaForTopic()` doesn't account for that possibility.

Browser console:
```
GET https://<host>/api/<kafka-server>/schema/topic/<topic>
Uncaught (in promise) Object { status: 401, message: "Unauthorized", stacktrace: null }
```

It's actually the same for producing a new message, but there it doesn't matter as much.

This is annoying when you aren't using a schema for the topic - because it doesn't matter that the user does not have SCHEMA READ permission. IMHO, a warning like "Cannot determine if the topic has a schema, proceed with caution" or something would be enough here.

**Comment by AlexisSouquiere** [comment]
@pw-lehre Thanks for the alert. I will check this issue today and let you know

**Comment by AlexisSouquiere** [comment]
PR is ready.
I just check if user has permission to read schemas before calling getPreferredSchemaForTopic to prevent the issue.
I didn't put a warning message because people can have topics without schema and they would see this warning every time they want to publish a message.
