### ISSUE TITLE
Github Enterprise / SSO

### ISSUE THREAD

**Issue by kanimaru** [tchiotludo/akhq#1606]
Hi the #990 isn't done correctly the requester asked for Github Enterprise but the implementation referenced in the issue #1319 only works for github.com I think it has to be changed just a little to work with GHE also. 

The fix path in the https://github.com/tchiotludo/akhq/blob/dev/src/main/java/org/akhq/security/authentication/GithubApiClient.java#L11 needs to be configureable. But I'm not confident enough in micronaut to do it. 

```
@Client("https://api.github.com")
public interface GithubApiClient {
```

**Comment by JeniaTr** [comment]
![image](https://github.com/tchiotludo/akhq/assets/5598131/ee249278-c0b4-41ad-a382-6f18e42840cf)
![image](https://github.com/tchiotludo/akhq/assets/5598131/6a46e7e4-684b-4191-9821-25bfd03001ce)
I also have a problem with access from the organization when using GitHub SSO

**Comment by tchiotludo** [comment]
done in https://github.com/tchiotludo/akhq/pull/1613
