### ISSUE TITLE
Can't get html-head replacement to work

### ISSUE THREAD

**Issue by michelsantos10** [tchiotludo/akhq#1659]
### Discussed in https://github.com/tchiotludo/akhq/discussions/1415
(UI Settings - Inject some css or javascript does not work on 0.24.0)

<div type='discussions-op-text'>

<sup>Originally posted by **dstrivelli** January 17, 2023</sup>
Between updates from 0.23.0 to the current Dev version, the html-head replacement appears to have stopped working.

<img width="675" alt="image" src="https://user-images.githubusercontent.com/31289764/213000859-97d9d67b-3866-4587-ba27-cf9f309d246a.png">

When I rollback to the 0.23.0 version, my defined snippet is replaced into the HTML head as expected.
</div>

### CAUSE

The HTML code generated in version 0.24.0 is not the same as in 0.23.0 and the html-head replacement method fails.

| html code generated `in` 0.24.0 | html code generated `before` 0.24.0 |
|--------|--------|
| ```<meta name="html-head" content="replace"/>``` | ```<meta name="html-head" content="replace">``` |

Notice that there is a slash at the end that was added in version 0.24.0. In the [StaticFilter.java class](https://github.com/tchiotludo/akhq/blob/0.24.0/src/main/java/org/akhq/controllers/StaticFilter.java#L75), line 75, this is where the "html-head" is replaced. Note that the bar at the end is not taken into account, and this means that it does not match and the value is no longer replaced.

Please be aware that a trailing slash was introduced in version 0.24.0. The replacement of "html-head" occurs in the [StaticFilter.java class](https://github.com/tchiotludo/akhq/blob/0.24.0/src/main/java/org/akhq/controllers/StaticFilter.java#L75) class, specifically on line 75. It's important to note that the trailing slash is not considered during this process, resulting in a mismatch. Consequently, the value is not replaced.

**Comment by AlexisSouquiere** [comment]
This feature is working fine on dev.
It has been fixed in #1489
