### ISSUE TITLE
Fixing CI

### ISSUE THREAD

**Issue by shaneikennedy** [tchiotludo/akhq#1702]
Since my commit here https://github.com/tchiotludo/akhq/commit/64f904c3699d9cb758a6d3dfae6af44e7d20bf9f the `./gradlew check -no-daemon` step in CI is now producing more artefacts than before in the build dir

```
akhq git:dev
❯ ls build/distributions/
 akhq-0.24.0.tar   akhq-shadow-0.24.0.tar
 akhq-0.24.0.zip   akhq-shadow-0.24.0.zip
```

and cp is finding multiple targets for akhq-*.tar which is why it's complaining that akhq.tar is not a directory. 

For some reason, ./gradlew build complains about the incomplete dependency declaration that I found in 64f904c3699d9cb758a6d3dfae6af44e7d20bf9f, but gradle check doesnt....

I think for the purposes of fixing CI you can revert that commit for now.

**Comment by tchiotludo** [comment]
it's fixed here: https://github.com/tchiotludo/akhq/commit/1d234ebe0d949521a89fc02534d7c553c8856c92
