### ISSUE TITLE
Pagination: After searching with NEWEST the click on next page appends wrong "after"

### ISSUE THREAD

**Issue by jonasvoelcker** [tchiotludo/akhq#1752]
This is one sample URL getting generated when searching and using the pagination button:

https://www.test.de/ui/kafkaqmsk01/topic/xyz/data?sort=NEWEST&partition=All&searchByValue=Stephan_C&after=/api/kafkaqmsk01/topic/xyz/data?after=0-2896_1-2540_4-3383_5-3510_6-2910_7-2646_8-2937_11-2626_12-4453_13-2337_14-2566_15-2497_16-3463_17-4715&partition=All&sort=NEWEST

**Comment by alwibrm** [comment]
@tchiotludo At the moment this seems to be the only blocker for the release of 0.25.0.
