### ISSUE TITLE
LoadBalancerIP support in helm chart

### ISSUE THREAD

**Issue by likeMyCoffee** [tchiotludo/akhq#1766]
When using the Helm chart and configuring the service to "LoadBalancer", I would like to use a predetermined loadbalancer IP address.

In service.yaml could you add the following in line 20 ?

```
  {{- if (eq .Values.service.type "LoadBalancer") }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- end }}
```

Because I'm at work I'm not able to do the pull request thing :-)

**Comment by tchiotludo** [comment]
PR are welcome :smile:

**Comment by likeMyCoffee** [comment]
Wow never had the main dev respond this fast :-)

I don't do PRs too often so it's always an adventure.
I'll add a configurable pathType aswell :-)

Try and make the PR in a bit .... To be continued!!!
