### ISSUE TITLE
Is there going to be a master release for docker image tchiotludo/akhq

### ISSUE THREAD

**Issue by aonamrata** [tchiotludo/akhq#1767]
Hi,

There seem to have been lot of new changes and fixes to AKQH image since the last release [0.24.0](https://hub.docker.com/layers/tchiotludo/akhq/0.24.0/images/sha256-64d7c8308348c9f1522e2e21dfba5782df368fa32bf07e160b8a5ac1d6da6b8d?context=explore) Last pushed a year ago. All the new changes are going to the dev release. Should i switch our service to use that tag going forward or will there be a new master release that is more stable? Just going by the name dev feels more beta testing stage.

Thanks.

**Comment by tchiotludo** [comment]
latest information [here](https://github.com/tchiotludo/akhq/discussions/1644)
