### ISSUE TITLE
Feature / Ability to change the number of partitions via the web interface

### ISSUE THREAD

**Issue by GeorgeGeorge90** [tchiotludo/akhq#1768]
Hello @tchiotludo !

Do you plan to add to the web interface the ability to replace/add partitions in already created and working topics?

**Comment by AlexisSouquiere** [comment]
This feature has already been developed in #1601. It's accessible from the Partitions tab

 
<img width="1198" alt="image" src="https://github.com/tchiotludo/akhq/assets/2262145/e4a05274-ffd0-4cce-89c8-ec9e81b9f155">

Is there something else that you would need ?

**Comment by tchiotludo** [comment]
@GeorgeGeorge90 reopen if we are lacking a feature please
