### ISSUE TITLE
No schema-values when producing Events [0.25.0]

### ISSUE THREAD

**Issue by yannickpoggel** [tchiotludo/akhq#1783]
When trying to produce events to a topic, the auto-completion / dropdown of "Value schema" is empty in the new version of akhq.

![akhq0250](https://github.com/tchiotludo/akhq/assets/151126180/99cbf447-c78e-4a69-be4e-1c1198e5253a)

In the 0.24.0 release we can see the list of subjects in the schema-registry:
![akhq0240](https://github.com/tchiotludo/akhq/assets/151126180/ad99aa52-6246-41f5-8931-85216f941057)

We are using AVRO-Schemas with confluentinc/cp-schema-registry:7.5.3

**Comment by AlexisSouquiere** [comment]
Any logs (from AKHQ or from the browser console) ?
Can you share your application.yml to check for config issue with the new RBAC and permissions for the registry ?

**Comment by AlexisSouquiere** [comment]
Can you try to create a subject following the TopicNameStrategy ? myTopic --> myTopic-value
I quickly checked and we are following the TopicNameStrategy to build the key and value subject lists. This is probably why you don't see the SampleSubject

We probably need to add the other subjects in the 2 dropdowns to support the other naming strategies

**Comment by AlexisSouquiere** [comment]
Got it. It's definitely something that we can fix
