### ISSUE TITLE
Endpoint topic/{topicName}/groups incorrect acl resource type [0.25.0]

### ISSUE THREAD

**Issue by doxsch** [tchiotludo/akhq#1789]
In the `TopicController`, it appears that the wrong resource is being checked for the endpoint `api/{cluster}/topic/{topicName}/groups` (see [here](https://github.com/tchiotludo/akhq/blob/dev/src/main/java/org/akhq/controllers/TopicController.java#L275)). Instead of using `Role.Resource.TOPIC`, it might be more appropriate to use `Role.Resource.CONSUMER_GROUP`, as the same data can be read in the `GroupController` with the `CONSUMER_GROUP` resource (see [here](https://github.com/tchiotludo/akhq/blob/dev/src/main/java/org/akhq/controllers/GroupController.java#L37)).

**Comment by tchiotludo** [comment]
@doxsch PR are welcome :)
