### ISSUE TITLE
Regression for handling offset update error

### ISSUE THREAD

**Issue by shaneikennedy** [tchiotludo/akhq#1807]
When I try to update an offset for a consumer group (and it fails, as expected) nothing happens but there's an error log in the console. In version 0.24 there used to be an error banner explaining the error

**Comment by AlexisSouquiere** [comment]
Can you explain how you produce this kind of error when updating the offsets ?

**Comment by shaneikennedy** [comment]
For sure

1. Create a topic
2. Create a consumer group for the topic
3. Create a consumer in the consumer group from point 2
4. Produce some data to the topic from point 1
5. Make sure the consumer from point 3 has consumed the data and commited the offsets
6. Try to reset the offset for this consumer group

This should fail because you can't update the offsets of a consumer group while there are consumers connected


But for dev purposes I think you could just find where the request is being made in api.jsx and throw an exception such that the Promise is rejected (in the image you can see that api.jsx:88 is where it happens https://github.com/tchiotludo/akhq/blob/40b4bedb6c047e11205a790a35306211bf78e337/client/src/utils/api.jsx#L88)

**Comment by shaneikennedy** [comment]
Sorry had to remove the image from the issue, i don't think there was anything sensitive but it did have some klarna specifc things in it. Here's a trimmed down image 
<img width="511" alt="image" src="https://github.com/tchiotludo/akhq/assets/24571820/479351ec-6ce9-49c6-a2e5-2610b65b216b">
