### ISSUE TITLE
contains a not contains

### ISSUE THREAD

**Issue by Lubrmanus** [tchiotludo/akhq#1836]
When searching, even though I specify "value not contains," the results still include items where the value contains the specified term.

**Comment by akshay232** [comment]
Can you give one example of the keyword you are searching with?

**Comment by jonasvoelcker** [comment]
Hi @Lubrmanus,

I've just tested this on my machine and it seems to work. Do you maybe have a search in progress and start a new one? What about hitting the Stop-Button before searching with "Not Contains"?

**Comment by Lubrmanus** [comment]
It's strange, now it works without any problems, but sometimes nothing happens. Unfortunately, I can't press anything there, and the search doesn't work either, but sometimes it works without any problems. Maybe there's some peculiarity I don't understand.
it's OK
![image](https://github.com/tchiotludo/akhq/assets/149938835/290ed3d3-f1fc-4c5c-ac23-a79ea48a1c85)
And now it doesn't work.
![image](https://github.com/tchiotludo/akhq/assets/149938835/305dcbd0-50c9-4eff-8ffe-67c5f5a5aa60)

**Comment by jonasvoelcker** [comment]
It seems like you are not using our latest version, could you please try to install the 0.25.0 and delete all your related browser caches as well as opening the browser from scratch? There is a service worker, which tries to keep the Frontend in place if no new browser window is used.

You can see that you are running the new frontend when the input fields turn grey ;)

**Comment by Lubrmanus** [comment]
I upgraded to the new version and the problem is solved. Everything is working on the initial tests.
