### ISSUE TITLE
UI Feature: Scrolling list of Kafka Connectors

### ISSUE THREAD

**Issue by aonamrata** [tchiotludo/akhq#1845]
Hi, When you have too many connectors in AKHQ it does not show a scroll down like it used to do with previous version.
Collapse view:
![image](https://github.com/tchiotludo/akhq/assets/1792005/4c855052-e34f-46e2-b954-fcadfdcd2e1d)

Expanded view:
![image](https://github.com/tchiotludo/akhq/assets/1792005/fa64276e-e2d3-4fc6-b0a5-03a20e4a4ae9)

We recently updated to AKHK version 0.25.0 and I am on Chrome Version 126.0.6478.63 (Official Build) (64-bit) browser

**Comment by AlexisSouquiere** [comment]
PR #1841 is already opened to fix this issue
