### ISSUE TITLE
Copy a message is really slow to init

### ISSUE THREAD

**Issue by ClearClean** [tchiotludo/akhq#1856]
When I try to copy a message from the topic messages view, the new page takes a long long time to load.

![image](https://github.com/tchiotludo/akhq/assets/113035987/b86bdca1-e935-4292-ae0d-84148cab56c8)

When loading, the "Value Schema" field can not be set since the list is empty, and the http call is still pending.

In the akhq logs, I can see a lot of warn about all my Schemas. It seems like AKHQ is scanning the whole schema registry in order to retrieve the data.

I have over 5000 schemas in the registry, maybe this is too much ?

Same behavior when I try to produce a new message instead of a copy.

**Comment by AlexisSouquiere** [comment]
I think you are still using 0.24.0 or lower version.
There were improvements since 0.25.0 to handle large registries. I have quite the same number of schemas on my side and it's working fine. I suggest you to update to the latest version
