### ISSUE TITLE
Failing to display consumer groups if uiPageSize is larger than 94

### ISSUE THREAD

**Issue by ollewobbla** [tchiotludo/akhq#1919]
If uiPageSize>94, the consumer groups information never loads in the topics list.

The browser console logs shows:

TopicList.jsx:296 Uncaught (in promise) TypeError: f.data.filter is not a function
    at TopicList.jsx:296:30
    at Array.forEach (<anonymous>)
    at TopicList.jsx:293:18

Tried v0.24.0 & v0.25.1, same results.

**Comment by AlexisSouquiere** [comment]
Trying to understand the issue, you mean that if you are trying to load more than 94 topics per page in the topics list, the consumer groups column won't load anything. Am I right ?

**Comment by Kris686** [comment]
Hi, @AlexisSouquiere I've encountered the same issue. Yes, if I'm trying to load 100 and above topics per page, the consumer groups column won't load anything.
![image](https://github.com/user-attachments/assets/778743ec-2676-4852-8eeb-6215aa54b74d)
![image](https://github.com/user-attachments/assets/abf7f29c-5fff-4c20-b88b-8d51e03ef994)

If I will increase to 150/200 I'm getting internal server error + more exceptions:
![image](https://github.com/user-attachments/assets/edced180-15b0-433c-9a10-11c3f51cd710)
![image](https://github.com/user-attachments/assets/53bf8423-69f4-4f6c-be99-8bc0d25d074e)

@ollewobbla were you able to resolve this issue?

**Comment by AlexisSouquiere** [comment]
The PR #1889 will fix it. I just need to fix the conflicts (I forgot) and then it can be merged. Will do that ASAP

**Comment by Kris686** [comment]
@AlexisSouquiere Thank you for help!!!!
