### ISSUE TITLE
Can't display topic info with black screen

### ISSUE THREAD

**Issue by vasili439** [tchiotludo/akhq#1947]
When I try to filter one of our topics in common topics list with Search field I'm get black screen with console error "Uncaught RangeError: Invalid time value" (see attached screen). I think error could be connected with consumer groups as black screen appear when topic info is already displayed but akhq tries to fetch consumer groups status:
![image](https://github.com/user-attachments/assets/4a587a1f-4b44-467c-99b4-c88716972ba2)

BTW: the same for chrome/firefox browsers

**Comment by AlexisSouquiere** [comment]
Can you try to disable the consumer groups info in the topics list by enabling "Skip Consumer Groups" in the Settings page ?  Eventually do the same with "Skip Last Record Date". It will tell if the error really comes from the consumer groups info request, the last record request, etc. For me there is a notion of time only in the last record request

Then we will have to investigate in the request causing the error and search for a time in the response to check the format

**Comment by vasili439** [comment]
Sorry. Our developers refactored approach for data processing and now affected topic is not relevant anymore and it was deleted. So I can't reproduce the issue for now. Will reopen it if mentioned error rise once again.
