### ISSUE TITLE
Last record behavior is erratic

### ISSUE THREAD

**Issue by thnk2wn** [tchiotludo/akhq#1986]
Version `0.24.0`.

Note here as I refresh this topic the last record keeps toggling from 3 days ago (old value) and 1 hour (current value).

![2024-10-29_15-15-18](https://github.com/user-attachments/assets/97f220d2-8633-4b8c-897f-1d25e50e14c7)

Same thing happens when we call via API.

https://{base-address}/api/{cluster}/topic/last-record?topics={topic}

**Comment by tchiotludo** [comment]
you can update to latest version please? so many change since this 0.24.0

**Comment by tchiotludo** [comment]
ok cool, let's close and reopen if it reappear please

**Comment by thnk2wn** [comment]
@tchiotludo Still happening after 0.25.1

https://github.com/user-attachments/assets/0b3ede7e-ab4e-4f4f-b19b-fc559c4b9d41
