### ISSUE TITLE
Q: tweaking thread pools needed ?

### ISSUE THREAD

**Issue by jorgheymans** [tchiotludo/akhq#200]
Hi,

We are seeing intermittent "hangs" of kafkahq, where clicking on anything in the left menu (Topics, ACL, ...) does not do anything. Or after entering login credentials we never get to the main page. The browser loading indicator appears but the new page is never actually returned. This happens both on FF and Chrome. Developer Tools shows that some resources (css or images) are being requested but kafkahq sends no response. Sometimes a refresh fixes it, sometimes not. So i was wondering if the request thread pools for a standard kafkahq instance are adequately sized ? Are there any micronaut parameters we need to set for this?

**Comment by jorgheymans** [comment]
Attached a screenshot that may be relevant, in this case the ACL item was clicked but it took a very long time for the result to be displayed. We observed that `main.js` and `icon.png` took a very long time to load.

![image](https://user-images.githubusercontent.com/193792/73272346-8354ab80-41e2-11ea-9ef2-0af12bc6f496.png)

**Comment by tchiotludo** [comment]
Interesting, did you reach directly KafkaHQ or have a reverse proxy in front ?

**Comment by jorgheymans** [comment]
Direct connection.

Op di 28 jan. 2020 16:55 schreef Ludovic DEHON <notifications@github.com>:

**Comment by jorgheymans** [comment]
Noticing that when the problem occurs, a restart of kafkahq makes it work again for a while. Maybe it's a request handler pool of some sort that gets blocked.

**Comment by tchiotludo** [comment]
On `/prometheus` endpoint, you can see the thread poll handle by micronaut .
After the bug / lag, can you send me the value output by this endpoint please ?

**Comment by jorgheymans** [comment]
Can you tell me to the exact name of the metric ? Is it executor.pool.size ?

**Comment by tchiotludo** [comment]
on the `/prometheus`, every entry starting with `executor_` can help to understand.

**Comment by jorgheymans** [comment]
Interesting tidbit perhaps, I have set the `micronaut.server.host` property and the server has been running stable since ... Will keep observing it.

**Comment by jorgheymans** [comment]
@tchiotludo hang is occuring again, here are the `executor` metrics

```
  1 # HELP executor_pool_size_threads The current number of threads in the pool
  2 # TYPE executor_pool_size_threads gauge
  3 executor_pool_size_threads{name="io",} 1.0
  4 executor_pool_size_threads{name="scheduled",} 8.0
  5 # HELP executor_active_threads The approximate number of threads that are actively executing tasks
  6 # TYPE executor_active_threads gauge
  7 executor_active_threads{name="io",} 1.0
  8 executor_active_threads{name="scheduled",} 0.0
  9 # HELP executor_seconds
 10 # TYPE executor_seconds summary
 11 executor_seconds_count{name="io",} 157.0
 12 executor_seconds_sum{name="io",} 5.6804066
 13 executor_seconds_count{name="scheduled",} 622.0
 14 executor_seconds_sum{name="scheduled",} 0.288138697
 15 # HELP executor_seconds_max
 16 # TYPE executor_seconds_max gauge
 17 executor_seconds_max{name="io",} 0.164876433
 18 executor_seconds_max{name="scheduled",} 6.44455E-4
 19 # HELP executor_queue_remaining_tasks The number of additional elements that this queue can ideally accept without blocking
 20 # TYPE executor_queue_remaining_tasks gauge
 21 executor_queue_remaining_tasks{name="io",} 0.0
 22 executor_queue_remaining_tasks{name="scheduled",} 2.147483647E9
 23 # HELP executor_queued_tasks The approximate number of tasks that are queued for execution
 24 # TYPE executor_queued_tasks gauge
 25 executor_queued_tasks{name="io",} 0.0
 26 executor_queued_tasks{name="scheduled",} 2.0
 27 # HELP executor_completed_tasks_total The approximate total number of tasks that have completed execution
 28 # TYPE executor_completed_tasks_total counter
 29 executor_completed_tasks_total{name="io",} 157.0
 30 executor_completed_tasks_total{name="scheduled",} 622.0
```

**Comment by tchiotludo** [comment]
Really weird, didn't see any issue. 
I have compared with my metrics nothing seems to be different.

Tunning can be done here : https://docs.micronaut.io/latest/guide/index.html#threadPools

the only one that seems to have impact is `micronaut.executors.io`.
But I think it's a simple `Executors.newCachedThreadPool()` without any max value. 

You can't try but I'm really doubtful ...

**Comment by tchiotludo** [comment]
closing in favor of #209 that must be the main reason I think. 

Feel free to reopen if needed !
