### ISSUE TITLE
OutOfMemory issue

### ISSUE THREAD

**Issue by jorgheymans** [tchiotludo/akhq#209]
Our kafkahq instance went OOM, after running stable for about 5-6 days. It runs on jdk8, with 1G heap. Is 1G typically enough for an instance with about 20-30 ppl maybe using it ?

I have the memory dump available if you want, let me know where to share it.  

![image](https://user-images.githubusercontent.com/193792/73730980-fa84c500-4737-11ea-8e7c-a2f70f9e7a7a.png)

**Comment by jorgheymans** [comment]
It seems a micrometer issue https://github.com/micrometer-metrics/micrometer/issues/1743 . 

![image](https://user-images.githubusercontent.com/193792/73733024-7e8c7c00-473b-11ea-880e-4d189ccf6670.png)

**Comment by HungUnicorn** [comment]
can you please share the http response status statistics, i.e., counts of endpoint and response status ? should be available in prometheus metric `http_server_requests_seconds_count` and is visualized in grafana as time series

**Comment by tchiotludo** [comment]
@jorgheymans thanks for the report and the research. 

Quickly look, I need to update micronaut 1.3 RC and also force micrometer to v1.3.3 since this is the only release containing the fix. 

I just push a new version on `dev` image, can you try please ?

**Comment by jorgheymans** [comment]
@tchiotludo we tried this out, upon first access of kafkahq instance nothing happens. It seems to hang indefinitely, nothing in the logs either.

**Comment by jorgheymans** [comment]
this seems to be the error

```
Message: Multiple possible bean candidates found: [io.micronaut.views.soy.SoySauceViewsRenderer, io.micronaut.views.freemarker.FreemarkerViewsRenderer, io.micronaut.views.soy.SoyTofuViewsRenderer]
Path Taken: new ErrorController([ViewsRenderer viewsRenderer],RequestHelper requestHelper)]:  java.lang.Throwable -> ErrorController#HttpResponse error(HttpRequest request,Throwable e)
2020-02-06 09:41:15,955 DEBUG pGroup-1-2 i.m.c.DefaultBeanContext   Finding candidate beans for type: interface io.micronaut.views.ViewsRenderer
2020-02-06 09:41:15,955 DEBUG pGroup-1-2 i.m.c.DefaultBeanContext   Resolved bean candidates [Definition: io.micronaut.views.soy.SoySauceViewsRenderer, Definition: io.micronaut.views.freemarker.FreemarkerViewsRenderer, Definition: io.micronaut.views.soy.SoyTofuViewsRenderer] for type: interface io.micronaut.views.ViewsRenderer
2020-02-06 09:41:15,955 DEBUG pGroup-1-2 i.m.c.DefaultBeanContext   Finalized bean definitions candidates: [Definition: io.micronaut.views.soy.SoySauceViewsRenderer, Definition: io.micronaut.views.freemarker.FreemarkerViewsRenderer, Definition: io.micronaut.views.soy.SoyTofuViewsRenderer]
2020-02-06 09:41:15,955 DEBUG pGroup-1-2 i.m.c.DefaultBeanContext   Searching for @Primary for type [io.micronaut.views.ViewsRenderer] from candidates: [Definition: io.micronaut.views.soy.SoySauceViewsRenderer, Definition: io.micronaut.views.freemarker.FreemarkerViewsRenderer, Definition: io.micronaut.views.soy.SoyTofuViewsRenderer] 
2020-02-06 09:41:15,955 DEBUG pGroup-1-2 .s.n.RoutingInBoundHandler Found matching exception handler for exception [Failed to inject value for parameter [viewsRenderer] of class: org.kafkahq.controllers.ErrorController
```

**Comment by tchiotludo** [comment]
there is a workaround on #212, I will look at this asap

**Comment by tchiotludo** [comment]
Fix on the last `dev` version

**Comment by jorgheymans** [comment]
In the end i did below fix to stabilize the memory consumption. I'm pretty sure that #200 is related to this, because each time the hanging was starting to happen more frequently we noticed that the Xmx boundary had been nearly reached. Why the application never OOM's though i don't know. 

```
micronaut:
  metrics:
    enabled: false
```

Maybe for kafkahq a strategy where it prunes or disables those micronaut features that are not used makes more sense.

**Comment by jorgheymans** [comment]
After having fixed the micrometer issue by disabling the metrics, we still noticed that most remainder heap memory was taken up by FlightRecorderMXBeanImpl (probably due to https://bugs.openjdk.java.net/browse/JDK-8207829)

![image](https://user-images.githubusercontent.com/193792/74813634-ec1cd880-52f5-11ea-91a5-5a6a7f41f559.png)

Upgrading to jdk13 fixed also this.

**Comment by tchiotludo** [comment]
Really strange bug and thanks for digging it ! 

Maybe I will move to jdk13 on the docker image and keep java11 compatibility for local installation. 
Will think about it

**Comment by jorgheymans** [comment]
Just leaving final note, even though the memory leak is not there anymore it is worrying that JMX metrics takes up so much heap for a kafka client. There is an issue for this on the kafka side https://issues.apache.org/jira/browse/KAFKA-3980 . For me this issue can be closed, but i would suggest to disable micronaut metrics by default.

**Comment by tchiotludo** [comment]
Hi @jorgheymans 
I decided to just remove Kafka Metrics from Akhq, this one are deprecated in last micrometer version and also I don't really think this metrics have any sense for akhq.
I will realease quickly a new version but the change are available on dev in a mean time. 

Thanks for your investigation on this issue :+1:

**Comment by jorgheymans** [comment]
Removing the kafka metrics makes sense, as we were still seeing like 80% of heap taken up by this. We'll test out the dev version soon, thanks !
