### ISSUE TITLE
please publish helm chart to https://hub.helm.sh

### ISSUE THREAD

**Issue by kostyrev** [tchiotludo/akhq#211]
it's very inconvenient to install chart with git cloning this repository

**Comment by tchiotludo** [comment]
it was on backlog but I don't know the process for this, any clue ?

**Comment by kostyrev** [comment]
there are multiple choices. Maybe the easiest one is [Github Pages](https://helm.sh/docs/topics/chart_repository/#github-pages-example)

**Comment by tchiotludo** [comment]
don't see the repo add ! 
Will be simplier (since I can update the charts as I want) and I will go for it in a few day

**Comment by tchiotludo** [comment]
Hello, 
I think the repo can be publish to helm hub. 

Can you try with the repository : https://akhq.io/ and tell me if it's ok for you ?

**Comment by kostyrev** [comment]
ca marche, merci!
