### ISSUE TITLE
ACL to allow filtering by consumer groups 

### ISSUE THREAD

**Issue by apellegr06** [tchiotludo/akhq#241]
Hello,

I think that the reset consumer offset functionnality should be a great new feature in a futur release :)

Regards

**Comment by tchiotludo** [comment]
There is already a functionnality reset offset : https://github.com/tchiotludo/kafkahq/releases/tag/0.2.0

**Comment by apellegr06** [comment]
Oups ! It' s right :)

And is it possible to have a functionality to filter consumer group (as for the topic) in order to give access to devlopment team to reset their own offsets (and not these one of other application :)) ?

Thanks
Alain

**Comment by tchiotludo** [comment]
It's possible easily, mostly the same than this one : https://github.com/tchiotludo/kafkahq/pull/126 for consumer group. 

PR are welcome :+1:

**Comment by apellegr06** [comment]
I'm sorry, I'm not a developper :(

**Comment by tchiotludo** [comment]
done in #1472
