### ISSUE TITLE
Allow for setting additional fields when creating a connector

### ISSUE THREAD

**Issue by marghidanu** [tchiotludo/akhq#251]
I'm trying to create a connector using the interface but I can't find all the fields available. For example the `value.converter.schemas.enable` is not available for the ElasticSearch sink type. Maybe the interface should allow adding arbitrary values.

**Comment by tchiotludo** [comment]
Good catch, don't really think about it before but was true some connectors don't expose configuration. 
PR are welcome on this :+1:
