### ISSUE TITLE
Sort by Newest ignored when including a search term

### ISSUE THREAD

**Issue by nilbus** [tchiotludo/akhq#259]
In KafkaHQ 0.11.0 in the Topic > Data view, Sort by Newest works great until I enter a Search term. With both Sort and Search specified, data is listed with Oldest first, even though it reports to being sorted by Newest.

I'd prefer to have this functionality work, but if it can't be made to work, the Sort header should revert to showing `Sort: (Oldest)` when using a search term. Otherwise, the header is misleading.

Use case: We sometimes have topics that have multiple messages of different schemas. One message is less frequent than the other, requiring us to search / filter to find messages of that schema. However, when searching, sort by newest doesn't work.

A workaround I have is to filter to a recent Timestamp nearer to the newest rather than sorting.

**Comment by tchiotludo** [comment]
Hello,

Thanks for the report, but it's only a ui issue.
Search and sort by newest is incompatible, Kafka don't allow by default to sort by newest and it's a hack done by akhq, I will remove the option on sort page for search since it's not possible 😀

**Comment by nilbus** [comment]
Assuming you mean that you’ll disable sort in the UI when searching, that’s
perfect. Thanks!
