### ISSUE TITLE
Viewing Connector Details throws 500

### ISSUE THREAD

**Issue by tjharke13** [tchiotludo/akhq#285]
When viewing a connector details a 500 error is thrown.  Looking through source code and looking at kafka connect logs, the issue stems from the getPlugin calling getPlugins and trying to validate all plugins.  Even plugins that are deployed, but not in use.  This causes a 500 error on kafka connect side for a NPE when trying to validate a plugin that isn't deployed for a connector.

Because this should be doing a singular getPlugin, there are unneeded calls being done out to kafka connect to validate the plugins.  

![image](https://user-images.githubusercontent.com/3589858/80864790-81b7db00-8c4a-11ea-8c8d-3ec31038d411.png)

**Comment by tchiotludo** [comment]
closed in #287
