### ISSUE TITLE
Hide secrets from kafka-connect connectors

### ISSUE THREAD

**Issue by ebrard** [tchiotludo/akhq#291]
Kafka-Connect connectors may contain credentials such as Debezium `database.password` and `database.user`. I would suggest to replace the value for keys that contain `user|password|jaas` I think this could be done at [this level](https://github.com/tchiotludo/akhq/blob/511f3bd00237238420a48b07054bfc521a7a9b18/src/main/java/org/akhq/models/ConnectDefinition.java#L76). Let me know what you think and feel free to "assign to me" ;)

**Comment by tchiotludo** [comment]
Nice suggestion but it will break the update on the connector config, no ? 
We will remove the user / password and user will send an update without that user. 

I'm wrong ?

**Comment by ebrard** [comment]
The idea was just to replace the values not to remove the keys. But nevertheless you made a point. I am not to confident having all my databases and kafka secrets exposed even tho only our engineers have access internally. Maybe a tradeoff would be to hide credentials with the read right but display then if the update right is set?

**Comment by ebrard** [comment]
I had another quick look at in the configuration section (update), some key are not visible anyway like `database.history.producer.sasl.jaas.config`. I guess the api client library that you use is not aware of it maybe?

**Comment by tchiotludo** [comment]
no really sure how to handle it special case for now.
I think the library is not doing anything and it must be directly kafka connect that must hide on the rest api. 
Not really sure of that. 

Maybe a quick look on why sasl.jaas is hidden (by connect or debezium).
Maybe it's a bug on upstream connector that must hide also this one ?

**Comment by ebrard** [comment]
`database.history.producer.sasl.jaas.config` is not hidden/missing when I hit the kafka-connect API directly. I will have a look at it all and see what I can do.

**Comment by tchiotludo** [comment]
Maybe a better solution will be to have more granularity on ACLS ?
And have a special role to see / update configs ?

**Comment by ebrard** [comment]
So for example there will be some permission to just see the status without the configuration? in the main view of the connectors.

**Comment by tchiotludo** [comment]
yes for now we have this : 
```
          - connect/read
          - connect/insert
          - connect/update
          - connect/delete
          - connect/state/update
```

tomorrow we can have for example : 
```yaml
          - connect/read
          - connect/insert
          - connect/update
          - connect/delete
          - connect/config/read
          - connect/config/update
          - connect/state/update
```

**Comment by ebrard** [comment]
Yeah that would make perfect sense, I've seen that you have refactored the UI part in a branch, should I wait for that to be merged?

**Comment by tchiotludo** [comment]
Yeah clearly, the refactor of the ui is the next big milestone and will remove the old ui soon.
If you plan to make a PR, maybe it's better to start from the refactor branch or to wait, like you want 👍

**Comment by pimpelsang** [comment]
We've used this approach to not have secrets in configuration at all.

https://debezium.io/blog/2019/12/13/externalized-secrets/

**Comment by ebrard** [comment]
I'll need to have a deeper look since I would also like to hide the Kafka credentials contained in `database.history.consumer.sasl.jaas.config`.

**Comment by raphaelauv** [comment]
Akhq is showing the configuration, I think it's the responsibility of the dev to implement externalize secrets in kafka-connect

https://cwiki.apache.org/confluence/display/KAFKA/KIP-297%3A+Externalizing+Secrets+for+Connect+Configurations
https://docs.confluent.io/platform/current/connect/security.html#externalizing-secrets
