### ISSUE TITLE
Increase # of partitions / replication factor for a topic

### ISSUE THREAD

**Issue by ericychoi** [tchiotludo/akhq#294]
Our kafka use case is relatively simple, but one of more frequent "maintenance" we do is increase # of partitions for a given topic, and create new topics.

Playing around with this tool, I know I can create a new topic quite easily.  But I couldn't find a way to alter number of partitions for a given topic.  Is this something that can be done by akhq?

**Comment by tchiotludo** [comment]
You are true, there is no way for now to increase the number of partition.
And I'm also surprised that you are the first to request it 😆
PR are welcome is this, it's seems to be simple 👍

**Comment by shivasheeshyadav** [comment]
Hi @tchiotludo @ericychoi 
I would like to work on it. Please assign it to me.

**Comment by tchiotludo** [comment]
@shivasheeshyadav, glad to know it :+1: 
Maybe just take care of a big change here : https://github.com/tchiotludo/akhq/pull/288 
That will come really soon. 

So my advice, Just start for now on api side only and don't add any front end to avoid loss of work !

**Comment by shivasheeshyadav** [comment]
@tchiotludo sure. will start work on the backend then.

**Comment by ebrard** [comment]
also interested in that feature +1

**Comment by shivasheeshyadav** [comment]
Hi @tchiotludo 
I'm facing some issues in setting up dev environment.
I ran `docker-compose -f docker-compose-dev.yml up`

`ERROR: for akhq_zookeeper_1  Cannot start service zookeeper: Ports are not available: listen tcp 127.11.8.17:2181: bind: can't assign requested address`

**Comment by shivasheeshyadav** [comment]
Hi @tchiotludo 
Could you please help me with development environment setup.
I couldn't get it right. I ran the following:
`docker-compose -f docker-compose-dev.yml up`

Even though it starts the server, I couldn't access http://localhost:8080/

**Comment by tchiotludo** [comment]
Can you try on http://127.11.8.17:8080 ? 

If it's don't work , maybe you should remove this from `docker-compose-dev.yml` file : 
`127.11.8.17:` and try http://localhost:8080/ ?

This mostly only work in linux, it must be the main reason.

**Comment by shivasheeshyadav** [comment]
@tchiotludo Tried both ways. I'm getting the following error :
`{"message":"Internal Server Error: Couldn't find any clusters on your configuration file, please ensure that the configuration file is loaded correctly"}`

I'm running on Ubuntu.

**Comment by tchiotludo** [comment]
Ok you are better now. 
You just need know to provide a configuration files to connect to your cluster. 

in `src/main/resources/application-dev.yml`, paste that : 

```yaml
akhq:
  connections:
    plaintext:
      properties:
        bootstrap.servers: "kafka:9092"
```

Sorry, onboarding for new developer is not really easy.

**Comment by shivasheeshyadav** [comment]
Hi @tchiotludo 
Thanks for the help. It did work, but with a broken UI.
However, I've made the first commit towards this issue and raised a PR #302

Please review.

**Comment by MilkyWay-core** [comment]
We too wait the function. Do you can reopen the feature request ? @tchiotludo

**Comment by dberardo-com** [comment]
any idea why this isnt supported yet ??

**Comment by ebrard** [comment]
increasing the number of partition is already supported.
