### ISSUE TITLE
/ redirects with HTTP 301

### ISSUE THREAD

**Issue by ruurtjan** [tchiotludo/akhq#297]
The root endpoint '/' now forwards with HTTP 301: permanently moved. This is cached by browsers, so if a user changes the configuration and renames a Kafka cluster, it forwards to an incorrect url. It's also inconvenient if you run akhq locally, where you might reuse the port later for a different web server.

Changing the redirect to a HTTP 302 should fix this issue.

**Comment by tchiotludo** [comment]
Hi @ruurtjan, 

You must use an old version, this PR fix it : https://github.com/tchiotludo/akhq/pull/274
and was release on last version

**Comment by ruurtjan** [comment]
Ah, Sweet! Yeah, I must be on an old container then.
