### ISSUE TITLE
Extend Date with seconds/ms

### ISSUE THREAD

**Issue by krasaev** [tchiotludo/akhq#299]
Hi there. First of all, thank you for this amazing tool).

I would like to ask you is it possible to show in the Date column in the topic/tail view seconds and milliseconds? Sometimes it's really matter exact time of a message arriving, especially when you try get the exact order of messages that were sent during some action.

If this possibility exists, please tell me how turn it on, cause I have failed to find out how to do it. 

TIA

**Comment by tchiotludo** [comment]
Hi @krasaev, 

really easy, available in 5 min on `dev` image :smile:
