### ISSUE TITLE
The ingress.yaml file of the AKHQ official Helm Chart still has the old Kubernetes apiVersion?

### ISSUE THREAD

**Issue by Cybertanuki** [tchiotludo/akhq#305]
Hello dear AKHQ team! 
Is there a newer HelmChart where the Ingress apiVersion is set to `networking.k8s.io/v1beta1` instead of `extensions/v1beta1`?
I saw this commit that should fix the problem: https://github.com/tchiotludo/akhq/pull/98/commits/cd9acef8cb6a1d31556c906b3f294ea924c1551f but in the downloadable HelmChart it looks that the Ingress apiVersion is still old, whereas the Deployment version is up-to-date. 
I downloaded it this way: `helm pull akhq/akhq --untar` using helm 3.2.1 and then I looked inside the `ingress.yaml` and found `apiVersion: extensions/v1beta1` hardcoded.
Probably is there a reason for that? 
https://github.com/tchiotludo/akhq/blob/dev/helm/akhq/templates/ingress.yaml
Since I am a newbie developer, I apologize in advance if I did or said something wrong.
Any help would be appreciated, thanks.

**Comment by tchiotludo** [comment]
Really don't understand here where it disappeared ... :thinking: 

I've fix it and create a new helm charts version 

Thanks for the report :+1:

**Comment by Cybertanuki** [comment]
Merci beaucoup!
