### ISSUE TITLE
Could I add new feature to this tool?

### ISSUE THREAD

**Issue by quanghn96** [tchiotludo/akhq#310]
Hello everyone!

I want to custom this tool to add new feature. How can I do it? Thanks!

**Comment by tchiotludo** [comment]
Hi, 

You just need to fork it, add some, maybe with [dev server](https://github.com/tchiotludo/akhq#development-server) and send a PR in order to add the feature the official akhq :+1:

**Comment by tchiotludo** [comment]
closing since no response
