### ISSUE TITLE
Set timezone (now UTC set from jvm.options)

### ISSUE THREAD

**Issue by Pixelshifter** [tchiotludo/akhq#314]
I would like to set my own timezone. I'm running AKHQ inside a Docker-container, in which I've volume mounted the /etc/timezone file from the host. This has a different timezone set than the default (UTC), but didn't work. Some more digging lead me to https://github.com/tchiotludo/akhq/blob/dev/docker/app/jvm.options where the timezone is set within the JVM.

Without wanting to fork this project and the need to manage my internal CI/CD pipeline for this awesome tool, I was wondering if there is  a way to override this timezone setting, or that we could implement an option in the application.yml to set our own timezone. Perhaps people here have found a different solution?

**Comment by tchiotludo** [comment]
Hi, 

When you are talking about timezone, want date to you want to have on your timezone ? 
Date display on the web ui ? Logs ? both ? others ? 

Thanks

**Comment by Pixelshifter** [comment]
Thanks for the really fast reply! I see that the timestamp for messages in a given topic in the UI are 2 hours in the past which also applies to timestamps in the access_log.

**Comment by tchiotludo** [comment]
will be in the `dev` in 5 minutes, help [here](https://github.com/tchiotludo/akhq#pass-custom-java-opts)

**Comment by Pixelshifter** [comment]
Superb!!!

**Comment by Pixelshifter** [comment]
Unfortunately this doesn't work :( Only solution thus far is to copy the existing jvm.options and set the timezone there and use that file, which gets injected as env-var (as per the README).

**Comment by tchiotludo** [comment]
Really sure ? 
I've tried on my local computer and it's works !

**Comment by Pixelshifter** [comment]
This is my docker run command:

`/usr/bin/docker run -v /etc/localtime:/etc/localtime:ro \
          -v /opt/akhq/akhq_config.yml:/app/application.yml:ro \
          -e 'JAVA_OPTS=-Duser.timezone=Europe/Amsterdam' \
          --name=akhq \
          -p 127.0.0.1:8081:8080 private_docker_reg_url/tchiotludo/akhq:dev`

Which results in this being logged (see the timestamp of journalctl (host system) vs the timestamp IN the logmessage:

`Jun 19 09:07:50 localhost.localdomain docker[40419]: 2020-06-19 07:07:50,075 INFO  main       i.m.runtime.Micronaut      Startup completed in 11559ms. Server Running: http://ec163e4fa706:8080`


What DID work though was to override the whole JVM_OPTS file with my own custom jvm.options file and set the timezone there (as per your README instructions).

**Comment by arunvelsriram** [comment]
Slightly related question. Is it possible use browser timezone in the UI, irrespective of the timezone used in the server?

**Comment by tchiotludo** [comment]
When the ui was rework in React, this part was forgotten, I reopen, 
Thanks for the report

**Comment by jinooslee** [comment]
Waiting for the UI changes. :)

**Comment by Chaosmonkeys** [comment]
Any updates?
