### ISSUE TITLE
how to read values from a secret from akhq helm template?

### ISSUE THREAD

**Issue by jipipayo** [tchiotludo/akhq#322]
I am trying to setup akhq with ssl brokers not using hardcoded passwords with the helm templates.

currently I am using a values file with a secret with the whole configuration, it works, but it has the password hardcoded into the values.yaml
ssl.truststore.password = "foo"

How can i read my password from a secret? helm doesnt allow to do that from a values.yaml

**Comment by tchiotludo** [comment]
For the secret, the helm charts allow to pass some : 
https://github.com/tchiotludo/akhq/blob/dev/helm/akhq/values.yaml#L29

This configuration will be stored as secrets. 
This don't work for you ?

**Comment by tchiotludo** [comment]
closing since no response
