### ISSUE TITLE
Deafult replication factor is displayed in "Factor" and "In Sync" columns

### ISSUE THREAD

**Issue by paul-lysak** [tchiotludo/akhq#326]
No matter what is the actual replication factor and number of in-sync replicas, AKHQ v. 0.14.1 shows the number from 
`default.replication.factor` in "Replications / Factor" and "Replications / In Sync" columns in "Topics" table.

**Comment by tchiotludo** [comment]
I think this is resolved here : https://github.com/tchiotludo/akhq/pull/301 so on last version !

**Comment by paul-lysak** [comment]
Yes, it worked with version `0.15.0`. Thanks.
