### ISSUE TITLE
Add share button

### ISSUE THREAD

**Issue by tchiotludo** [tchiotludo/akhq#332]
A share button for every message and add a route to show only this message

**Comment by polarising-java** [comment]
@tchiotludo  create a new API for this?

   @Secured(Role.ROLE_TOPIC_DATA_READ)
    @Get("api/{cluster}/topic/{topicName}/data/record")
    @Operation(tags = {"topic data"}, summary = "Ge a single record")
    public Record record(
        HttpRequest<?> request,
        String cluster,
        String topicName,
        Optional<Integer> partition,
        Optional<Integer> offset
    )

**Comment by tchiotludo** [comment]
in think this is the better way, yeah :) 
Since we need to be sure that only that exactly offset is fetch, I think we need a new route for that :+1:

**Comment by tchiotludo** [comment]
done in #401
