### ISSUE TITLE
Filter topics in consumer group when update offsets

### ISSUE THREAD

**Issue by bochkarevnv** [tchiotludo/akhq#339]
Hi, we have consumer groups with many topics attached and if we use update offsets, this function change offset on all topic in consumer group. If we want to update only one topic, we have to select the desired change (for example, timestamp), copy the offset across all partitions of the desired topic, then go back and insert them manually. If it possible to add selection of topics for update offsets function?

**Comment by tchiotludo** [comment]
Seems to be easy, just need to add a checkbox for each topic in order to choose the wanted one, PR are welcome 😀
