### ISSUE TITLE
Config log directory ?

### ISSUE THREAD

**Issue by holiday-sunrise** [tchiotludo/akhq#341]
Hi togehter,

where can we configure the log directory.  We Run it as Standalone/Linux Server

Kind regards

rainer

**Comment by tchiotludo** [comment]
Hi, 

You need to provide a custom [logback configuration files](http://logback.qos.ch/manual/configuration.html) : 

and launch akhq with `java -Dlogback.configurationFile=/path/to/config.xml -jar akhq.jar`

**Comment by holiday-sunrise** [comment]
Thx for your Help

**Comment by tchiotludo** [comment]
No problems 👍
