### ISSUE TITLE
Mistake printing Replication Factor /<CLUSTER_NAME>/topic

### ISSUE THREAD

**Issue by mcortinas** [tchiotludo/akhq#345]
Hi,

  Let me share an screenshoot of my installation due to I detect an error printing replication factor in one of my topic. 
  I installed akhq using helm chart the docker image used is 0.14.1

 My topic has replication factor 3 and the URL "/<CLUSTER_NAME>/topic" prints 6, It seems an error. In my current cluster has a 6 brokers, maybe, application is printing the number of brokers...... maybe not, I'm not sure....
 
![akhq_replication_factor_ERROR](https://user-images.githubusercontent.com/692263/89016279-c40bb980-d318-11ea-8f0c-4fab33de3a33.png)

 Let me share the URI /<CLUSTER_NAME>/topic/<TOPIC-NAME>/partitions
![akhq_replication_factor_OK](https://user-images.githubusercontent.com/692263/89016504-21076f80-d319-11ea-8bab-32bad2de21a0.png)

**Comment by tchiotludo** [comment]
I think this one is resolved here : https://github.com/tchiotludo/akhq/pull/301.
Available on next release :smile:

**Comment by mcortinas** [comment]
Thank you! Do you know some ETA about next release?

**Comment by tchiotludo** [comment]
Normally, this week I hope 🤞

**Comment by mcortinas** [comment]
Perfect! Thank you! :)

**Comment by mcortinas** [comment]
Thank you very much for solve this in 0.15.0 , I checked in all my environments
