### ISSUE TITLE
Increased Logging

### ISSUE THREAD

**Issue by MrMunki** [tchiotludo/akhq#347]
Hello, I really like this product so far, but I have a couple of issues. I can't work out how to increase the logging. I'm trying to use LDAPS against Active Directory, which is not working, but I get nothing at all in the logs to say why. I also cannot see any topics in the list, but I can see all groups and ACL's.

Could someone let me know how to increase the logging please?

Thanks

**Comment by tchiotludo** [comment]
Hello, 

You have debugging instruction [here](https://github.com/tchiotludo/akhq#ldap). 
Especially : 

 ```yaml
curl -i -X POST -H "Content-Type: application/json" \
       -d '{ "configuredLevel": "TRACE" }' \
       http://localhost:8080/loggers/io.micronaut.configuration.security
```
Hope it help :smile:

**Comment by MrMunki** [comment]
Thanks. I'm struggling to get this to work though. I've imported my AD certs to the /etc/ssl/certs/java/cacerts but it just keeps throwing 
javax.naming.CommunicationException: simple bind failed: adservername.redacted:3269

.... loads of java stuff

Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

... loads of java stuff

Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

... some java stuff

Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

I'm using the latest version of the docker image, 0.15.0, but I just can't get this to work.

Any help would be greatly appreciated

**Comment by tchiotludo** [comment]
I think you must use : https://micronaut-projects.github.io/micronaut-security/latest/guide/#io.micronaut.configuration.security.ldap.configuration.LdapConfiguration$GroupConfiguration

especially : 
```
-Djavax.net.ssl.trustStore="<path to truststore file>"
-Djavax.net.ssl.trustStorePassword="<passphrase for truststore>"
```
In order to provide a valid truststore with your certificate

**Comment by MrMunki** [comment]
Great, thank you, I've got this working now. I also had to add 
search:
  filter: "sAMAccountName={0}"
to make it work with Active Directory

Still can't get a list of topics though

**Comment by tchiotludo** [comment]
it work @MrMunki ?

**Comment by MrMunki** [comment]
It did work yes, thank you. However, the topics are not working. Just logging another ticket for that one.
