### ISSUE TITLE
Base path is not used when loading static resources (0.15.0)

### ISSUE THREAD

**Issue by flare-test-account** [tchiotludo/akhq#357]
I updated AKHQ from 0.14.1 to 0.15.1 and it tries to get the static resources without using the base path on the property akhq.server.base-path. I tried both with and without the trailing slash (since on the readme it is told to use it but on application.example.yml it tells to use the path without the trailing slash).

**Comment by tchiotludo** [comment]
Hi,

I've seen recently that micronaut have a native option : 

```yaml 
micronaut: 
  server: 
    context-path: "/akhq"
```

Can you try please ? 
If it works, I will remove the specific one for akhq !

**Comment by senzzzi** [comment]
@tchiotludo it didn't work for me. I tried the property you suggested both with and without the previous property. Without it, the base path for the BE is not respected and it tries to go to "/login" instead of "/akhq/login". With it, it keeps redirecting indefinitely to "/akhq/login".

**Comment by tchiotludo** [comment]
Just confirm that really don't work :cry: 
This point was completely forgot when doing new ui. 
Working on it in later days

**Comment by tchiotludo** [comment]
Can you try with dev image please ? 
I think it work :)

**Comment by tchiotludo** [comment]
i forgot to mention, I move to `micronaut.server.context-path` and remove custom the old one ;)

**Comment by senzzzi** [comment]
Thanks for the fix @tchiotludo. Do you have and ETA for the next release?

**Comment by tchiotludo** [comment]
Since the next release will drop the old ui, it's a major change and I want to have the more feedback possible. 
So I think it will take about 1 month.

In a mean time, you can use the [dev](https://github.com/tchiotludo/akhq#development-environment) docker image or jar if you need it now.
