### ISSUE TITLE
Search by topic name not working on reset offset page

### ISSUE THREAD

**Issue by bochkarevnv** [tchiotludo/akhq#358]
Hello!
It looks like a bug, the search (ctrl+f) by topic name does not work on the reset offsets page.

**Comment by tchiotludo** [comment]
Hi 
I don't really understand what is your issue ? 
Can you add a screenshot and system / browser version please ?

**Comment by bochkarevnv** [comment]
I use Windows 10 and Chrome 64-bit 78.0.3904.97. On my screenshot topic name is data.*****.test and i try to find it on page by "data.". I have consumer groups with many topics and it’s hard to find the topic you want. 
![image](https://user-images.githubusercontent.com/35523301/90397701-eafc1680-e0a0-11ea-8291-5efc42c42e72.png)

**Comment by tchiotludo** [comment]
Can you try with last version on the new ui please ? 
The old will be removed soon ;)

**Comment by bochkarevnv** [comment]
I tried on a newer version - same problem.

**Comment by tchiotludo** [comment]
I try on my side and I can't reproduce this issue.
Does this issue exist on all page from akhq ?
Or only on this page ?

**Comment by bochkarevnv** [comment]
I tried another build with a new interface, the search works on it. I close the ticket.
