### ISSUE TITLE
Add last write datetime on topicks page

### ISSUE THREAD

**Issue by bochkarevnv** [tchiotludo/akhq#359]
Hello!
It would be nice if the topics viewing page would contain information about the datetime of the last write in this topic. Now for this information you need to go to the topic and change the sorting to newest or move the timestamp filter back until the data appears.
I don't have the skills to develop it myself.

**Comment by Presto412** [comment]
I'm interested to work on this, could you please give some starter points?

**Comment by tchiotludo** [comment]
You will need to add a Method `getLastRecord(String clusterId, String topic)` on `RecordRepository` and add a new route on `TopicController`

After we need to find the  logic on `RecordRepository`: 
- There is [this response](https://stackoverflow.com/questions/31735852/kafka-how-to-get-last-modified-time-for-a-topic-i-e-last-message-added-to-any?rq=1) that is very old and don't seems to be available on last client (to confirm)
- Last option I see is to use a KafkaConsumer, get last offset (`consumer.endOffsets`) and decrement offset (-1) till you have a message (`consumeSingleRecord`) and return the last record 
- Or find a better way :smile: 

Last, add a async call on the controller in order to add a col on `TopicList.jsx`

**Comment by Presto412** [comment]
Thanks @tchiotludo , I'll check this out.

**Comment by Presto412** [comment]
@tchiotludo I'm fairly new to kafka, but below is what I could come up with. Is this the right approach?
I get all the partitions of the topic, and then poll the messages, and decrement them based on timestamp. Please have a look

```java
           public Optional<Record> getLastRecord(String clusterId, String topicName, Options options) throws ExecutionException, InterruptedException {

        Topic topic = topicRepository.findByName(clusterId, topicName);
        List<TopicPartition> topicPartitions = topic.getPartitions().stream().map(partition -> new TopicPartition(partition.getTopic(), partition.getId())).collect(Collectors.toList());
        KafkaConsumer<byte[], byte[]> consumer = kafkaModule.getConsumer(clusterId);
        Map<TopicPartition, Long> endOffSets = consumer.endOffsets(topicPartitions);
        ConsumerRecord<byte[], byte[]> lastRecord = null;
        while (!endOffSets.isEmpty()) {
            consumer.assign(endOffSets.keySet());
            endOffSets.forEach(consumer::seek);
            ConsumerRecords<byte[], byte[]> consumerRecords = this.poll(consumer);
            if (!consumerRecords.isEmpty()) {
                while (consumerRecords.iterator().hasNext()) {
                    ConsumerRecord<byte[], byte[]> consumerRecord = consumerRecords.iterator().next();
                    if (lastRecord == null) {
                        lastRecord = consumerRecord;
                    } else {
                        lastRecord = lastRecord.timestamp() > consumerRecord.timestamp() ? lastRecord : consumerRecord;
                    }
                }
                break;
            }
            endOffSets = endOffSets.entrySet()
                    .stream()
                    .filter(topicPartitionLongEntry -> topicPartitionLongEntry.getValue() >= 1)
                    .map(topicPartitionLongEntry -> {
                                topicPartitionLongEntry.setValue(topicPartitionLongEntry.getValue() - 1);
                                return topicPartitionLongEntry;
                            }
                    ).collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue));
        }
        consumer.close();
        return Optional.ofNullable(lastRecord).map(record -> newRecord(record, options));
    }
```

**Comment by tchiotludo** [comment]
I have an idea right now, maybe it can help a lot on the algo ! 

- get the `Map<TopicPartition, Long> endOffSets = consumer.endOffsets(topicPartitions);`
- remove an arbitrary value (let say 10) when assign on each partition, and poll till the original endOffSets.

and from all the record keep the max offset.

What do you think about that ?

**Comment by Presto412** [comment]
@@tchiotludo Instead of getting the endOffSets,
once we have all the partitions, what if we do a binary search on the offsets of a partition?
Theoretically takes the least amount of time
Each partition would have the last record and finally we get the record with the latest timestamp

**Comment by tchiotludo** [comment]
Because internally, Kafka can have some offset that is not readable due to [Transactions](https://cwiki.apache.org/confluence/display/KAFKA/Transactional+Messaging+in+Kafka).
AKHQ is configured to read only `read_committed` offset and also want you commit a transaction, it take an offset that the Kafka Consumer will never be able to read. 
It's why I suggest a minus -10 to have an optimistic approach on this value.

**Comment by Presto412** [comment]
In either case, if we are only able to read the committed offsets, the result wouldn't make a difference right?
Maybe we can ignore the offsets that can't be read by the consumer, and perform binary search with that adjustment in mind

**Comment by Presto412** [comment]
Hey @tchiotludo , since it's read committed, we can just call the 
[committed](https://kafka.apache.org/25/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#committed-java.util.Set-) method. It retrieves the last committed offset which we can read

**Comment by tchiotludo** [comment]
To be honest, I don't know this method.
If it's work, go for it !!!
It's better than than my supposition 😃

**Comment by Presto412** [comment]
hey @tchiotludo  could you please check #439

**Comment by tchiotludo** [comment]
I was not really sure if the PR is done :smile: 
Will add my review now :+1:

**Comment by Presto412** [comment]
@tchiotludo updated as per comments

**Comment by tchiotludo** [comment]
done here #439
