### ISSUE TITLE
Helm - run as non root

### ISSUE THREAD

**Issue by alicekop** [tchiotludo/akhq#360]
Currently, when using helm, there is no way to run akhq as a non-root.
It makes the chart unusable in cases with strict security policy that forbids running containers as root.

It would be great to have a possibility to specify in helm chart that akhq container should be run as a different user.
I believe that this could be done simply by adding `securityContext` section in `values.yml` and using it within `deployment.yml` template.

**Comment by mcortinas** [comment]
it should be greatful!

**Comment by tchiotludo** [comment]
done in charts `0.1.3`
