### ISSUE TITLE
Allow to delete topic config

### ISSUE THREAD

**Issue by piotrp** [tchiotludo/akhq#362]
Currently there is no way to remove topic config and restore its displayed type to DEFAULT_CONFIG. It should be possible eg. by leaving text input empty.

My use case: clearing topic by setting `retention.ms`, i.e.:
1. Set `retention.ms` to 1
2. Wait
3. Delete `retention.ms` override

In most cases I don't want to store `retention.ms` in topic config because I want to use my cluster's default value.

**Comment by tchiotludo** [comment]
Good feature ;) 
To be honest, I also use the same trick for now :laughing:
