### ISSUE TITLE
org.apache.kafka.common.errors.SecurityDisabledException: No Authorizer is configured on the broker

### ISSUE THREAD

**Issue by PLarboulette** [tchiotludo/akhq#367]
Hello, 

Since the last release, we have an error on the page : 

>  /kafka-cluster/group/{{consumerGroup}}/topics

![image](https://user-images.githubusercontent.com/9429197/91178679-c843b080-e6e5-11ea-907e-2d4f4ecfe70b.png)

We don't change our cluster configuration and I don't see anything in the last commits that could explain this error. 

Any idea ? 

Thanks :)

**Comment by tchiotludo** [comment]
It was an issue on your cluster ?
