### ISSUE TITLE
New UI topic list displays consumer groups with skip-consumer-groups: true

### ISSUE THREAD

**Issue by andreybratus** [tchiotludo/akhq#372]
For clusters with large number of topics is expensive to show consumer groups. By setting the `skip-consumer-groups: true` I expect this information not to be fetched/shown when listing topics. It was working properly in `0.14.1` but seems that this config property is ignored in `0.15.0`.

**Comment by tchiotludo** [comment]
Thanks for the report :+1: 
you can try on dev branch ;)

**Comment by andreybratus** [comment]
Thank you,
I can confirm that it works as expected on dev.
