### ISSUE TITLE
Can not see pending Consumer Groups from Topic list in new version

### ISSUE THREAD

**Issue by 84drizzt** [tchiotludo/akhq#383]
Hello,
Previously I was using V0.12 and upgraded to V0.15. I noticed that the pending or inactive consumer groups are not showing in Topic list now .

Here is screenshot of older version, pending one is in yellow with lags:
![consumer stop](https://user-images.githubusercontent.com/1628155/91629701-d94e3380-e9fd-11ea-89bc-8ccbbd01641a.png)

Of course we can see ALL in "Consumer Groups" page, but it's a little inconvenience..
Is there any configuration to make pending ones show in Topic list again?

Thanks!

**Comment by polarising-java** [comment]
Hi @84drizzt already fixed on pull request https://github.com/tchiotludo/akhq/pull/378

**Comment by tchiotludo** [comment]
Try on dev branch and reopen if it's not working 👍

**Comment by 84drizzt** [comment]
Thanks very much!
