### ISSUE TITLE
HTTP contextPath support

### ISSUE THREAD

**Issue by gquintana** [tchiotludo/akhq#384]
I'd like to add a prefix to HTTP urls, in order to make reverse proxying easier.

There is a [contextPath](https://docs.micronaut.io/latest/api/io/micronaut/http/server/HttpServerConfiguration.html#setContextPath-java.lang.String-) setting in Micronaut HTTP Server.
```
micronaut.server:
  port: 8083
  contextPath: /akhq/
```

But adding this setting breaks AKHQ; it produces a 307 redirect to /ui which ends in NPE:
```
java.lang.NullPointerException
	at io.micronaut.web.router.resource.ReactStaticResourceResolver.resolve(ReactStaticResourceResolver.java:34)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.matchFile(RoutingInBoundHandler.java:630)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.channelRead0(RoutingInBoundHandler.java:557)
	at io.micronaut.http.server.netty.RoutingInBoundHandler.channelRead0(RoutingInBoundHandler.java:140)
```

**Comment by tchiotludo** [comment]
Hi,
there is already an issue [here](https://github.com/tchiotludo/akhq/issues/357) and it's fixed on `dev` version.
Can you try please ?

**Comment by gquintana** [comment]
It's better I can see the wait page with the animated AKHQ logo.
Sadly I get 404 on XHR request on `/api/me`  now.

**Comment by tchiotludo** [comment]
with dev branch ? really surprising.
- Are you using docker image or jar ? 
- Maybe you can share a chrome devtools screenshot of the networks tabs ? 
- can you share also yoiur configuration files ?

**Comment by gquintana** [comment]
The problem was the trailing /
Thanks for your help.

**Comment by tchiotludo** [comment]
not really sure of what you mean with that :
>  Gradle build produces a tarball containing binaries, startup script and sample config files.

I don't think I have change the gradle build :thinking:

**Comment by gquintana** [comment]
I am interested in the .tar / .zip files produced by Gradle (sadly no Docker here).
But they are not published in the [releases page](https://github.com/tchiotludo/akhq/releases) so far.

**Comment by tchiotludo** [comment]
ok understood :) 

you can make PR here : https://github.com/tchiotludo/akhq/blob/dev/.github/workflows/main.yml#L98 
To upload also zip and tar, for now there is only the jar.
