### ISSUE TITLE
Session fixation issue

### ISSUE THREAD

**Issue by sectestaccount** [tchiotludo/akhq#389]
Hi,

I have checked that the login form is vulnerable to session fixation vulnerabilities:
[](https://owasp.org/www-community/attacks/Session_fixation)

akhq assigns a Session ID (JSESSIONID) when a user logs into the application:

![image](https://user-images.githubusercontent.com/60386959/92449536-82ddb380-f1ba-11ea-9081-8437204d8e13.png)

If the user logs out, the application does not remove the SESSIONID:

![image](https://user-images.githubusercontent.com/60386959/92449682-af91cb00-f1ba-11ea-97ed-fa67bc7d55f0.png)

If the user logs into the application again, the SESSIONID cookie is not updated:

![image](https://user-images.githubusercontent.com/60386959/92449789-db14b580-f1ba-11ea-8943-0b30de94ddce.png)

The best way to fix this issue is to renew the session ID when a user logs in and remove/disable the session ID when the user logs out.

Thanks.
Kind regards.

**Comment by jniebuhr** [comment]
#342 Removes sessions and replaces them with JWT tokens
