### ISSUE TITLE
Session ID cookie attributes

### ISSUE THREAD

**Issue by sectestaccount** [tchiotludo/akhq#390]
Hi,

the SESSION cookie does not set the following attributes:
- SameSite: prevents the browser from sending this cookie along with cross-site requests. The main goal is mitigate the risk of cross-origin information leakage. It also provides some protection against cross-site request forgery attacks.

- Secure: This attribute tells the browser to only send the cookie if the request is being sent over a secure channel such as HTTPS. This will help protect the cookie from being passed over unencrypted requests.

![image](https://user-images.githubusercontent.com/60386959/92449536-82ddb380-f1ba-11ea-9081-8437204d8e13.png)

https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html#cookies

These attributes will help to secure the session management.

Thanks.
Kind regards.

**Comment by jniebuhr** [comment]
Sessions will most likely be removed in the next release. The secure mode is active by default for the JWT cookie, I've added the `cookie-same-site: strict` setting to the PR.
