### ISSUE TITLE
Avro data is bad encoded to json

### ISSUE THREAD

**Issue by zaghdous** [tchiotludo/akhq#406]
When I display avro records from a topic, the fields with union types are not encoded to json as expected in the avro spec (http://avro.apache.org/docs/current/spec.html#json_encoding):

Ex : 

Schema
{
  "type" : "record",
  "name" : "recordName",
   "namespace" : "name.space",
   "fields" : [ {
     "name" : "id",
     "type" : ["null", "int"]
   } ]
}

Gives the displayed Json :
{
   "id" : 141
}
But need to be (indeed I would like to produce to the topic an edited payload) :
{
   "id" : {"int" : 141}
}

When I use avro-tools to deserialize the avro, I obtain a json well encoded containing the type.
Is it something to configure? Thanks for your reply.

**Comment by tchiotludo** [comment]
the schema you provide need to be displayed as 
```json 
{
   "id" : 141
}
``` 
avro don't wrap the type like you said and I'm really surprise that avro-tools display it like that.
Seems that the akhq  displayed is the right way to display it !

**Comment by zaghdous** [comment]
Thanks for your reply, but please take a look to the avro spec (link above)

**Comment by tchiotludo** [comment]
I already know the avro specs, I've done a lot of avro in my life ! 
Your schema mean that your is can be null or int so :

```json 
{
   "id" : 141
}
``` 

Or 

```json 
{
   "id" : null
}
``` 

Not that you need to wrap the content like that.
Mostly you must use something that let think avro the wrong way

**Comment by zaghdous** [comment]
Sorry but it is explicit here :

**Comment by tchiotludo** [comment]
No link here !!
And i'm sure about that !!
There is no wrap on avro side.

**Comment by zaghdous** [comment]
Please take a moment : 

**test.asvc** :
{
	"type" : "record",
	"name" : "recordName",
	"namespace" : "name.space",
	"fields" : [ {
		"name" : "id",
		"type" : ["null", "int"]
	 } ]
}

**bad.json**:

{
"id" : 141
}

**good.json**:
{
"id" : {"int" : 141}
}

$ java -jar avro-tools-1.10.0.jar fromjson --schema-file test.asvc bad.json > test.avro
Exception in thread "main" org.apache.avro.AvroTypeException: Expected start-union. Got VALUE_NUMBER_INT

$ java -jar avro-tools-1.10.0.jar fromjson --schema-file test.asvc good.json > test.avro
OK

$ java -jar avro-tools-1.10.0.jar tojson test.avro > test.json

**test.json** :

{
"id" : {"int" : 141}
}

**Comment by zaghdous** [comment]
http://avro.apache.org/docs/current/spec.html#json_encoding

**Comment by KepptnKool** [comment]
I was just about to open a similar issue. @zaghdous  is right about the json encoding.

How about adding an option to use the standard avro json encoder?

See https://github.com/apache/avro/blob/master/lang/java/avro/src/main/java/org/apache/avro/io/JsonEncoder.java
