### ISSUE TITLE
Produce to topic: avro with nullable can't be produced

### ISSUE THREAD

**Issue by zaghdous** [tchiotludo/akhq#407]
Dear Ludovic, I reopen the issue that you closed because I really like your product and like to use it in my organization.
My goal is not to flood you with issues ! I think that the "produce to topic" function is cool but does not work since any given bad encoded JSON cannot be handled. Try to take the json you display and use it to produce a new message, you will get a **"org.apache.avro.AvroTypeException"** !

So here is the avro spec (link that I already added in the previous ticket) :

http://avro.apache.org/docs/current/spec.html#json_encoding

And an example of serde using avro-tools (we always learn even if you are a specialist):

**test.asvc :**
{
"type" : "record",
"name" : "recordName",
"namespace" : "name.space",
"fields" : [ {
"name" : "id",
"type" : ["null", "int"]
} ]
}

**bad.json:**

{
"id" : 141
}

**good.json:**
{
"id" : {"int" : 141}
}

$ java -jar avro-tools-1.10.0.jar fromjson --schema-file test.asvc bad.json > test.avro
Exception in thread "main" org.apache.avro.AvroTypeException: Expected start-union. Got VALUE_NUMBER_INT

$ java -jar avro-tools-1.10.0.jar fromjson --schema-file test.asvc good.json > test.avro
OK

$ java -jar avro-tools-1.10.0.jar tojson test.avro > test.json

**test.json :**

{
"id" : {"int" : 141}
}

**Comment by zaghdous** [comment]
I tested your app, and works exactly like avro-tools :
- unable to serialize bad.json to avro => AvroTypeException
- good.json is accepted and rendered in the same form !

So the pb is present when avro is not generated from json !

**Comment by tchiotludo** [comment]
Sorry to close the previous one !
Doing some test with your example, and for now, you need to produce `good.json` from akhq ! 
I really think it was not the case and `bad.json` should be accepted IMO. 

Your goal is to produce the good.json or the bad.json from akhq ?

**Comment by zaghdous** [comment]
🙂
Since bad.json is not accepted, the avro should decode to good.json which is accepted.
My goal is to copy a json, change data and resend it to the topic.
Thanks a lot !

**Comment by tchiotludo** [comment]
must be done on `dev`, can you try ?
