### ISSUE TITLE
Page listing doesn't work for consumer group tab

### ISSUE THREAD

**Issue by MCPDanilovich** [tchiotludo/akhq#419]
I use last version of akhq. I found, that list of consumer groups doesnt change when i change the page number.
![image](https://user-images.githubusercontent.com/25364749/94447524-83161100-01b2-11eb-8b3a-cf678dcda08b.png)
![image](https://user-images.githubusercontent.com/25364749/94447571-90cb9680-01b2-11eb-97eb-ddbfcfc1977b.png)

![image](https://user-images.githubusercontent.com/25364749/94447711-c40e2580-01b2-11eb-885b-fd7e64e898e5.png)

**Comment by tchiotludo** [comment]
fix on `dev` branch, can you try please ?
