### ISSUE TITLE
Can't update consumer group offset

### ISSUE THREAD

**Issue by MCPDanilovich** [tchiotludo/akhq#420]
![image](https://user-images.githubusercontent.com/25364749/94447899-00418600-01b3-11eb-8f42-541c71b8e830.png)

Topic name: <service>-<country>-<env>, in my cas: testservice-usa-dev

**Comment by tchiotludo** [comment]
Can you send me screenshot of the update consumer groups page before you hit the button please ? 
I really don't understand here (since it work on for me)

**Comment by MCPDanilovich** [comment]
![image](https://user-images.githubusercontent.com/25364749/94452128-e0609100-01b7-11eb-8a60-d2cbce4ffd35.png)

When i change offset for partition:

![image](https://user-images.githubusercontent.com/25364749/94452219-f9694200-01b7-11eb-8533-1c7f9962b7c2.png)

Now i use docker image with dev tag from your docker registry.

**Comment by tchiotludo** [comment]
I see `leonbets` on the error but not on the screenshot.
still strange, can you give the output off chrome devtools during the request.
to see what the the client try yo send to the server ?

**Comment by MCPDanilovich** [comment]
Request URL: https://kafkahq.common.dev.leoncorp.net/api/kafka-gce-dev/group/betTickerBetOperationConsumer-v1-083ccb69-614f-4e86-93d2-c5f2b916995e/offsets
Request Method: POST
Status Code: 500 
Remote Address: 35.198.189.242:443
Referrer Policy: strict-origin-when-cross-origin

**Comment by MCPDanilovich** [comment]
:authority: kafkahq.common.dev.domain.net
:method: POST
:path: /api/kafka-gce-dev/group/betTickerBetOperationConsumer-v1-083ccb69-614f-4e86-93d2-c5f2b916995e/offsets
:scheme: https
accept: application/json, text/plain, */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9,ru;q=0.8
cache-control: no-cache
content-length: 1028
content-type: application/json;charset=UTF-8
cookie: SESSION=NjAxMGFkOGYtYjgwNS00MDE5LWIxNGEtYzEzNTU0ZDg2YmU3
origin: https://kafkahq.common.dev.leoncorp.net
pragma: no-cache
referer: https://kafkahq.common.dev.domain.net/ui/kafka-gce-dev/group/betTickerBetOperationConsumer-v1-083ccb69-614f-4e86-93d2-c5f2b916995e/offsets
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36

**Comment by MCPDanilovich** [comment]
![image](https://user-images.githubusercontent.com/25364749/94453696-a7c1b700-01b9-11eb-92f2-425aafb74051.png)

**Comment by tchiotludo** [comment]
perfect, just missing the body please of the request ! (last screen on the bottom)

**Comment by MCPDanilovich** [comment]
![Uploading image.png…]()

**Comment by MCPDanilovich** [comment]
![image](https://user-images.githubusercontent.com/25364749/94454882-1d7a5280-01bb-11eb-98bf-c56e78f2e7be.png)

**Comment by tchiotludo** [comment]
ok that the error :) 
a partition with a string can't work ... but how do you have this string on partition ... :thinking: 
have you any screen where I can find this string on the ui ?

**Comment by MCPDanilovich** [comment]
![image](https://user-images.githubusercontent.com/25364749/94457089-ca090400-01bc-11eb-9a3e-59fc91fa5196.png)
This is different group but result is the same. 
![image](https://user-images.githubusercontent.com/25364749/94457191-eb69f000-01bc-11eb-9662-0f5c725d62b2.png)

**Comment by MCPDanilovich** [comment]
![image](https://user-images.githubusercontent.com/25364749/94457254-f7ee4880-01bc-11eb-9dc8-f0d0fdae4869.png)

**Comment by tchiotludo** [comment]
ok found it :) 
can you try with last `dev` version please ?

**Comment by MCPDanilovich** [comment]
![image](https://user-images.githubusercontent.com/25364749/94518447-9a94de80-0232-11eb-8cef-4d1e259b7b30.png)
Something wrong. I got loop on auth stage.
![image](https://user-images.githubusercontent.com/25364749/94518486-abddeb00-0232-11eb-8e5f-5d8556381a3d.png)

**Comment by tchiotludo** [comment]
Really strange I didn't change anything about login.
Can you show me the auths path response ?

**Comment by MCPDanilovich** [comment]
![image](https://user-images.githubusercontent.com/25364749/94534341-f2d6db00-0248-11eb-9879-af21eef2cb3a.png)

**Comment by tchiotludo** [comment]
The tab with response please 😆

**Comment by MCPDanilovich** [comment]
Sorry. 
![image](https://user-images.githubusercontent.com/25364749/94535603-6e855780-024a-11eb-9bac-7b85d8723def.png)

**Comment by tchiotludo** [comment]
Really strange, this endpoint return that there is no login, you are redirected to login every time ? 
Can you share your configuration files please ?

**Comment by MCPDanilovich** [comment]
`akhq:
  server:
    base-path: ""
    access-log:
      enabled: true
      name: org.akhq.log.access
      format: "[Date: {}] [Duration: {} ms] [Url: {} {} {}] [Status: {}] [Ip: {}] [Length: {}] [Port: {}]"

  clients-defaults:
    consumer:
      properties:
        isolation.level: read_committed
  connections:
    kafka-gce-feed-exporter:
      properties:
        bootstrap.servers: "<>"
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="<>" password="<>";
    kafka-gce-dev:
      properties:
        bootstrap.servers: "<>:9092"
    bs-kafka-dev:
      properties:
        bootstrap.servers: "<>:9092"
        security.protocol: SASL_SSL
        sasl.mechanism: PLAIN
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="<>" password="<>";
        ssl.truststore.location: /app/kafka.truststore.jks
        ssl.truststore.password: <>
        ssl.endpoint.identification.algorithm : ""

  security:
    default-group:
      - node-read
    groups:
      node-read:
        roles:
           - node/read
        attributes:
        # Regexp to filter topic available for group
          topics-filter-regexp: ".*"
      kafkahq-reader: # Group name
        roles:  # roles for the group
           - topic/read
           - node/read
           - topic/data/read
           - topic/insert
           - topic/data/read
           - topic/data/insert
           - topic/data/delete
           - group/read
           - registry/read
           - connect/read
        attributes:
        # Regexp to filter topic available for group
          topics-filter-regexp: ".*"
      kafkahq-admin:
        roles:
          - topic/read
          - topic/insert
          - topic/delete
          - topic/config/update
          - node/read
          - node/config/update
          - topic/data/read
          - topic/data/insert
          - topic/data/delete
          - group/read
          - group/delete
          - group/offsets/update
          - acls/read
          - registry/read
          - registry/insert
          - registry/update
          - registry/delete
          - registry/version/delete
        attributes:
          topics-filter-regexp: ".*"
    ldap:
      group:
        kafkahq-user:
          groups:
            - kafkahq-reader
        ipausers:
          groups:
            - kafkahq-admin
        kafkahq-admin:
          groups:
            - kafkahq-admin

  pagination:
    page-size: 15 # number of elements per page (default : 25)
    threads: 30 # Number of parallel threads to resolve page
  topic:
    retention: 172800000 # default retention period when creating topic
    partition: 3 #  default number of partition when creating topic
    replication: 3 # default number of replicas when creating topic
    default-view: HIDE_INTERNAL # default list view (ALL, HIDE_INTERNAL, HIDE_INTERNAL_STREAM, HIDE_STREAM)
    skip-consumer-groups: true
    internal-regexps: # list of regexp to be considered as internal (internal topic can't be deleted or updated)
      - "^_.*$"
      - "^.*_schemas$"
      - "^.*connect-config$"
      - "^.*connect-offsets$1"
      - "^.*connect-status$"
    stream-regexps: # list of regexp to be considered as internal stream topic
      - "^.*-changelog$"
      - "^.*-repartition$"
      - "^.*-rekey$"
  topic-data:
    sort: OLDEST # default sort order (OLDEST, NEWEST) (default: OLDEST)
    size: 40 # max record per page (default: 50)
    poll-timeout: 29900 # The time, in milliseconds, spent waiting in poll if data is not available in the buffer.`

**Comment by tchiotludo** [comment]
ok no security enabled so (no login) ! The endpoint is right ! 

Can you respond to this : 
>  this endpoint return that there is no login, you are redirected to login every time ?

**Comment by MCPDanilovich** [comment]
micronaut:
  security:
    ldap:
      default:
        enabled: true
        context:
          server: 'ldap://<>:389'
          managerDn: 'uid=service-kafka-hq,cn=users,cn=accounts,dc=domain,dc=net'
          managerPassword: '<>'
        search:
          base: "cn=users,cn=accounts,dc=domain,dc=net"
        groups:
          subtree: true
          enabled: true
          base: "cn=groups,cn=accounts,dc=domain,dc=net"
          filter: "member={0}"

**Comment by tchiotludo** [comment]
ok !! the format of the configuration files have changed on dev version ! (especially for group & security).
Please look at this changed here : https://github.com/tchiotludo/akhq/commit/5ab788da22529ede3c7b640f1918304511cea6f0
