### ISSUE TITLE
Missing required configuration "bootstrap.servers" which has no default value [But it is specified]

### ISSUE THREAD

**Issue by m-stojanovic** [tchiotludo/akhq#422]

**Comment by tchiotludo** [comment]
it's works ? you found the solution ?

**Comment by m-stojanovic** [comment]
> it's works ? you found the solution ?

yes, I wanted just to remove as it could be possible extra spam here. So I closed and edited. Was a pretty simple problem, not worth showing.

**Comment by tchiotludo** [comment]
:+1:
