### ISSUE TITLE
Procedure to add CAroot cert of LDAP into HELM chart deploy

### ISSUE THREAD

**Issue by gerardgorrion** [tchiotludo/akhq#426]
Hi all,

We want to add the CAroot certificate into HELM deploy. I can see into values.yml the below code:

```
initContainers: {}
#   create-keystore: 
#     image: "openjdk:11-slim"
#     command: ['sh', '-c', 'keytool'] <-- here put de keytool code to add into pod akhq?
#     volumeMounts:
#      - mountPath: /tmp
#        name: certs
```

How can I add the cert of LDAP to cacert of openjdk into a pod akhq?
Thanks!

**Comment by gerardgorrion** [comment]
And where we define jvm.options values? in values.yaml? because we need to add:

```
#SSL trustStore
-Djavax.net.ssl.trustStore=/usr/local/openjdk-11/lib/security/cacerts
-Djavax.net.ssl.trustStorePassword=password
```

**Comment by tchiotludo** [comment]
extraVolumes  & extraVolumeMounts to mount the certificate  & 
```
  extraEnv:
    - name: JAVA_OPTS
      value: "-Djavax.net.ssl.trustStore=/usr/local/openjdk-11/lib/security/cacerts -Djavax.net.ssl.trustStorePassword=password"
```

**Comment by gerardgorrion** [comment]
We need to change the templates/deployment.yaml?

```
containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          env:
          {{- if .Values.secrets }}
          - name: MICRONAUT_ENVIRONMENTS
            value: secrets
          - name: MICRONAUT_CONFIG_FILES
            value: /app/application.yml,/app/application-secrets.yml
          {{- end }}
          {{- **with .Values.image.extraEnv** }}
{{ toYaml . | trim | indent 10 }}
          {{- end }}
          volumeMounts:
          {{- if .Values.extraVolumeMounts }}{{ toYaml .Values.extraVolumeMounts | trim | nindent 12 }}{{ end }}
          {{- if .Values.configuration }}
            - name: config
              mountPath: /app/application.yml
              subPath: application.yml
          {{- end }}
          {{- if .Values.secrets }}
            - name: secrets
              mountPath: /app/application-secrets.yml
              subPath: application-secrets.yml
          {{- end }}
```
First stem add extraEnv and navigate into jvm.options on pod created by HELM chart and it doesn't show any extra line with the Djavax configs...

**Comment by tchiotludo** [comment]
I've fix the helm charts : https://github.com/tchiotludo/akhq/commit/ac9f276a0fdefdcfd998b74daabcff651e7f8a4f 
There is a new version `image` was wrong. 
Can you try please ?

**Comment by gerardgorrion** [comment]
![Captura](https://user-images.githubusercontent.com/35425181/94820127-60793780-0400-11eb-86fb-3e106d8950a1.PNG)

Yes, seem like the variable to be inside pod, are now into akhq.jar? Because on the jvm.options they are not show

**Comment by tchiotludo** [comment]
the jvm.options is a static files ! 
echo $JAVA_OPTS to see if the env vars is good 

and the magic happen here : https://github.com/tchiotludo/akhq/blob/dev/docker/app/akhq

**Comment by gerardgorrion** [comment]
And we assume that akhq/docker/app/files are running with akhq/helm/akhq version, right?

echo show: 
```
root@pod:/app# echo $JAVA_OPTS
-Djavax.net.ssl.trustStore=/usr/local/openjdk-11/lib/security/cacerts -Djavax.net.ssl.trustStorePassword=pass
```

now we should use volume mount to insert our cacert.

**Comment by tchiotludo** [comment]
no the version is wrong on this (not sticked), it use :latest by default as you can see in the values.yaml

**Comment by gerardgorrion** [comment]
There's no way to config LDAP via SSL/TLS on HELM version? maybe the best solution is use a custom image of current AKHQ lastest or dev?

**Comment by tchiotludo** [comment]
You can !! 
Already tell you how to it here : https://github.com/tchiotludo/akhq/issues/426#issuecomment-702039151

**Comment by gerardgorrion** [comment]
In akhq readme I only can see the config to docker:

```
volumeMounts:
- mountPath: /app/application.yml
  subPath: application.yml
  name: config
  readOnly: true
'''

I tested this one:

```
extraVolumes: 
  - name: certs
    mountPath: /app/certs

extraVolumeMounts: 
  - name: cacerts
    mountPath: /app/cacert
    subPath: cacert
```

and no need to comment the result 👎 
No examples and no docu about this deploy it is hard. Thanks!

**Comment by tchiotludo** [comment]
This is no example because there is no right way to it. 
Every people do it the way they want (secrets, configmaps, ...) and it's standard kubernetes knowledge that you need to learn if you want to work with k8s.

Unfortunately, it's not me that will have the time to teach you k8s over github issue. 
So please dig on google, there is a lot lot lots of examples on how to mount a volume with some secrets inside.
