### ISSUE TITLE
GitHub oauth2 with organization restrictions example

### ISSUE THREAD

**Issue by sergeyshaykhullin** [tchiotludo/akhq#446]
Hello, i am using akhq behind oauth2-proxy in k8s cluster
I found that i can use micronaut's oauth, but example is using google provider with no access restrictions

I want to use it with GitHub oauth app and restrict access by organization. I think it is very common use

I tried to do it myself, but don't get how to do it working
Can you please provide an example and/or add to docs

Thanks!

**Comment by tchiotludo** [comment]
Micronaut don't provide this logic for now. 

One simple way to handle this is here : 
https://github.com/tchiotludo/akhq/blob/5ab788da22529ede3c7b640f1918304511cea6f0/src/main/java/org/akhq/modules/OidcUserDetailsMapper.java#L126-L131

Just add some configurations and check here if the email of one of allowed domain and map the user to the default group `no-roles` and it's done. 

PR are welcome :+1:

**Comment by sergeyshaykhullin** [comment]
Thanks

**Comment by tchiotludo** [comment]
Keep it open if anyone willing to do it 😉
