### ISSUE TITLE
Add akhq to artifacthub.io

### ISSUE THREAD

**Issue by sergeyshaykhullin** [tchiotludo/akhq#447]
https://artifacthub.io (https://hub.helm.sh) has no akhq packages

I think you have to become verified publisher

**Comment by tchiotludo** [comment]
Hi :) 
Thanks for pointing me this :) I didn't know this one. 
Only the old helm hub. 

First part is done : https://artifacthub.io/packages/helm/akhq/akhq

Just really can figure how to deal with README & LICENSE files, any clue ?

**Comment by sergeyshaykhullin** [comment]
Sorry, i can't help you with this, i don't know.

Just found that no akhq in new chart browser =(

**Comment by tegioz** [comment]
Hi @tchiotludo 

The README and LICENSE content displayed in Artifact Hub is obtained from the `README.md` and `LICENSE` files in the chart package (https://helm.sh/docs/topics/charts/#the-chart-file-structure). There also also some [Artifact Hub specific annotations](https://artifacthub.io/docs/topics/annotations/helm/) you can use to improve users experience.

**Comment by tchiotludo** [comment]
Thanks @tegioz for the information. 
I've added the files https://github.com/tchiotludo/akhq/commit/43b4184030db7afc8a5e64d0275a50d7ec57d29e and release a new charts version, it's working :) 
Thanks a lot for the tips :+1:

**Comment by tegioz** [comment]
Awesome, no worries 👍
