### ISSUE TITLE
Pass trust store file through helm

### ISSUE THREAD

**Issue by vikesh-chauhan** [tchiotludo/akhq#452]
I am downloading akhq as a subchart through helm. I have overridden all configuration but not able to pass the truststore.jks file from parent chart to akhq subchart. What is the best way to do that?

**Comment by tchiotludo** [comment]
What is the main charts ? In order to understand deeply ?

**Comment by vikesh-chauhan** [comment]
The main chart is basically a wrapper around akhq chart which overrides the values.yaml file needed for akhq. my values.yaml for main charts looks like below. What i would like to do is for akhq to use the truststore.jks file located in the main chart for akhq's ssl configuration

kafka-akhq:
  secrets: |
    akhq:
      connections:
        xyz:
          properties:
            bootstrap.servers: <bootstrap urls>
            security.protocol: SSL
            ssl.truststore.location: /app/truststore.jks
            ssl.truststore.password: changeit
            ssl.keystore.location: /app/truststore.jks
            ssl.keystore.password: <password>
          schema-registry:
            url: <schema registry url>
      security:
        basic-auth:
          - user: admin
            password: <hashed password>
            groups:
              - admin
        groups:
          admin:
            roles:
              - topic/read
              - topic/insert
              - topic/delete
              - topic/config/update
              - node/read
              - node/config/update
              - topic/data/read
              - topic/data/insert
              - topic/data/delete
              - group/read
              - group/delete
              - group/offsets/update
              - registry/read
              - registry/insert
              - registry/update
              - registry/delete
              - registry/version/delete
              - acls/read
              - connect/read
              - connect/insert
              - connect/update
              - connect/delete
              - connect/state/update

**Comment by vikesh-chauhan** [comment]
I was able to achieve it using extraVolumes and extraVolumeMounts. Thanks!

**Comment by vikesh-chauhan** [comment]
Hi I would like to reopen the issue as volume mount did not resolve the issue.

To summarize: I am have a parent helm chart which has truststore.jks file which i would like to pass to the subchart (akhq in this case). The parent chart does not have a pod to mount the file to a volume. Is there anyway I can pass the file to subchart for akhq subchart to use for truststore config
