### ISSUE TITLE
Skip loading consumer group information is not working

### ISSUE THREAD

**Issue by nuncard** [tchiotludo/akhq#466]
Setting the configuration variable akhq.topic.skip-consumer-groups to true, does not produce the expected behavior.
The application dos not "skip loading consumer group information when showing topics".

**Version:** 0.16.0

**Comment by tchiotludo** [comment]
Look at these : https://github.com/tchiotludo/akhq/pull/464
Since the consumer group call are async now (and don't prevent the topic list to be loaded), I don't see a use case for this configuration for now.

**Comment by nuncard** [comment]
Anyway, it is still a valid configuration property.
And I see no reason to drop it, as it allow us to tweak the interface.
So, are you planning to fix it ?

**Comment by tchiotludo** [comment]
Not really sure, is there still use case for this now ? 
The main use case is slow down on topic page. 
Since it's no more the case, I don't really sure I will fix it. 

But feel free the give me some reason :smile:

**Comment by nuncard** [comment]
Ok, I understand.
Just stop mentioning skip-consumer-groups property in your documentation, please.
Otherwise it will always look to be a bug

**Comment by tchiotludo** [comment]
The documentation was remove yesterday, in a meantime, there is this PR https://github.com/tchiotludo/akhq/pull/464 that have the same need !
You can follow this as there is a valid reason 🙂
