### ISSUE TITLE
Loading consumer group makes the server unavailable due to memory issues

### ISSUE THREAD

**Issue by nuncard** [tchiotludo/akhq#467]
When we open the application, it raises a lot of errors and is unable to list the consumer list for each topic.

A deep analysis shown that for each call of /api/dev/topic/<topicname>/groups, the server replies with a 79MB-json-file. Which multiplied by 25 requests at the same time makes the server unavailable due to memory issues.

> Exception in thread "pool-1-thread-241" java.lang.OutOfMemoryError: Java heap space

All this just to open AKHP's home page just one time.

**Version:** 0.16.0

**Comment by tchiotludo** [comment]
I've a same report yesterday about that. 

Just for information, what how many consumer & how many partition on these topics ? 
We need to remove a lot of unnecessary informations on this endpoint

**Comment by nuncard** [comment]
By replicating the same action in version 0.12.0 the scenario is:

**Topics:** 25
**Partitions:**
1 topic with 1 partition;
1 topic with 2 partitions;
16 topics with 3 partitions;
5 topics with 12 partitions;
2 topics with 25 partitions;
**Consumers:**
8 topics with 2 consumers;
14 topics with 3 consumers;
3 topics with 4 consumers;
