### ISSUE TITLE
Link to Topic (from Consumer Groups) not respecting "micronaut.server.context-path"

### ISSUE THREAD

**Issue by dspereira-avlino** [tchiotludo/akhq#469]
We are setting the context-path as we are running AKHQ behind a reverse proxy. Most of the links seem to respect that, but not the link where we are redirected to a Topic (when we are in the Consumer Groups view). The context-path is not prepended to the link.
 
![image](https://user-images.githubusercontent.com/55401641/96730606-4357d900-13ae-11eb-907d-553f7d529a0d.png)

**Version:** 0.16.0

**Comment by tchiotludo** [comment]
done, you can try with dev version
