### ISSUE TITLE
Live tail is not fetching data

### ISSUE THREAD

**Issue by vislante** [tchiotludo/akhq#471]
I am new to using akhq, i tried to set the server up using kubernetes and am able to do it without any issues. I am able to add users to specific groups and set up permissions.

But we have a problem in accessing live tail messages. When we try to do that we are having the following issues

Error on UI

![image](https://user-images.githubusercontent.com/6615306/96835311-00613880-1476-11eb-9730-16cfeaac8394.png)

On server side we are getting this error in the logs

![image](https://user-images.githubusercontent.com/6615306/96835413-2090f780-1476-11eb-8b51-28cfa2a07d9a.png)

Not sure if this is an issue from the configuration or permissions.

**Comment by tchiotludo** [comment]
Mostly it must be ACLS on your Kakfa Cluster, AKHQ declare on group id: 
https://github.com/tchiotludo/akhq/blob/13aafa288b1cceb0ac55397a1197572b54b5a4e1/src/main/resources/application.yml#L100
And your cluster must have some acls that prevent `Akhq` to consume ! 
To be honest, I'm not really sure why this configuration is provide by default. 
In my memory, I think I could remove this one.

Maybe you can try to add this to your configuration files : 
```yaml
akhq:
  clients-defaults:
        group.id: null
```
To see If it resolved your issue ?
