### ISSUE TITLE
Horizontal scrollbar in Firefox

### ISSUE THREAD

**Issue by Crack** [tchiotludo/akhq#474]
AKHQ 0.16.0 in Firefox 81.0.2 has horizontal scrollbar:

![obraz](https://user-images.githubusercontent.com/1409807/96875977-24257e00-1478-11eb-9929-2ea3f55d9e9e.png)

It may be relevant that my browser has devicePixelRatio == 1.25 (125% inherited from OS settings).

**Comment by polarising-java** [comment]
@tchiotludo  The problem is with the position: sticky in the searchbar. In firefox the scrollbars ( horizontal and vertical) are visible with the sticky option.
