### ISSUE TITLE
akhq Api

### ISSUE THREAD

**Issue by skate9819** [tchiotludo/akhq#483]
Hi. 
Is it possible to close the api? We really want to use the latest version, but without the api.

**Comment by tchiotludo** [comment]
It's not possible, the latest version depend on the api completely since it was a react based application. 
I don't see any reasonable reason to close the api, do you have one to provide ?

**Comment by skate9819** [comment]
We want to close the api because you can use the api to perform operations that are not allowed in any **security.groups**.
This is very bad for the clusters without an ACL.

**Comment by tchiotludo** [comment]
In this case, you need to enable security on akhq to secure akhq, that will secure the akhq api

**Comment by skate9819** [comment]
I'm just stupid. The config was a bit bad. Now everything works as it should.
**Thank you very much!**
