### ISSUE TITLE
error on akhq/helm/akhq/templates/deployment.yaml

### ISSUE THREAD

**Issue by cpoule23** [tchiotludo/akhq#488]
Hi,
It seems to have an error on line 56.
           {{- if $.Values.extraEnv }}{{ toYaml $.Values.extraEnv | trim | nindent 12 }}{{ end }}
should be            {{- if .Values.extraEnv }}{{ toYaml .Values.extraEnv | trim | nindent 12 }}{{ end }}

Thanks  :)

**Comment by tchiotludo** [comment]
PR ? :+1:  :smile:  ?
