### ISSUE TITLE
Some links not working when using custom context-path

### ISSUE THREAD

**Issue by axblu** [tchiotludo/akhq#489]
When defining a custom `context-path` (e. g. `"/akhq"`) in the configuration, some links are not working.

For example:
The link to a consumer group when you are in the topics view.
The link to a topic when you are in the consumer groups view (either all or for a specific topic).

**Comment by tchiotludo** [comment]
I think it's already fix on https://github.com/tchiotludo/akhq/issues/469, can you try with dev image and reopen if not ?
