### ISSUE TITLE
Invalid button links when context-path set

### ISSUE THREAD

**Issue by gquintana** [tchiotludo/akhq#493]
On akhq 0.16, I have set `context-path: "/akhq"
Most of the UI is properly displayed with the /akhq prefix.

Except 2 links are broken:
- on a consumer group button (in row_groupComponent_6) from the Topics page: The link points to https://myhost/ui/mycluster/group/mygroup instead of http://myhost/akhq/ui/mycluster/group/mygroup 
- on a topic button (in row_topics_4) from the Consumer Groups page. The link points to https://myhost/ui/mycluster/topic/mytopic instead of https://myhost/akhq/ui/mycluster/topic/mytopic

**Comment by tchiotludo** [comment]
Already fix, see #469 and #489
