### ISSUE TITLE
Terraform chart "akhq/akhq" not found

### ISSUE THREAD

**Issue by Jean-Mercier** [tchiotludo/akhq#497]
Hello
Thanks for the job i try to install the chart with the provider terraform helm
https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release

My problem :
i declare the ressource 
```
resource "helm_release" "akhq" {
  name        = "akhq"
  repository  ="https://akhq.io/"
  chart       = "akhq/akhq"
  values      = [
    file("akhq_values.yaml")
  ]
...
}
```

But Terraform return error on apply :
`Error: chart "akhq/akhq" not found in https://akhq.io/ repository`

Do you have a technical url like 
https://kubernetes-charts.storage.googleapis.com
for your charts ?

**Comment by tchiotludo** [comment]
Hi, 
The charts are here : https://akhq.io/index.yaml so repository is https://akhq.io/
I think you must use : 
```
resource "helm_release" "akhq" {
  name        = "akhq"
  repository  ="https://akhq.io/"
  chart       = "akhq"
  values      = [
    file("akhq_values.yaml")
  ]
...
}

**Comment by Jean-Mercier** [comment]
thanks it's this
