### ISSUE TITLE
Display username of current logged users

### ISSUE THREAD

**Issue by tchiotludo** [tchiotludo/akhq#508]

**Comment by polarising-java** [comment]
@tchiotludo:  Do you have some preference in the place where we put the username?

**Comment by tchiotludo** [comment]
The better will be on left menu like the old akhq (and move the login button also here) I think.
The button as somewhat break with big name or in responsive. 

If you have some trouble, just remove the button when the user is logged and add a logout button with the current username at the same place

**Comment by polarising-java** [comment]
Only added the name in the logout button for now.
Move the button to the sidebar is another challenge
