### ISSUE TITLE
list of topics for tailing incomplete ?

### ISSUE THREAD

**Issue by jorgheymans** [tchiotludo/akhq#513]
The dropdown that lists the topic available for tailing is no longer complete. We have several hundreds of topics, but the dropdown is only showing the first 10, and the search does not work. In 0.14 this was working fine, has something changed here ?

**Comment by tchiotludo** [comment]
yes we have changed  to react the whole ui, maybe a bug here, we will look, thanks for the report

**Comment by jorgheymans** [comment]
Thanks, I am testing this using the dev branch.

**Comment by tchiotludo** [comment]
Don't see any change on this part since the react ui, the bug most be since 0.15.0 I think, but thanks for the information

**Comment by larvinloy** [comment]
I was seeing the same issue and applying pagination config seems to fix the drop down issue:
```
pagination:
        page-size: 10000
```

**Comment by jorgheymans** [comment]
Thanks @larvinloy , this seems to be a global setting though. When i set it to 1000 it's now trying to load all topics at once in the topic overview page, that's not desirable there paging should stay something like 25.

**Comment by polarising-java** [comment]
The list is using a paginated API. Must be change to other without pagination.

**Comment by jorgheymans** [comment]
Confirming that the fix works, thanks !
