### ISSUE TITLE
When setting Context Path, the readinessProbe path is not updated

### ISSUE THREAD

**Issue by nfldsantos** [tchiotludo/akhq#520]
When setting:

**micronaut.server.context-path** the **readinessProbe.httpGet.path** is not updated with that context-path before /health

To fix this, need to add the context-path also the the path of http get of readiness probe.

Installed with helm chart
File to change: /templates/deployment.yaml
Image tag: latest

**Comment by tchiotludo** [comment]
I've added `readinessProbe.prefix` on `values.yaml` to handle this. 
I've no way to link micronaut configuration with helm charts
