### ISSUE TITLE
Connects config doesn't have all configs options 

### ISSUE THREAD

**Issue by gkoritnik** [tchiotludo/akhq#521]
AKHQ don't have all configuration properties under configs tab.

For example:
While configuring AVRO Schema Registry for JMS connector in configs section there is no options to configure:
- basic.auth.credentials.source
- value.converter.schema.registry.basic.auth.user.info
- value.converter.basic.auth.credentials.source
- schema.registry.url
- schema.registry.basic.auth.user.info

Under configs there should be available all available settings for connectors.

So to configure connector with all necessary properties direct call to connect API is needed. 
Example configuration via REST API:
{
  "connector.class": "io.macronova.kafka.connect.jms.JmsSinkConnector",
  "jms.message.converter.output.format": "avro",
  "errors.log.include.messages": "true",
  "tasks.max": "1",
  "basic.auth.credentials.source": "USER_INFO",
  "value.converter.schema.registry.basic.auth.user.info": "user:password",
  "jms.destination.name": "queue.from.kafka.avro",
  "errors.deadletterqueue.context.headers.enable": "true",
  "value.converter.basic.auth.credentials.source": "USER_INFO",
  "jms.url": "tcp://url:port,tcp://url:port",
  "schema.registry.url": "https://url:8283",
  "jms.username": "user",
  "errors.deadletterqueue.topic.replication.factor": "3",
  "value.converter": "io.confluent.connect.avro.AvroConverter",
  "errors.log.enable": "true",
  "key.converter": "io.confluent.connect.avro.AvroConverter",
  "errors.retry.timeout": "10000",
  "topics": "topic-name",
  "jms.connection.factory": "com.tibco.tibjms.TibjmsQueueConnectionFactory",
  "errors.retry.delay.max.ms": "5000",
  "value.converter.schema.registry.url": "https://url:8283",
  "errors.deadletterqueue.topic.name": "que-name",
  "name": "name",
  "schema.registry.basic.auth.user.info": "user:password",
  "errors.tolerance": "all",
  "jms.password": "password",
  "jms.destination.type": "queue",
  "key.converter.schema.registry.url": "https://url:8283"
}

**Comment by spetar** [comment]
We also have the same problem!!! 

In AKHU under connector Configuration for "Schema Registry" we can see only those 2 properties regarding schema registry :
- value.converter.schema.registry.basic.auth.user.info,
- key.converter.schema.registry.url

other schema registry configurations are missing. 
This is really annoying because, if we change any other property through UI, these properties bellow are deleted from connector configuration:
- "schema.registry.url": "https://url:8283"
- "basic.auth.credentials.source": "USER_INFO"
- "value.converter.basic.auth.credentials.source": "USER_INFO"
- "value.converter.schema.registry.url": "https://url:8283"
- "schema.registry.basic.auth.user.info": "user:password"

**and connector than failes!**

**Comment by tchiotludo** [comment]
Can you provide the exact connector link please ?
So you can try on our side ?
Thanks

**Comment by gkoritnik** [comment]
Hi tchiotludo,

I have Kafka and connectors inside secure environment and it's not exposed to outside world.
But I can help you with configuration and with recurrence of the problem.

I used debezium base connector:
https://hub.docker.com/r/debezium/connect-base

And imported debezium connect plugins, but you can also use debezium connect with plugins:
https://hub.docker.com/r/debezium/connect

In plugins I added also JMS connect:
https://github.com/macronova/kafka-connect-jms
But for this connector you also must add client dependencies:
https://www.tibco.com/resources/product-download/tibco-enterprise-message-service-community-edition--free-download

**Comment by gkoritnik** [comment]
And I also must say, that missing config options are on all connectors. So you can use io.debezium.connector.postgresql.PostgresConnector for testing purposes.

**Comment by tchiotludo** [comment]
mostly this one is hardcoded, I don't understand why plugins to expose all the properties. 
If you want to add one, if's [here](https://github.com/tchiotludo/akhq/blob/dev/src/main/java/org/akhq/models/ConnectPlugin.java#L40
)
You can try with `dev` branch
