### ISSUE TITLE
Tail : Topics list is incomplete in dropdown

### ISSUE THREAD

**Issue by jthiebau** [tchiotludo/akhq#527]
Topics list size for tail topics selection seems to be limited by akhq.pagination.page-size (default 25).
When increasing the value for this property we can see all topics in tail dropdown but it also impact topic list in topics details page.

**Comment by tchiotludo** [comment]
hey ! 

fix done here https://github.com/tchiotludo/akhq/pull/516

Please try the `dev` version please

**Comment by jthiebau** [comment]
Okay, thanks, I'll do it.
