### ISSUE TITLE
Add redirect from root path to context-path

### ISSUE THREAD

**Issue by piotrp** [tchiotludo/akhq#530]
When `micronaut.server.context-path` is set add a redirect from `/` to configured context path.

This would allow to make a deployment that is 1) usable with proxies, and 2) easily accessible at internal URL. Currently when I deploy application at http://akhq-server:8080/akhq/ and access http://akhq-server:8080/ URL I get 404 response. It would be great if http://akhq-server:8080/ would redirect me to http://akhq-server:8080/akhq/.

**Comment by abid1998** [comment]
I would like to work on this issue. Can someone help me understand what needs to be done ?

**Comment by tchiotludo** [comment]
Not really sure about how to handle that. 
Micronaut handle this internally and prefix all the route `micronaut.server.context-path`.
And don't find a way quickly to prevent this. 
The best is to look to micronaut here.

**Comment by tchiotludo** [comment]
mostly it was also my concern, if you change the base path, you are behind a reverse proxy IMO.
So the redirect must be set on the reverse proxy

**Comment by piotrp** [comment]
I was thinking about installation looking like this:
* http://akhq-server:8080/akhq/ - address on internal network
* http://public/akhq/ - official address for end-users, on a proxy that aggregates multiple applications under one URL, secured in a way that only end-users have access

Now, telling somebody on my team that "we have AKHQ on akhq-server, port 8080" is not enough for them to access it, unless I also mention the magic path "/akhq/".

Having a working redirect would just make it a bit more flexible and easy to use - purely a quality of life feature for first-time users, as later on browser history helps to fill in the correct address.

**Comment by piotrp** [comment]
This discussion got me thinking whether it would require some convoluted solution, making it not worth the effort, but looks like this case can be easily handled by ErrorController.notFound. @abid1998 are you still interested in working on this, or would you rather do something more interesting? I got some time on my hands so can contribute a solution to my own issue.

**Comment by tchiotludo** [comment]
nice catch @piotrp, the ErrorController can be a nice solution ;) 
Go for it if you have time ;)

**Comment by tobiade** [comment]
@piotrp Gotcha - okay that makes sense. Thanks! 
Also - if you or @abid1998 don't mind, I'll be happy to pick this up too. Trying to get my first ever open source PR out the door :)

**Comment by tchiotludo** [comment]
don't fight for this one ;) there is many more open PR here :smile:

**Comment by tobiade** [comment]
Ha - I've bookmarked a few. This was top of the list 😄 
Thanks - I'll follow up with another.
