### ISSUE TITLE
 ERROR [org.springframework.kafka.KafkaListenerEndpointContainer#0-0-C-1] o.s.c.l.LogAccessor: Consumer exception java.lang.IllegalStateException: This error handler cannot process 'org.apache.kafka.common.errors.SslAuthenticationException's; no record information is available

### ISSUE THREAD

**Issue by akshayubale1** [tchiotludo/akhq#536]
please find below configuration for the springboot

spring.kafka.properties.security.protocol=SSL
spring.kafka.ssl.trust-store-location=file:/var/ssl/private/client.truststore.jks
spring.kafka.ssl.trust-store-password=*****
spring.kafka.ssl.key-store-location=file:/var/ssl/private/client.keystore.jks
spring.kafka.ssl.key-store-password=*****
spring.kafka.ssl.key-password=******

**Comment by tchiotludo** [comment]
I don't see what you are talking about... 
We don't use Spring on AKHQ ...

**Comment by akshayubale1** [comment]
sorry i think i asked the question on wrong window...the thing is i am trying to connect my springboot application to kafka cluster but i am getting the above error..i tried lot of configuration but getting the same error..

**Comment by tchiotludo** [comment]
I couldn't help ;) 
No spring here :)
