### ISSUE TITLE
Feature / Additional filtering for a topic content

### ISSUE THREAD

**Issue by xakassi** [tchiotludo/akhq#537]
Hi, @tchiotludo !

Now when I open a topic, I can filter a topic content using `Search` field and specifying some string there. But it provides an ability only for CONTAINS search. And some our customers would like also to have an ability to use EQUALS and NOT CONTAINS options.

What do you think about this feature?

From my side I can try to implement this, but since I have no any experience with frontend, it can take some time. So maybe someone else is also interested in such feature and can implement it better?

Thanks for the great app 🥇

**Comment by tchiotludo** [comment]
Hi @xakassi, 
 
Nice feature, just need a little bit design on how it will be available on front end. 
You have an idea ? 
Because if we go to this idea, we will need to allow searching in header / key / value with contains / equals / not contains. 
Maybe a list of that ? 

FYI, If you do the backend, I could do the front end for you, np about that !

**Comment by polarising-java** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/57811604/101897210-18b22180-3ba2-11eb-801c-bd4e90aa3317.png)

**Comment by tchiotludo** [comment]
Maybe also another multiple select with search in :
- key
- value
- headers
?

**Comment by polarising-java** [comment]
![image](https://user-images.githubusercontent.com/57811604/101898664-6af44200-3ba4-11eb-88db-2b72ef2463a4.png)

**Comment by tchiotludo** [comment]
seems to be fine

**Comment by polarising-java** [comment]
I have to increase the default size of the box

**Comment by tchiotludo** [comment]
or going to vertical layout like partition to avoid that ?

**Comment by polarising-java** [comment]
![image](https://user-images.githubusercontent.com/57811604/101901175-8e20f080-3ba8-11eb-86b5-27d820d5ea2d.png)

**Comment by tchiotludo** [comment]
perfect :+1:

**Comment by xakassi** [comment]
You can estimate my artistic ability in Paint )))

I think it can look like this:
![Filter design 1](https://user-images.githubusercontent.com/26784806/101906053-cb4da880-3bd1-11eb-9b72-5035d988aefb.png)

Or even like this (ability to specify different filter types for keys, values, headers):
![Filter design 2](https://user-images.githubusercontent.com/26784806/101906151-f46e3900-3bd1-11eb-8185-7bdc82ee3ce4.png)

**Comment by xakassi** [comment]
Oh, I paint something but than reload a page and see that there is a perfect solution already )))
@polarising-java your design is just perfect, I like it, thanks :)

**Comment by polarising-java** [comment]
your solution is more configurable than mine. @tchiotludo  what do you think?

**Comment by xakassi** [comment]
Ok, then I'll still leave these Paint pictures here (I have deleted them before)

The idea with a single filter type for all fields:
![Filter design 1](https://user-images.githubusercontent.com/26784806/101926352-7f5c2d00-3bec-11eb-9eba-e30d6c994fc0.png)

The idea with different filter types for keys, values and headers:
![Filter design 2](https://user-images.githubusercontent.com/26784806/101926447-9c90fb80-3bec-11eb-93ff-728606a504df.png)

**Comment by xakassi** [comment]
Hi, guys!
I have discussed UI with our customers and they said that the last picture from me is preferred. So they would like to have an ability to search specifying different rules and filter types for key, value, header key, header value.
All those filters should combine by AND operator (it seems quite natural).

From backend side it should not be difficult at all, we just need a filters chain: apply first filter rule to all topic content, then apply second filter to the result of the first filter and so on.

@tchiotludo , @polarising-java what do you think?

**Comment by tchiotludo** [comment]
2nd one is fine ! more possibility, just need to have default to contain since it will most use one !

**Comment by polarising-java** [comment]
I think the meaning of "filter=none" is not to apply the filter to the type(key, value, ...) . 
But we can just filter by the type if the type "value" has some value
