### ISSUE TITLE
Unable to utilize REST API

### ISSUE THREAD

**Issue by ritheshrithu** [tchiotludo/akhq#546]
Hi ,

I am trying to use AKHQ rest API for performing operations. But I am unable to generate the Token for the native user.

I have also tried with the JWT token taken from the browser but still getting the error.

Please find the error below.

`Error: Exceeded maxRedirects. Probably stuck in a redirect loop https://abc.com/akhq-sbx/login
`
Please note that I have configured OIDC login as well as Native user login.

Could you please help me here.

Thanks & Regards,
Rithesh S

**Comment by tchiotludo** [comment]
The best is to used basic-auth in order to pass the api from a server.
You just need to add an `Authorization: Basic XXXX` to pass the api. 
 
The jwt is more complex

**Comment by ritheshrithu** [comment]
Hi,

Even after providing the Basic token, still the same error

**Comment by ritheshrithu** [comment]
Also not sure why the error says "Struck in redirect loop"

**Comment by ritheshrithu** [comment]
Hi,

Also could you please confirm do we need to grant any sort of permission for the native user to access APIs like 'topic/read', etc.

Because, I am getting 401 while trying with basic auth.

**Comment by tchiotludo** [comment]
Yes you need to had a group with roles in order to make the api available

**Comment by ritheshrithu** [comment]
Yeah Thanks. Its working now.
