### ISSUE TITLE
Cancel request on filter changed

### ISSUE THREAD

**Issue by tchiotludo** [tchiotludo/akhq#555]
Playing with filter on all page (search, partition, ...) is not canceled like on other page. 

Example, If go to topic data page, choose a partition and change directly the partition will lead to blink with first request, second request when they ended. 
We need to cancel it properly when filter changed.
`this.cancelAxiosRequests()` is not called in this case because we are not chaging page.

**Comment by polarising-java** [comment]
Added a fix on Improve data search #552 branch
