### ISSUE TITLE
OIDC : JWT validation failed, how to increase log level ?

### ISSUE THREAD

**Issue by rhaezebrouck** [tchiotludo/akhq#556]
Hello,

We've enabled security and defined our OIDC provider in application.yml.
AKHQ redirects to the login form, then retrieves the access token and fails token validation with the following message :

`{"message":"Internal Server Error: JWT validation failed","_links":{"self":{"href":"/oauth/callback/oauth2?code=nbg3yJoH8rmWx-cc2s9f3vsSgm5zuKQh3t6odrBpgCk&state=eyJyZWRpcmVjdFVyaSI6Imh0dHBzOi8vYWtocS10ZXN0LWx5ci1rYWZrYS1kZXYuZHBhYXMubHlyZWNvLmNvbS9vYXV0aC9jYWxsYmFjay9vYXV0aDIiLCJub25jZSI6ImE3ZGQ1YmQyLTk5MzItNDFhYi1iODg5LWY2MWQzNTE1OGU1NCJ9","templated":false}},"_embedded":{"stacktrace":{"message":"io.micronaut.security.authentication.AuthenticationException: JWT validation failed\n\tat io.micronaut.security.oauth2.endpoint.authorization.response.DefaultOpenIdAuthorizationResponseHandler.lambda$createAuthenticationResponse$1(DefaultOpenIdAuthorizationResponseHandler.java:172)\n\tat [...]}` 

Looking at a similar micronaut issue, here https://github.com/micronaut-projects/micronaut-security/issues/346#issuecomment-674883825, I understand that we may have further information about the failure by increasing the log level.

However I'm not able to do so. I've tried 2 options : 

- In application.yml
>micronaut:
>  ...
>logger:
>  levels:
>    org.akhq: TRACE
>    io.micronaut.security.authentication: DEBUG
- Through API : strangely, accessing the /loggers endpoint redirects me to /login, other endpoints (/health, /prometheus) work well...
I tried this config to allow anonymous access to all endpoints, with no success:
>endpoints:
>  all:
>    enabled: true
>    sensitive: false
>    port: 8085

How to change the log level when security is enabled ?

**Comment by tchiotludo** [comment]
not really easy since your example yml is not indented ! 

If it can help : 
Logger in configuration must be indented 
```yaml
logger:
  levels:
    org.akhq: TRACE
    io.micronaut.security.authentication: DEBUG
```

logger endpoint is already available without any configuration : 
```bash
curl -i -X POST -H "Content-Type: application/json" \
       -d '{ "configuredLevel": "TRACE" }' \
       http://localhost:8080/loggers/io.micronaut.configuration.security
```

**Comment by rhaezebrouck** [comment]
Thanks for your prompt answer, indeed my indentation is correct in my application.yml but TRACE/DEBUG logs are still not visible.

And curl on /loggers/* returns a 307 REDIRECT to /login

In the meantime we solved our issue with OIDC: we did not properly define the certificate used for the signature inside our OIDC provider. So we won't spend more time for now on increasing log level. 
Thanks!

**Comment by ownyrd** [comment]
Hey @rhaezebrouck can you describe in more detail you certificate definition inside the oidc provider? Facing the same issue ...
