### ISSUE TITLE
Live tail's topic field doesn't search all topics

### ISSUE THREAD

**Issue by ardalan-saberi-etsy** [tchiotludo/akhq#563]
- Expected behavior (my assumption):
I should be able to search all topics when clicking on the topic drop down field
- Actual behavior:
the drop down only loads as many as page-size (I set it to 10 in the screenshot) items and only searches between them. therefore I can't find my topic and won't be able to select it to live tail.
- Workaround(~ish): 
 currently I just set my page-size to 1000.

<img width="1014" alt="Screen Shot 2021-01-15 at 6 23 17 AM" src="https://user-images.githubusercontent.com/74240038/104738812-da58d680-56fa-11eb-91cb-b44ce655accf.png">

**Comment by tchiotludo** [comment]
Hi, it's fixed on the `dev` branch, can you try ?

**Comment by ardalan-saberi-etsy** [comment]
Yes Sir! I'll do it over the weekend and let you know if anything.
