### ISSUE TITLE
Kafka topic size under metrics?

### ISSUE THREAD

**Issue by jessetandor** [tchiotludo/akhq#570]
I'm trying to get the total size of a topic and it seems there isn't a straightforward way to do this via Kafka. Doing a df -h at your logs folder works but I'm looking for something a bit more refined. I realised AKHQ is able to display topic sizes from each node in a cluster. 
Are these values exposed when metrics are enabled..?

**Comment by tchiotludo** [comment]
No, we don't expose metrics from topic throu /metrics endpoint. 
You can reach the api to fetch them or use [this](https://github.com/danielqsj/kafka_exporter)

**Comment by jessetandor** [comment]
Your API section doesn't point to anything though - expected..? Where are the list of akhq endpoints..?

**Comment by tchiotludo** [comment]
Here is the [api docs](https://github.com/tchiotludo/akhq#api), there is a full swagger available on the server like documented here

**Comment by jessetandor** [comment]
Im very confused - Please explain where the swagger .yml file is. 'on the server' ? There is no such file in your project (a far as i can see) and the link's under API's just take me to the general web sites.

**Comment by tchiotludo** [comment]
On your instance : 
* a full documentation is here : http://localhost:8080/api/
* a swagger is generated by server here : http://localhost:8080/swagger/akhq.yml
