### ISSUE TITLE
Extreme slowness loading consumer groups view

### ISSUE THREAD

**Issue by the-rapel** [tchiotludo/akhq#577]
We have been using akhq version 14.1 for a while now and recently upgraded to 16.0.
We have roughly 1K topics on our Kafka cluster, messages traffic is relatively modest. 
We are experiencing significant performance deterioration especially while loading consumer groups.

Attached an example showing slowness loading consumer groups (14.1 vs 16)

https://user-images.githubusercontent.com/78351626/106469256-bdb4f080-64a7-11eb-8585-474858227884.mov

https://user-images.githubusercontent.com/78351626/106469289-c60d2b80-64a7-11eb-8aec-001278fbd391.mov

.
(currently resulted in reverting back to version 14.1)

**Comment by tchiotludo** [comment]
Can you try with `dev` version please ? 
We have a fix on this slowness that will be release soon

**Comment by tchiotludo** [comment]
New release is out, please try and reopen if it's still any issue !
