### ISSUE TITLE
ConfigMap can't read ENV vars for schema registry but can for connection properties

### ISSUE THREAD

**Issue by gbuirel** [tchiotludo/akhq#585]
Hello,

This issue is about how variables are read in the configmap file.

I deploy AKHQ using a deployment, a service and a configmap defined in yaml (could and probably will have to switch to the helm chart in the future)

In my configMap, I use env vars for some credentials, as defined in the following code : 

```data:
  application.yml: |
    [...]
    akhq:
      [...]
      connections:
        kafka-dev:
          properties:
            bootstrap.servers: "my-functionnal-bootstrap-server"
            security.protocol: SSL
            ssl.truststore.location: "/config/ca.jks"
            ssl.truststore.password: ${SSL_DEV_TRUSTSTORE_PASSWORD}
            ssl.keystore.type: "PKCS12"
            ssl.keystore.location: "/config/kafka-hq.p12"
            ssl.keystore.password: ${SSL_DEV_KEYSTORE_PASSWORD}
          schema-registry:
            url: "my-functionnal-schema-registry-url"
            basic-auth-username: ${DEV_BASIC_AUTH_USERNAME}
            basic-auth-password: $DEV_BASIC_AUTH_PASSWORD}
            properties: {}
```

What's weird is that when accessing my akhq instance, I can see I connected to my kafka cluster correctly, but when trying to access the schema-registry, I get an error 

`Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false') at [Source: (sun.net.www.protocol.http.HttpURLConnection$HttpInputStream); line: 1, column: 2]; error code: 50005`

This only happens when I'm using  ${DEV_BASIC_AUTH_USERNAME}, If i put my auth info in plaintext, I get the registry without any issue.
But the var replacement seems to work for my connexion to the bootstrap servers ?

All the env vars are defined in a secret, using the data  field (values are encoded in b64)

This is using the latest tchiotludo/akhq  image.

**Comment by tchiotludo** [comment]
seems to be weird that broker works and not registry. 
As I know to use env var in helm / kubernetes, you need to use the syntax : ` $(SSL_DEV_TRUSTSTORE_PASSWORD)` with `()` and not the `{}`. 
Also I see that : `$DEV_BASIC_AUTH_PASSWORD}` missing `{` in your case !

**Comment by gbuirel** [comment]
The misssing { was a typo on my part when copying it here, I've checked and it wasn't in my config.
I tried using the (), still doesn't work.

My guess would be there is some default values picking up for the bootstrap servers when the ${} doesnt work, and that doesn't exist in the schema-registry properties.

I'll try using the helm chart to incorporate secrets into my config more properly

**Comment by gbuirel** [comment]
Other way around would be to allow reading a file value in AKHQ conf,  something like
`$__file{/etc/secrets/schema-auth/DEV_PASSWORD}`
But I'm not sure on the syntax,  this doesn't seem to work

**Comment by gbuirel** [comment]
Ok so I'm not really sure about why but here's the workaround.

I've twisted my configuration a bit, and when using "stringData" to define DEV_BASIC_AUTH_PASSWORD,  the configmap actually manages to read its value.
But If I define the value in a  data  (so, encoded in b64) field in my secret, it doesn't work.

**Comment by tchiotludo** [comment]
I didn't notice that : (values are encoded in b64) ! 
Sure it will not work and it's not expected and must be a plain password :smile: 

Move to helm charts, there is a secrets in order to handle this ;)

**Comment by gbuirel** [comment]
I agree with using a helm chart as a better solution, but I think there was a misunderstanding.

The actual password is stored in a kubernetes secret, using the  "data" field, just like all the others ENV VARS I use in the configuration  ( for the truststore & keystore password as well) .
Which means I store it encoded in b64.
So I have, in my secret  : 

```
data : 
   DEV_BASIC_AUTH_PASSWORD :  "my password, encoded in b64"
stringData:
   CLEAR_DEV_BASIC_AUTH_PASSWORD:  "my password, in plaintext"
```

And in my container, the actual ENV vars  **both sends back my  plain text password** when I try

`echo $DEV_BASIC_AUTH_PASSWORD`
or
`echo $CLEAR_DEV_BASIC_AUTH_PASSWORD`

The weird part is that one can be read in the conf file, and not the other.
But at this point, when the container reads the ENV var, both seems to be in plaintext, so that's what's weird

**Comment by tchiotludo** [comment]
There must be an interpolation issue here I think. 
Maybe k8 or micronaut interpolate the vars and lose it. 
Maybe go to [Monitoring endpoint](https://github.com/tchiotludo/akhq#monitoring-endpoint), there is a `/env` that will display all the configuration available that can help you to find the issue ?
