### ISSUE TITLE
Feature Request: Optimize the implementation of obtaining the status of connectors

### ISSUE THREAD

**Issue by cobolbaby** [tchiotludo/akhq#586]
https://github.com/tchiotludo/akhq/blob/d9557b03947e183124d9304aa680afcb362f16b0/src/main/java/org/akhq/repositories/ConnectRepository.java#L70-L85

If possible, it is recommended to use the new interface to obtain the connector status in batches. The loop traversal method is time-consuming when dealing with hundreds of connectors.

Batch API:

```
curl -s "http://${CONNECT_URL}/connectors?expand=info&expand=status"
```

**Comment by tchiotludo** [comment]
Thanks @cobolbaby I was not aware of this new method !! 
Done in `dev`
