### ISSUE TITLE
how to config "connection bootstrap" with mechanism oauthbearer

### ISSUE THREAD

**Issue by ericmagna** [tchiotludo/akhq#591]
Hi,

On broker kafka, i put a mechanism oauthbearer with keycloak and it's work fine.

I tried to config AKHQ properties connection with sasl.jaas.config. With different config, the connection fail with an message jwt.

the file application.example.yml don't implement a config with sasl.mechanism: OAUTHBEARER.

can you help me to config akhd connect to bootstrap with mechanism OAUTHBEARER ?

Thank you for you help.

**Comment by tchiotludo** [comment]
Really don't know how it works (don't even know it's was possible). 
Do you have configuration for a consumer or producer in java ? 
It must be the same

**Comment by ericmagna** [comment]
i just configure broker kafka to user oauth2 with keycloak. 

I have done multiple tests by producing and consuming messages from the kafka-topic.sh binary with success. 
I see the creation of tokens with keycloak without problem

after these tests, i try to configure akhq to communicate with kafka brokers in oauthbearer mode without success.

In my opinion, I am not far from the solution but I cannot find the right configuration. 

some of you may have encountered this problem to perform a configuration with an OAUTHBEARER mechanism on AKHQ.
 

Nevertheless if you have an idea, I am very interested. If I can get this solution to work, I will suggest including the configuration in the sample application.yml file.
Nevertheless if you have an idea, I am very interested. If I can get this solution to work, I will suggest including the configuration in the sample file application.example.yml.

thank for you help.

**Config broker kafka** 
listeners=SASL_PLAINTEXT://172.17.0.4:9093,SASL_SSL://172.17.0.4:9091,CLIENT://172.17.0.4:9094
advertised.listeners=SASL_PLAINTEXT://mommo01-1.ci.hawai.recouv:9093,SASL_SSL://mommo01-1.ci.hawai.recouv:9091,CLIENT://mommo01-1.ci.hawai.recouv:9094
sasl.enabled.mechanisms=OAUTHBEARER
sasl.mechanism.inter.broker.protocol=OAUTHBEARER
inter.broker.listener.name=CLIENT
listener.security.protocol.map=PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL,CLIENT:SASL_PLAINTEXT,CLIENT:SASL_PLAINTEXT

listener.name.client.oauthbearer.sasl.login.callback.handler.class=io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler
listener.name.client.oauthbearer.sasl.server.callback.handler.class=io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler



listener.name.client.oauthbearer.sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
 oauth.valid.issuer.uri="https://<xxxxxxxx>/auth/realms/sandbox_kafka" \
 oauth.jwks.endpoint.uri="https://<xxxxxxxx>/auth/realms/sandbox_kafka/protocol/openid-connect/certs" \
 oauth.username.claim="preferred_username"  \
 oauth.jwks.refresh.seconds="600" \
 oauth.jwks.expiry.seconds="720" \
 oauth.client.id="kafka-broker" \
 oauth.client.secret="<xxxxxxxx>" \
 oauth.ssl.truststore.location="kafka.server.truststore.jks" \
 oauth.ssl.truststore.password="<xxxxxxxx>" \
 oauth.ssl.truststore.type="jks" \
 oauth.ssl.endpoint_identification_algorithm="" \
 oauth.token.endpoint.uri="https://<xxxxxxxx>/auth/realms/sandbox_kafka/protocol/openid-connect/token";


**config jaas broker server** 
sasl_plaintext.KafkaServer {
           org.apache.kafka.common.security.plain.PlainLoginModule required
           user_kafka="xxxxxxxx"
           username="kafka"
           password="xxxxxxxx";
           };
sasl_ssl.KafkaServer {
           org.apache.kafka.common.security.plain.PlainLoginModule required
           user_kafka="xxxxxxxx"
           username="kafka"
           password="xxxxxxxx";
           };
Client {
       org.apache.zookeeper.server.auth.DigestLoginModule required
       username="kafka"
       password="xxxxxxxx";

       org.apache.kafka.common.security.plain.PlainLoginModule required
       username="kafka"
       password="xxxxxxxx";
};
KafkaClient {
           org.apache.kafka.common.security.plain.PlainLoginModule required
           username="kafka"
           password="xxxxxxxx";

           org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required
           unsecuredLoginStringClaim_sub="alice";
           };
KafkaServer {
           org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required
           LoginStringClaim_sub="kafka-broker";
};

**Config AKHQ**
  # list of kafka cluster available for akhq
  connections:
    my-cluster-plain-text: # url friendly name for the cluster (letter, number, _, -, ... dot are not allowed here)
      properties: # standard kafka properties (optional)
        bootstrap.servers: "172.17.0.4:9094,172.17.0.5:9094"
        sasl.jaas.config: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required unsecuredLoginStringClaim_sub="alice";
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: OAUTHBEARER

**Config kafka broker for producer (file producer.properties)**
bootstrap.servers=mommo01-1.ci.hawai.recouv:9094

# specify the compression codec for all data generated: none, gzip, snappy, lz4, zstd
compression.type=none

# name of the partitioner class for partitioning events; default partition spreads data randomly
#partitioner.class=

# the maximum amount of time the client will wait for the response of a request
#request.timeout.ms=

# how long `KafkaProducer.send` and `KafkaProducer.partitionsFor` will block for
#max.block.ms=

# the producer will wait for up to the given delay to allow other records to be sent so that the sends can be batched together
#linger.ms=

# the maximum size of a request in bytes
#max.request.size=

# the default batch size in bytes when batching multiple records sent to a partition
#batch.size=

# the total bytes of memory the producer can use to buffer records waiting to be sent to the server
#buffer.memory=

sasl.login.callback.handler.class=io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler

sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
 oauth.valid.issuer.uri="https://<xxxxxxxxxxxx>/auth/realms/sandbox_kafka" \
 oauth.jwks.endpoint.uri="https://<xxxxxxxxxxxx>/auth/realms/sandbox_kafka/protocol/openid-connect/certs" \
 oauth.username.claim="preferred_username"  \
 oauth.client.id="kafka-producer-client" \
 oauth.client.secret="<xxxxxxxxxxxx>" \
 oauth.ssl.truststore.location="kafka.server.truststore.jks" \
 oauth.ssl.truststore.password="<xxxxxxxxxxxx>" \
 oauth.ssl.truststore.type="jks" \
 oauth.ssl.endpoint_identification_algorithm="" \
 oauth.token.endpoint.uri="https://<xxxxxxxxxxxx>/auth/realms/sandbox_kafka/protocol/openid-connect/token";


security.protocol=SASL_PLAINTEXT
sasl.mechanism=OAUTHBEARER

**Comment by tchiotludo** [comment]
Can you format the configuration please ? it's unreadable ;)
One thing I see : `io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler`, this class is not available on AKHQ, maybe a missing deps for your use case ? 
Also can you give me the configuration for `kafka-topic.sh` please ? It will be almost the same for akhq I think.

**Comment by ericmagna** [comment]
Sorry you are right the copy paste is not readable. I am attaching the elements to you (4 files).

servers.properties and kafka_jaas is config for kafka broker. application.yml is for akhq and producer.properties is a sample for test to produce message in kafka.

I use the strimzi libraries in version 0.16 to establish a connection between kafka broker and keycloak..

If I understand your remark, I will have to integrate the dependencies of the strimzi libraries into akhq. In this case, what is the best practice to integrate the strimzi library in akhq ?
Thank you for your answers.

Test case topics
Create a topic oauth2-demo-topic on broker kafka
bin/kafka-topics.sh \
  --zookeeper momzoo03-1.ci.hawai.recouv:2181 \
  --create \
  --topic oauth2-demo-topic \
  --partitions 1 \
  --replication-factor 1

produce message 
./bin/kafka-console-producer.sh --broker-list mommo01-1.ci.hawai.recouv:9094 --topic oauth2-demo-topic --producer.config ./config/producer.properties

consume message
 ./bin/kafka-console-consumer.sh --bootstrap-server mommo01-1.ci.hawai.recouv:9094 --topic oauth2-demo-topic --from-beginning --consumer.config ./config/consumer.properties

[producer.properties.txt](https://github.com/tchiotludo/akhq/files/5940019/producer.properties.txt)
 
[applications.yml.txt](https://github.com/tchiotludo/akhq/files/5940005/applications.yml.txt)
[kafka_jaas.properties.txt](https://github.com/tchiotludo/akhq/files/5940006/kafka_jaas.properties.txt)
[servers.properties.txt](https://github.com/tchiotludo/akhq/files/5940007/servers.properties.txt)

**Comment by ericmagna** [comment]
if I have to integrate the strimzi libraries, I think I have to modify the gradle.properties file to include these libraries. Since I don't know the gradle configuration, could you help me modify this file to include strimzi libraries. 

Thanking you.

**Comment by tchiotludo** [comment]
Just add `implementation group: 'io.strimzi', name: 'kafka-oauth-client', version: '0.7.0'` on `gradle.properties` and it will be good I think

**Comment by ericmagna** [comment]
Thank.

i add this lines :
    // strimzi
    // https://mvnrepository.com/artifact/io.strimzi/kafka-oauth-common
    implementation group: 'io.strimzi', name: 'kafka-oauth-common', version: '0.7.0'
    // https://mvnrepository.com/artifact/io.strimzi/kafka-oauth-client
    implementation group: 'io.strimzi', name: 'kafka-oauth-client', version: '0.7.0'
    //implementation group: "io.strimzi", name: "kafka-oauth-common"
    //implementation group: "io.strimzi", name: "kafka-oauth-client"
and i run ./gradlew shadowJar to générate akhq-0.1-all.jar.

I configured with the settings for a token management with keycloak and relaunched akhq.
I see a connection with the kafka broker and a connection with the keycloak / oauth. The url remains blocked, I continue to search. Thanks for your help, I'll keep you posted.

**Comment by tchiotludo** [comment]
thanks :+1: 
If you have success, create a PR with gradle dependencies & some docs ;)

**Comment by ericmagna** [comment]
No success . The analysis shows that akhq does not call the broker kafka contrary to what I wrote. The jar contains well the strimzi libraries and the configuration of the application.yml file does not put an error. Access via the browser does not return anything and I have nothing in the traces. To activate the debug mode by the curl it is not possible because it does not respond. I will set up a logback.yml to try and get some information.

**Comment by ericmagna** [comment]
i found the right configuration.

clone the last version (0.17).
modify build.gradle to add dependencies (implementation)
_/**********************************************************************************************************************\
 * Dependencies
 **********************************************************************************************************************/
dependencies {
    // strimzi
    // https://mvnrepository.com/artifact/io.strimzi/kafka-oauth-common
    implementation group: 'io.strimzi', name: 'kafka-oauth-common', version: '0.7.0'
    // https://mvnrepository.com/artifact/io.strimzi/kafka-oauth-client
    implementation group: 'io.strimzi', name: 'kafka-oauth-client', version: '0.7.0'_

and launch gradlew shadowJar to get an jar include librairie strimzi.

modify application.yml like that 
       _bootstrap.servers: "<broker kafka1>:9094,<broker kafka2>:9094"
        sasl.jaas.config: org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required oauth.valid.issuer.uri="https://<url keycloak>/auth/realms/sandbox_kafka" oauth.jwks.endpoint.uri="https://<url keycloak>/auth/realms/sandbox_kafka/protocol/openid-connect/certs" oauth.username.claim="preferred_username" oauth.client.id="kafka-producer-client" oauth.client.secret="<secret>" oauth.ssl.truststore.location="kafka.server.truststore.jks" oauth.ssl.truststore.password="xxxxx" oauth.ssl.truststore.type="jks" oauth.ssl.endpoint_identification_algorithm="" oauth.token.endpoint.uri="https://<url keycloak>/auth/realms/sandbox_kafka/protocol/openid-connect/token";
        sasl.login.callback.handler.class: io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler
        security.protocol: SASL_PLAINTEXT
        sasl.mechanism: OAUTHBEARER_

Of course it is necessary to configure the kafka brokers in oauthbearer with the strimzi library.

I haven't finished yet because there are still checks to be done.
when done i will suggest an addition in the readme.md file.

thank.

**Comment by tchiotludo** [comment]
Maybe a PR with the updated gradle.build, we can include the libs on the official package to simplify onboarding I think ;)

**Comment by kc89rst** [comment]
It works, thanks for the hint

**Comment by ericmagna** [comment]
PR created with modify README.md

**Comment by ericmagna** [comment]
![PR 615](https://github.com/tchiotludo/akhq/pull/615)
