### ISSUE TITLE
Issues setting up OIDC for Okta

### ISSUE THREAD

**Issue by nishantyedla** [tchiotludo/akhq#597]
Hello,

This is probably more of Micronaut or Okta related issue i'm facing just wanted to see if you got this to work or you can identify if I'm doing something wrong. 

I'm trying to setup oidc with Okta, had tested this on developer version of Okta for local testing and in our org as well on k8s. This is the error I see:
`message":"Internal Server Error: Failed to retrieve OpenID configuration for okta"`

The setup I have is AKHQ to manage our MSK clusters on AWS and basic auth works just fine. Attaching the docker-compose file & logs. Any help would be great!
[akhq.zip](https://github.com/tchiotludo/akhq/files/5954844/akhq.zip)

**Comment by tchiotludo** [comment]
maybe we need to configure this one : `micronaut.security.oauth2.clients.*.openid.configuration-path` ? [see here](https://micronaut-projects.github.io/micronaut-security/latest/guide/#io.micronaut.security.oauth2.configuration.OauthClientConfigurationProperties$OpenIdClientConfigurationProperties) 
Micronaut need to have a well-know configuration and seems that is configurable on [okta](https://developer.okta.com/docs/concepts/auth-servers/#org-authorization-server-discovery-endpoints)

Just some though, I don't know anything on Okta

**Comment by nishantyedla** [comment]
Thank you for looking into it! Yea I've doubted that first but micronaut seems to have a default value set for that path "/.well-known/openid-configuration" which is the path my okta account already responds to. For sanity i tried setting that no luck :(
I've opened a ticket with okta as well to see if they can point out something.

**Comment by nishantyedla** [comment]
I've reached out to Okta and seem to not have a solid answer for this either anyways ldap is working for me so that should be good. 

But wanted to ask what does the live tail option offer on the console?
![image](https://user-images.githubusercontent.com/42752634/107669095-62c98900-6c5f-11eb-9de9-9343e8dde7ea.png)

And is it possible to set cluster level access? right now we are monitoring 4 MSK clusters and i want to give more permissions on the lower env clusters to devs so they can manage from console and restrict to just read on prod.

**Comment by tchiotludo** [comment]
good to know you have a workaround :) 

And the response is not for now for differents group for each cluster, it will be certainly the next features, release but I don't know when, PR are welcome :+1:
