### ISSUE TITLE
LDAP configuration groups [AKHQ]

### ISSUE THREAD

**Issue by Adel-Akbi** [tchiotludo/akhq#598]
Hi,

I am able to login to AKHQ using a specefic user that I declare like below for example : 

> 
    ldap:

      users:
        - username: ADMIN207 # ldap user id
          groups: # Akhq groups list
            - admin

This prove that the connection to the LDAP is establishedwith success, but it's not what I need. I would like to have a group from my LDAP that contains this user and also make the others users of the group (GRP-AKHQ) can access to AKHQ... so, my problem is that I am unable to put the name of the group that this user is into... like that : 

> 

    ldap: 
       groups:
          - name: GRP-AKHQ    
            groups: # Akhq groups list
                - admin

I used both declaration of the LDAP groups... but still have nothing 👎 : 

 

> 

   ldap: 

      group:
          GRP-AKHQ:
             groups:
                 - admin

 I got nothing from the UI no error message (it says nothing -> e.g : the smal red panel of username or password wrong doesn't appear)...

Also, I added the parameter `filter: "member={0}"` but my AKHQ stopped running seems that it doesn't like it...
 
To clarify, when I try to login : 
![image](https://user-images.githubusercontent.com/45661981/107657774-c2d32600-6c85-11eb-9ad0-e912e012df97.png)

I get directely a refreshed page, and it remove the entire credentials that I have taped before without any error pop-up  : 

![image](https://user-images.githubusercontent.com/45661981/107658087-16457400-6c86-11eb-9ed3-f25db591463d.png)

How can I solve this pls?

**Comment by Adel-Akbi** [comment]
To clarify, when I try to login : 
![image](https://user-images.githubusercontent.com/45661981/107657774-c2d32600-6c85-11eb-9ad0-e912e012df97.png)

I get directely a refreshed page, and it remove the entire credentials that I have taped before without any error pop-up  : 

![image](https://user-images.githubusercontent.com/45661981/107658087-16457400-6c86-11eb-9ed3-f25db591463d.png)

**Comment by tchiotludo** [comment]
Can you try with debug enable like mention on README ? 

```bash 
curl -i -X POST -H "Content-Type: application/json" \
       -d '{ "configuredLevel": "TRACE" }' \
       http://localhost:8081/loggers/io.micronaut.configuration.security
````

And send me the log please ?

**Comment by Adel-Akbi** [comment]
@tchiotludo ou est-ce que je peux t'envoyer les logs ? nous sommes dans le secteur bancaire donc les données sont assez confidentielles...

**Comment by tchiotludo** [comment]
bien sur : tchiot.ludo@gmail.com
