### ISSUE TITLE
Schema Registry details of the subject 

### ISSUE THREAD

**Issue by PLarboulette** [tchiotludo/akhq#599]
Hello, 

Version 0.17.0 

I'm not sure it's a bug ... 

Scenario : 

- Schema registry screen, search by subject. 
- 2 results, with identical id for the schema 
- when I click on "details" of the second line, I come across the details for the subject of the first line.
- If I modify the URL to go to the good subject (URL for subject of the second line), it works. 

In my case, the two subjects use the same version for the schema, so there is no problem in the displayed information. but think if we have two versions different ? 

Thanks

**Comment by tchiotludo** [comment]
I can reproduce easily !  
Will dig or PR are welcome ! 
Thanks for the report

**Comment by tchiotludo** [comment]
done on dev branch ;)
