### ISSUE TITLE
Live tail only showing first message in a burst- search shows all

### ISSUE THREAD

**Issue by fecundf** [tchiotludo/akhq#600]
Been using akhq for a few hours now, and I notice that "Live Tail" only shows the first of several messages in a burst. Examining the topic shows all messages. I expect the live tail to show all messages same as search does.

Below are screenshots showing the live tail for a few test events sent together with 0,1,2,3, then a second pause, then events a,b,c. Note that the live tail only shows the '0' and 'a' events but the topic search shows all 0-3 and a-c

![image](https://user-images.githubusercontent.com/317592/107788872-e7c7a780-6d1e-11eb-824d-6e1fcd77a2dc.png)

![image](https://user-images.githubusercontent.com/317592/107789330-72a8a200-6d1f-11eb-8a8b-b43a927e4645.png)

I'm using the librdkafka library via a thin Perl wrapper, and wrote this for for the above

    $topic->produce(0,0,sprintf('{"payload":"%d"}',$_),sprintf('{"key":"%d"}',$_) ) for 0..3;
    sleep 1;
    $topic->produce(0,0,sprintf('{"payload":"%s"}',$_),sprintf('{"key":"%s"}',$_) ) for 'a'..'c';

I'm using a local Docker Kafka server node for this test on the same host as the client, no network issues, and akhq.jar console shows no log messages at all.

**Comment by tchiotludo** [comment]
There is fix on last version about that.
What is the version you are using ?

**Comment by fecundf** [comment]
How do I find the akhq version? I don't see it in the logs, not sure how to get it from the command-line or the web client.

**Comment by tchiotludo** [comment]
The version is directly on the ui : 
![image](https://user-images.githubusercontent.com/2064609/107985742-f5a15500-6fca-11eb-90c6-e1a976c15e20.png)

**Comment by fecundf** [comment]
Oh, I was also running a"Snapshot" release. Downloaded a little over a week ago, `ls -l akhq.jar` shows size 42680756 bytes, written Feb  5 17:06. Let's try with this [tagged 0.17 release](https://github.com/tchiotludo/akhq/releases/tag/0.17.0) - those are the same release- are the assets at https://github.com/tchiotludo/akhq/releases/tag/0.17.0 up-to-date? They show "Snapshot" in the UI.

I also tried the previous release, from https://github.com/tchiotludo/akhq/releases/download/0.16.0/akhq.jar - also has the same issue, and it also reports itself as "Snapshot" in the UI

**Comment by tchiotludo** [comment]
@fecundf : can you have a reproduction method with a local cluster maybe (docker-compose files) ? 
I really can't reproduce on my side. 
Reopen if you have a way for us to work on that

**Comment by denisgillespie** [comment]
Hello @fecundf  @tchiotludo ,
I have also come across this issue. Can it be reopened?

It appears to have stopped working correctly after version 0.14.0. 
I have attached a zip file containing a docker-compose file and a README with instructions to reproduce.

[recreate-akhq-live-tail-issue.zip](https://github.com/tchiotludo/akhq/files/6524228/recreate-akhq-live-tail-issue.zip)

![live-tail-screenshot](https://user-images.githubusercontent.com/56024737/119177059-b409c580-ba63-11eb-9b3d-c98e87b7257c.png)

![topic-1-all-messages](https://user-images.githubusercontent.com/56024737/119177084-b8ce7980-ba63-11eb-958e-2ff8d168dd17.png)

**Comment by tchiotludo** [comment]
Hi @denisgillespie , have you try with last dev version ? There is a bug fix from micronaut

**Comment by denisgillespie** [comment]
> Hi @denisgillespie , have you try with last dev version ? There is a bug fix from micronaut

No I haven't tried the dev version yet. I will check that out thanks

**Comment by denisgillespie** [comment]
Hi @tchiotludo just to let you know, I just tried pulling the latest dev image and unfortunately it still appears to be not working as expected.

**Comment by tchiotludo** [comment]
you can make a new try, live tail was not working at all
