### ISSUE TITLE
Openshift error::Couldn't find any clusters on your configuration file, please ensure that the configuration file is loaded correctly

### ISSUE THREAD

**Issue by skhamba71** [tchiotludo/akhq#604]
2021-02-15 13:45:17,633 INFO  main       i.m.c.e.DefaultEnvironment Established active environments: [k8s, cloud]
--
  | 2021-02-15 13:45:19,275 INFO  main       i.m.runtime.Micronaut      Startup completed in 1740ms. Server Running: http://akhqweb-4-9hmqb:8080
  | 2021-02-15 13:46:59,560 ERROR pGroup-1-2 .s.n.RoutingInBoundHandler Unexpected error occurred: Couldn't find any clusters on your configuration file, please ensure that the configuration file is loaded correctly
  | java.lang.IllegalArgumentException: Couldn't find any clusters on your configuration file, please ensure that the configuration file is loaded correctly
  | at org.akhq.middlewares.KafkaWrapperFilter.doFilter(KafkaWrapperFilter.java:25)
  | at io.micronaut.http.filter.HttpServerFilter.doFilter(HttpServerFilter.java:48)
  | at io.micronaut.http.server.netty.RoutingInBoundHandler$4.proceed(RoutingInBoundHandler.java:1835)
  | at io.micronaut.http.server.context.ServerRequestContextFilter.doFilter(ServerRequestContextFilter.java:57)
  | at io.micronaut.http.filter.HttpServerFilter.doFilter(HttpServerFilter.java:48)

**Comment by tchiotludo** [comment]
Sorry, didn't see this one ... 
Just mean that your configuration files is not valid
