### ISSUE TITLE
Trying out the docker-compose demo, I get errors with Zookeeper

### ISSUE THREAD

**Issue by mirosval** [tchiotludo/akhq#608]
I seems Zookeeper is not able to start because it can't use the disk?

```
org.apache.zookeeper.server.persistence.FileTxnSnapLog$DatadirException: Unable to create data directory /var/lib/zookeeper/log/version-2
zookeeper_1        |    at org.apache.zookeeper.server.persistence.FileTxnSnapLog.<init>(FileTxnSnapLog.java:127)
zookeeper_1        |    at org.apache.zookeeper.server.ZooKeeperServerMain.runFromConfig(ZooKeeperServerMain.java:124)
zookeeper_1        |    at org.apache.zookeeper.server.ZooKeeperServerMain.initializeAndRun(ZooKeeperServerMain.java:106)
zookeeper_1        |    at org.apache.zookeeper.server.ZooKeeperServerMain.main(ZooKeeperServerMain.java:64)
zookeeper_1        |    at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:128)
zookeeper_1        |    at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:82)
zookeeper_1        | Unable to access datadir, exiting abnormally
```

I have just followed the instructions in the readme and started this with `docker-compose up`.

I'm on Intel Mac Big Sur with Docker 3.1.0

**Comment by seagullmouse** [comment]
Me too

**Comment by tchiotludo** [comment]
Also on Intel Mac Big Sur ?

**Comment by seagullmouse** [comment]
I've worked around this for now by mapping the volume to my machine, e.g.

```
volumes:
      - /Users/xxx/Documents/dev/volumes/zookeeper/log/version-2/:/var/lib/zookeeper/log/version-2
      - /Users/xxx/Documents/dev/volumes/zookeeper/data/version-2/:/var/lib/zookeeper/data/version-2
```

**Comment by tchiotludo** [comment]
seems to be related to docker issue not akhq, reopen if needed

**Comment by fabiank0** [comment]
> I've worked around this for now by mapping the volume to my machine, e.g.
> 
> ```
> volumes:
>       - /Users/xxx/Documents/dev/volumes/zookeeper/log/version-2/:/var/lib/zookeeper/log/version-2
>       - /Users/xxx/Documents/dev/volumes/zookeeper/data/version-2/:/var/lib/zookeeper/data/version-2
> ```

Thanks, 1.5 yrs later and I ran into the same issue, after zookeeper suddenly stopped working for me. This fixed it for me.

**Comment by shaojun** [comment]
I had the same problem in a `Ubuntu 20.04.4 LTS x86` cloud server, with running the docker `image: confluentinc/cp-zookeeper:7.0.1`, while, in another same spec cloud server, then there's no such a problem, and both of them have no volumes mapping.

**Comment by antoniodimariano** [comment]
I am facing the same issue with an M1 and the `image: confluentinc/cp-zookeeper:latest.arm64` 
I tried to set the volumes as [here](https://github.com/tchiotludo/akhq/issues/608#issuecomment-785796511)
but I got this error 
```
does not match any of the regexes: '^[a-zA-Z0-9._-]+$'
```
I also tried to create the `var/lib/zookeeper/log/version-2` folder locally, granting it 1000:1000, but nothing has changed, and still unable to start zookeeper. 
```
org.apache.zookeeper.server.persistence.FileTxnSnapLog$DatadirException: Cannot write to snap directory /var/lib/zookeeper/data/version-2
```

**Comment by antoniodimariano** [comment]
@pebabion , yes I did it. Same issue.
