### ISSUE TITLE
Issues connecting to kafka connect v<2.3

### ISSUE THREAD

**Issue by dberardo** [tchiotludo/akhq#610]
Hello, 

i am using the latest version of the akhq docker image: tchiotludo/akhq:latest

When i click on the "Connects" section of the GUI the following error message displays: "the end point you requested requires Kafka-Connect 2.3.0+"

However, i am using kafka-connect 2.1.0 so i wonder why is that so?

The Connects section use to work just fine under: tchiotludo/akhq:0.16

**Comment by tchiotludo** [comment]
This is normal, I use on the last version a new endpoint from kafka connect.
This have a huge performance impact for large cluster, so it need to be done.
The kafka connect 2.3 was almost 2 years ago, so you need to update your connect server to use the last version

**Comment by dberardo** [comment]
ok, thanks for saying this. Maybe a note in the Doc would be good.

by the way, currently i am using this implementation of kafka-connect (to be honest i dont know about others): 

confluentinc/cp-kafka-connect:5.1.0 (which implements connect 2.1)

and this seems to work just fine.

When i try to upgrade to the next major version, which should include connect 2.3:

confluentinc/cp-kafka-connect:6.1.0

i cannot manage to get the connect replicated cluster run again using the exact same environmental variables / configuration as in the previous version.

the official documentation of this image is ridiculous, and the error log not really useful.

How have you managed to setup a connect 2.3 cluster? are you using the same implementation above?

**Comment by tchiotludo** [comment]
for the doc, PR are welcome ;) 

Personally, to be honest, I don't use connect at all :smile: 
I implement it on akhq because ask for it only :laughing: 
So I couldn't help you about migration, sorry ...

**Comment by dberardo** [comment]
ahah i see. Let me see if i can find some time during the week end to make a PR.

thanks for including connect for people like us :D

i will try to post my issue with the image version upgrade somewhere else
