### ISSUE TITLE
Using Kafka Transactions seems to be confusing the topic size and lag of consumer groups

### ISSUE THREAD

**Issue by jochenhebbrecht** [tchiotludo/akhq#613]
Hi,

I'm currently using AKHQ 0.16.0 and I'm using Kafka transactions from within Spring Kafka. I've noticed 2 strange things in AKHQ:

* the topic size in AKHQ is higher than the actual messages on my topic. In my case, AKHQ states `187` messages, but using this command, I get up to `99` (which is the correct number):
```
$ ./bin/kafka-console-consumer.sh --bootstrap-server localhost:9094 --topic my-toic --from-beginning
...
Processed a total of 99 messages
```
* the lag of a consumer group is higher then the actual lag. In my case, AKHQ states that the lag is `16`, but the actual lag is `0` (which is the correct number).

More information on the internals of Kafka transactions can be found here: https://www.confluent.io/blog/transactions-apache-kafka/

Unfortunately, I have no clue what's causing this, but I was wondering if you are aware of this? And would there be a potential way to solve this? I can query some things on my side to give you more details if you want?

Thanks for looking into this!
Jochen

**Comment by tchiotludo** [comment]
For the consumer lag, it can do nothing about that, Kafka api don't allow me to have the message count with transaction. 
Kafka transaction commit a last offset meaning COMMIT, and this one is never read by the kafka consumer... 
So I can't do anything about that. 

For the number of records, the same things apply, the offset position contains those transactions never read by a consumer. 

Sorry but I could correct this and I think kafka API will never changed here

**Comment by JochenHebbrecht-TomTom** [comment]
Hi @tchiotludo ,

Wow, you were fast in providing feedback yesterday :-).
Thanks for the additional information. I see other viewers (such as Kafdrop for example) experience the same behavior. It's unfortunate you can't get more data using the Kafka API.

It's OK to close this issue. :+1: 

Jochen

**Comment by jochenhebbrecht** [comment]
Hi @tchiotludo ,

Wow, you were very fast in providing feedback yesterday :-).
Thanks for the additional information. I see other viewers (such as Kafdrop) experience the same behavior. It's unfortunate you can't get more appropriate data using the Kafka API.

I'm OK to close this ticket :+1: 

Jochen
