### ISSUE TITLE
Feature-request Helm: Add abbility for service-labels

### ISSUE THREAD

**Issue by flyinggecko** [tchiotludo/akhq#624]
This is a feature-request to make it possible to add labels to the created service. 
This is useful if for example use linkerd and want to mirror the service into another k8s-cluster.

**Comment by tchiotludo** [comment]
For sure, just drop a PR [here](https://github.com/tchiotludo/akhq/blob/master/helm/akhq/templates/service.yaml) from master branch ;)

**Comment by flyinggecko** [comment]
I will do that ;)
