### ISSUE TITLE
Add scrolling/filtering to clusters list

### ISSUE THREAD

**Issue by arthurh4** [tchiotludo/akhq#635]
Hello,

We are managing a large number of small clusters (25+) and centralizing its management using akHQ, some of our users have trouble finding all the clusters as the cluster list panels in the UI are truncated (depending on screen resolution) without any scrolling/filtering option.

I could not find any option to turn on any of this feature in akHQ, could this be implemented ?

Thanks a lot

**Comment by tchiotludo** [comment]
There is no option for now, but feel free to add a PR with that !
Must be a simple overflow: scroll somewhere in the css :smile:

**Comment by clain23** [comment]
We are still experiencing this issue on 0.18.

**Comment by clain23** [comment]
I can repro on 0.19.0 too :(
