### ISSUE TITLE
Handle special topic like Schema Registry and __consumer_offsets and display data

### ISSUE THREAD

**Issue by PLarboulette** [tchiotludo/akhq#654]
Hello, 

I think I find a strange behavior in the topic list records. When I want to read the __consumer_offsets topic, the consumer tries to use the Schema Registry to deserialize key and values (probably because both is in a binary format ?) 

This behavior results in many calls on the Registry, with 404 response because the id used to get the schema doesn't exist (obviously) 

I think I can fix it, it's just to know if you are already anything in progress about this :) 

Have a nice day !

**Comment by tchiotludo** [comment]
Hello, 
The logic to trying to deserialize avro is here : 
https://github.com/tchiotludo/akhq/blob/594cda9a82e64028ff34780706740f98c3ea8054/src/main/java/org/akhq/models/Record.java#L156
It seems that record in `__consumer_offsets` start with magic bytes (really weird I don't see it before). 
No work is started here, the better for this topic will be deserialize to json this topic (to expose kafka internal to help people understand).
The whole logic is [here](https://github.com/apache/kafka/blob/trunk/core/src/main/scala/kafka/tools/DumpLogSegments.scala#L452) I think. 
But maybe it's too much work :thinking:

**Comment by LiamClarkeNZ** [comment]
Hi @tchiotludo,

Consumer offsets uses its own special serialization format, there's a formatter accessible if you have Kafka jars on the classpath, it was intended for cli usage with `kafka-consumer.sh` but could make life easier here perhaps?

`kafka.coordinator.group.GroupMetadataManager$OffsetsMessageFormatter`

**Comment by timtebeek** [comment]
Not sure it correctly does all it should in all circumstances, but I just opened https://github.com/tchiotludo/akhq/pull/856 to improve upon how `__consumer_offsets` records are displayed.
