### ISSUE TITLE
Connector notification error

### ISSUE THREAD

**Issue by fabiofilz** [tchiotludo/akhq#655]
Hi support team,

Would it be possible to add a notification feature when a Connector stop working? It could be through a webhook so a notification could be sent to a Teams channel.

We are running over 200 connectors and at the moment we don't have a way to automatise any alert.

It would be good if we could:
- have N webhooks
- Associate a connector to a specific webhook
- save the information that a notification was sent so AKHQ won't send a new notification about the same error again.

Thank you.
Fabio

**Comment by tchiotludo** [comment]
Hi @fabiofilz,

Thanks for the suggestion but it seems out of scope of akhq. 
AKHQ is a GUI / viewver not a proactive monitoring tool. 
I suggest to use prometheus with an exporter for [that](https://github.com/vinted/kafka-connect-exporter) !
