### ISSUE TITLE
AKHQ does not start on loging url

### ISSUE THREAD

**Issue by thedje** [tchiotludo/akhq#658]
Hello
I wanted to set up akhq so that the basic url would be the loging page: http://my_host:8081/ui/login
But when I type the url: http://my_host:8081, I arrive on the page: http://my_host:8081/ui/kafka-prod-design/topic
How to get to the right page?
I'm attaching my conf file.
[application.txt](https://github.com/tchiotludo/akhq/files/6271609/application.txt)

**Comment by tchiotludo** [comment]
Hello, 

There is a typo here :  ` defaurl:ult-group: admin`.
And if you want a login page directly (no anonymous user) , you need to use `default-group: no-roles`

**Comment by thedje** [comment]
Yes, it is working now.
Thank you
