### ISSUE TITLE
Read-only mode does not work

### ISSUE THREAD

**Issue by thedje** [tchiotludo/akhq#661]
Hello,
I use akhq version 0.16.0.
I created a group reader.
          
 And I set this group by default to the ldap connection.

I try to connect with the user 70091m which is not admin. And I stay on the loging pattern.
I thought I could read the topics.

In the log, I have no error:
akhq    | 2021-04-08 14:27:30,210 DEBUG 1-thread-2 LdapAuthenticationProvider Starting authentication with configuration [default]
akhq    | 2021-04-08 14:27:30,210 DEBUG 1-thread-2 LdapAuthenticationProvider Attempting to initialize manager context
akhq    | 2021-04-08 14:27:30,967 DEBUG 1-thread-2 LdapAuthenticationProvider Manager context initialized successfully
akhq    | 2021-04-08 14:27:30,967 DEBUG 1-thread-2 LdapAuthenticationProvider Attempting to authenticate with user [70091m]
akhq    | 2021-04-08 14:27:30,980 DEBUG 1-thread-2 LdapAuthenticationProvider User found in context [uid=70091m,ou=Utilisateurs,dc=maif,dc=local]. Attempting to bind.
akhq    | 2021-04-08 14:27:31,034 DEBUG 1-thread-2 LdapAuthenticationProvider Successfully bound user [uid=70091m,ou=Utilisateurs,dc=maif,dc=local]. Attempting to retrieving groups.
akhq    | 2021-04-08 14:27:31,037 DEBUG 1-thread-2 .DefaultLdapGroupProcessor No groups found!
akhq    | 2021-04-08 14:27:31,038 DEBUG 1-thread-2 .DefaultLdapGroupProcessor Attempting to add any additional groups...
akhq    | 2021-04-08 14:27:31,038 DEBUG 1-thread-2 LdapAuthenticationProvider Group search returned [[]] for user [70091m]
akhq    | 2021-04-08 14:27:31,051 INFO  1-thread-2 org.akhq.log.access        [Date: 2021-04-08T14:27:30.131288Z] [Duration: 919 ms] [Url: POST /login] [Status: 303] [Ip: /172.20.30.26] [User: 70091m]
akhq    | 2021-04-08 14:27:31,052 DEBUG 1-thread-2 LdapAuthenticationProvider Response successfully created for [70091m]. Response is authenticated: [true]
akhq    | 2021-04-08 14:27:31,198 INFO  1-thread-2 org.akhq.log.access        [Date: 2021-04-08T14:27:31.166447Z] [Duration: 32 ms] [Url: GET /api/me] [Status: 200] [Ip: /172.20.30.26] [User: 70091m]
akhq    | 2021-04-08 14:27:31,376 INFO  1-thread-2 org.akhq.log.access        [Date: 2021-04-08T14:27:31.374028Z] [Duration: 0 ms] [Url: GET /api/auths] [Status: 200] [Ip: /172.20.30.26] [User: 70091m]
akhq    | 2021-04-08 14:27:31,456 INFO  pGroup-1-2 org.akhq.log.access        [Date: 2021-04-08T14:27:31.45593Z] [Duration: 0 ms] [Url: GET /ui/login] [Status: 200] [Ip: /172.20.30.26] [User: 70091m]
akhq    | 2021-04-08 14:27:31,632 INFO  pGroup-1-2 org.akhq.log.access        [Date: 2021-04-08T14:27:31.632088Z] [Duration: 0 ms] [Url: GET /ui/static/css/2.7caccc14.chunk.css] [Status: 200] [Ip: /172.20.30.26] [User: 70091m]
akhq    | 2021-04-08 14:27:31,658 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2021-04-08T14:27:31.658017Z] [Duration: 0 ms] [Url: GET /ui/static/css/main.391157bf.chunk.css] [Status: 200] [Ip: /172.20.30.26] [User: 70091m]
akhq    | 2021-04-08 14:27:31,729 INFO  pGroup-1-4 org.akhq.log.access        [Date: 2021-04-08T14:27:31.72957Z] [Duration: 0 ms] [Url: GET /ui/static/js/2.62ae1d40.chunk.js] [Status: 200] [Ip: /172.20.30.26] [User: 70091m]

I’m attaching my conf file.
[application.txt](https://github.com/tchiotludo/akhq/files/6279449/application.txt)

I tried to set the configuration below but it didn’t work either : 
    ldap:
      default-group: topic-reader
      users:
        - username: 70091m
          groups:
            - topic-reader
        - username: 72788b
          groups:
            - admin

Can you help me, please?

**Comment by tchiotludo** [comment]
Seems that you need to part on the configuration files : 
```yaml
        groups:
          enabled: true
          base: "OU=GroupsOU,dc=example,dc=com"
          filter: "member={0}"
``` 
That allow to search for the group on the ldap

**Comment by thedje** [comment]
Do I have to go through a ldap group? Because initially, I just wanted to spend on the user. And I managed to get it back but I feel like the mapping is not done.

**Comment by tchiotludo** [comment]
Sorry don't understand your response

**Comment by thedje** [comment]
So, as I did not need the group ldap, I removed it from my conf:
    ldap:
      default:
        enabled: true
        context:
          server: 'ldaps://atuprod.maif.local:636'
          managerDn: 'cn=zabbix-lect,ou=Comptes service,ou=Comptes,dc=maif,dc=local'
          managerPassword: 'Maif1234'
        search:
          base: "ou=Utilisateurs,dc=maif,dc=local"
        # groups:
          # enabled: true
          # base: "ou=Utilisateurs,dc=maif,dc=local"
          # filter: "member={0}"

In my log, i have:


akhq    | 2021-04-09 06:17:49,809 DEBUG 1-thread-3 LdapAuthenticationProvider User found in context [uid=70091m,ou=Utilisateurs,dc=maif,dc=local]. Attempting to bind.
akhq    | 2021-04-09 06:17:49,874 DEBUG 1-thread-3 LdapAuthenticationProvider Successfully bound user [uid=70091m,ou=Utilisateurs,dc=maif,dc=local]. Attempting to retrieving groups.
akhq    | 2021-04-09 06:17:49,875 DEBUG 1-thread-3 LdapAuthenticationProvider Group search is disabled for configuration [default]
akhq    | 2021-04-09 06:17:49,876 INFO  1-thread-3 org.akhq.log.access        [Date: 2021-04-09T06:17:49.736915Z] [Duration: 138 ms] [Url: POST /login] [Status: 303] [Ip: /172.20.30.26] [User: 70091m]
akhq    | 2021-04-09 06:17:49,876 DEBUG 1-thread-3 LdapAuthenticationProvider Response successfully created for [70091m]. Response is authenticated: [true]
akhq    | 2021-04-09 06:17:49,916 INFO  1-thread-2 org.akhq.log.access        [Date: 2021-04-09T06:17:49.858514Z] [Duration: 57 ms] [Url: GET /api/me] [Status: 200] [Ip: /172.20.30.26] [User: 70091m]
akhq    | 2021-04-09 06:17:50,045 INFO  1-thread-2 org.akhq.log.access        [Date: 2021-04-09T06:17:50.044379Z] [Duration: 1 ms] [Url: GET /api/me] [Status: 200] [Ip: /172.20.30.26] [User: 70091m]
akhq    | 2021-04-09 06:17:50,064 INFO  1-thread-2 org.akhq.log.access        [Date: 2021-04-09T06:17:50.061656Z] [Duration: 0 ms] [Url: GET /api/auths] [Status: 200] [Ip: /172.20.30.26] [User: 70091m]
akhq    | 2021-04-09 06:17:50,170 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2021-04-09T06:17:50.169608Z] [Duration: 0 ms] [Url: GET /ui/login] [Status: 200] [Ip: /172.20.30.26] [User: 70091m]

But I'm staying on my login page.

**Comment by thedje** [comment]
I ran some tests.

Attached is the config that works pretty much. 
[application.txt](https://github.com/tchiotludo/akhq/files/6285991/application.txt)

Indeed, I still have 3 concerns:
- With the role reader which only has the role topic/read, I can also see acls, consumer groups, nodes...

- Despite the fact that I filtered the data by putting a filter (topics-filter-regexp: "events.arahi.*"), I see all the topics.

- When I log out, I have a 401 error and when I log back in, I have the error:
Internal Server Error: Missing required configuration "bootstrap.servers" which has no default value.
By clicking on topic, I find my data without errors.

However, this works by putting only 2 entries in security.groups (admin and reader)
If I add the following lines by adding a new reader_arahi entry:
      reader_arahi: # unique key
        name: reader_arahi # Other group
        roles:
          - topic/read
		  
And that I declare this role to the user :
    ldap:
      users:
        - username: 70091m 
          groups:
            - reader_arahi

I stay on the home page.

**Comment by tchiotludo** [comment]
Maybe you will need to rename reader group on your configuration ? 
The name can clash with the default one and maybe micronaut merge the properties ? 

Since I think it's was what you're trying with `reader_arahi`, I think it's a good solution.
Since ldap is complicated, can you try with simple basic auth and share the configuration please ?

**Comment by thedje** [comment]
Hello
I redid the conf to desactivate the ldap and add in the basic-auth a user arahi :
[application.txt](https://github.com/tchiotludo/akhq/files/6334758/application.txt)


And I stay on the home page with the user arahi.
The logs:

akhq    | 2021-04-19 09:06:30,172 INFO  pGroup-1-2 org.akhq.log.access        [Date: 2021-04-19T09:06:30.163197Z] [Duration: 9 ms] [Url: HEAD /ui/login] [Status: 200] [Ip: /172.20.30.26] [User: Anonymous]
akhq    | 2021-04-19 09:06:30,576 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2021-04-19T09:06:30.516975Z] [Duration: 59 ms] [Url: POST /login] [Status: 303] [Ip: /172.20.30.26] [User: arahi]
akhq    | 2021-04-19 09:06:30,703 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2021-04-19T09:06:30.699814Z] [Duration: 3 ms] [Url: POST /login] [Status: 303] [Ip: /172.20.30.26] [User: arahi]
akhq    | 2021-04-19 09:06:30,882 INFO  1-thread-2 org.akhq.log.access        [Date: 2021-04-19T09:06:30.8432Z] [Duration: 39 ms] [Url: GET /api/me] [Status: 200] [Ip: /172.20.30.26] [User: arahi]
akhq    | 2021-04-19 09:06:31,009 INFO  1-thread-2 org.akhq.log.access        [Date: 2021-04-19T09:06:31.008061Z] [Duration: 1 ms] [Url: GET /api/me] [Status: 200] [Ip: /172.20.30.26] [User: arahi]
akhq    | 2021-04-19 09:06:31,024 INFO  1-thread-2 org.akhq.log.access        [Date: 2021-04-19T09:06:31.023562Z] [Duration: 0 ms] [Url: GET /api/auths] [Status: 200] [Ip: /172.20.30.26] [User: arahi]
akhq    | 2021-04-19 09:06:31,151 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2021-04-19T09:06:31.150601Z] [Duration: 0 ms] [Url: GET /ui/login] [Status: 200] [Ip: /172.20.30.26] [User: arahi]
akhq    | 2021-04-19 09:06:31,474 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2021-04-19T09:06:31.473833Z] [Duration: 0 ms] [Url: GET /ui/static/css/2.7caccc14.chunk.css] [Status: 200] [Ip: /172.20.30.26] [User: arahi]
akhq    | 2021-04-19 09:06:31,500 INFO  pGroup-1-5 org.akhq.log.access        [Date: 2021-04-19T09:06:31.500527Z] [Duration: 0 ms] [Url: GET /ui/static/css/main.391157bf.chunk.css] [Status: 200] [Ip: /172.20.30.26] [User: arahi]
akhq    | 2021-04-19 09:06:31,661 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2021-04-19T09:06:31.660865Z] [Duration: 0 ms] [Url: GET /ui/static/js/2.62ae1d40.chunk.js] [Status: 200] [Ip: /172.20.30.26] [User: arahi]
akhq    | 2021-04-19 09:06:31,682 INFO  pGroup-1-4 org.akhq.log.access        [Date: 2021-04-19T09:06:31.681773Z] [Duration: 0 ms] [Url: GET /ui/static/js/main.2631d833.chunk.js] [Status: 200] [Ip: /172.20.30.26] [User: arahi]
akhq    | 2021-04-19 09:06:32,097 INFO  1-thread-2 org.akhq.log.access        [Date: 2021-04-19T09:06:32.09567Z] [Duration: 1 ms] [Url: GET /api/cluster] [Status: 200] [Ip: /172.20.30.26] [User: arahi]
akhq    | 2021-04-19 09:06:32,127 INFO  1-thread-3 org.akhq.log.access        [Date: 2021-04-19T09:06:32.126666Z] [Duration: 0 ms] [Url: GET /api/me] [Status: 200] [Ip: /172.20.30.26] [User: arahi]
akhq    | 2021-04-19 09:06:32,135 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2021-04-19T09:06:32.134742Z] [Duration: 0 ms] [Url: GET /ui/static/media/icon.648ce9c8.svg] [Status: 200] [Ip: /172.20.30.26] [User: arahi]
akhq    | 2021-04-19 09:06:32,269 INFO  pGroup-1-4 org.akhq.log.access        [Date: 2021-04-19T09:06:32.269316Z] [Duration: 0 ms] [Url: GET /ui/static/media/logo.45903e1f.svg] [Status: 200] [Ip: /172.20.30.26] [User: arahi]
akhq    | 2021-04-19 09:06:32,309 INFO  pGroup-1-5 org.akhq.log.access        [Date: 2021-04-19T09:06:32.309661Z] [Duration: 0 ms] [Url: GET /ui/static/media/fontawesome-webfont.af7ae505.woff2] [Status: 200] [Ip: /172.20.30.26] [User: arahi]
akhq    | 2021-04-19 09:06:32,361 INFO  1-thread-3 org.akhq.log.access        [Date: 2021-04-19T09:06:32.361188Z] [Duration: 0 ms] [Url: GET /api/auths] [Status: 200] [Ip: /172.20.30.26] [User: arahi]
akhq    | 2021-04-19 09:06:32,472 INFO  1-thread-3 org.akhq.log.access        [Date: 2021-04-19T09:06:32.46569Z] [Duration: 6 ms] [Url: GET /api/me] [Status: 200] [Ip: /172.20.30.26] [User: arahi]
akhq    | 2021-04-19 09:06:32,567 INFO  pGroup-1-2 org.akhq.log.access        [Date: 2021-04-19T09:06:32.566682Z] [Duration: 0 ms] [Url: GET /ui/favicon.ico] [Status: 200] [Ip: /172.20.30.26] [User: arahi]
akhq    | 2021-04-19 09:06:34,410 INFO  pGroup-1-3 org.akhq.log.access        [Date: 2021-04-19T09:06:34.410331Z] [Duration: 12 ms] [Url: HEAD /ui/login] [Status: 200] [Ip: /172.20.30.26] [User: Anonymous]
akhq    | 2021-04-19 09:06:39,397 INFO  pGroup-1-4 org.akhq.log.access        [Date: 2021-04-19T09:06:39.397031Z] [Duration: 0 ms] [Url: HEAD /ui/login] [Status: 200] [Ip: /172.20.30.26] [User: Anonymous]

**Comment by tchiotludo** [comment]
Here is a minimal configuration that is working on my side based on your !
I didn't changed a lot of things and it's working well.

I didn't take about your version .... move to [0.17.0](https://github.com/tchiotludo/akhq/releases/tag/0.17.0).
The configuration your are using is not working for 0.16.0

```yaml 
micronaut:
  security:
    enabled: true

akhq:
  security:
    default-group: no-roles

    groups:
      reader_arahi:
        name: reader_arahi 
        roles:
          - topic/read

    basic-auth:
      - username: user
        password: d74ff0ee8da3b9806b18c877dbf29bbde50b5bd8e4dad7a3a725000feb82e8f1
        groups:
          - admin
      - username: arahi
        password: d74ff0ee8da3b9806b18c877dbf29bbde50b5bd8e4dad7a3a725000feb82e8f1
        groups:
          - reader_arahi
```

**Comment by thedje** [comment]
Hello, thank you for the information.
