### ISSUE TITLE
Protobuf deserialization doesn't seem to work if there's a schema

### ISSUE THREAD

**Issue by cortopy** [tchiotludo/akhq#671]
When inspecting messages that are linked to a schema, I'm getting the following error

```
Error retrieving Avro unknown schema for id 1
```

Below the alert, the message is not parsed and displayed raw

Would it be possible to remove this error until someone completes https://github.com/tchiotludo/akhq/issues/666?

**Comment by tchiotludo** [comment]
I don't think we can remove this message until the #666. 
The whole application is thinking all is avro and will need this issue to be fixed in order to remove the error (and display the content :tada:)
