### ISSUE TITLE
Empty header on new message

### ISSUE THREAD

**Issue by kostkol87** [tchiotludo/akhq#677]
Hello! Faced with such bug: when produce new event to topic without any headers, a header like "":"" is added. For java org.springframework.messaging.Message it is critical for deserialization and it falls =(
It seems like it might be fixed in org.akhq.repositories.RecordRepository#produce(440) via filtering headers like:

.filter(entry -> StringUtils.isNotEmpty(entry.getKey()))

alternatively it might be fixed in front-end part of application: do not define the headers at all if nothing was passed.

Unfortunalty I'm not able to check my solution or make PR cause I have issues with dev environment, even cant build project =(

**Comment by tchiotludo** [comment]
I can reproduced, it's fixed on the server side ! 
Thanks for report
