### ISSUE TITLE
Starting the embedded Micronaut in https?

### ISSUE THREAD

**Issue by snaxattax** [tchiotludo/akhq#687]
I've been trying to pass the following to akhq during startup as jvm command line arguments: 
micronaut.ssl.enabled=true 
micronaut.ssl.buildSelfSigned=true 

and the embedded micronaut is still coming up http only on 8080. Trying using 'real' certs isn't working, either... micronaut still comes up http only on 8080.

Is there any other way to achieve this?

**Comment by alselies** [comment]
try this

comment : micronaut.server...
add : micronaut.ssl.port: 8080

**Comment by apellegr06** [comment]
Hi,

For SSL I have added that to the config file :

micronaut:
  ssl:
    enabled: true
    port: 8082
    key-store:
      path: file:xxxxxx
      password: xxxxxx
      type: JKS

**Comment by tchiotludo** [comment]
Seems to be the good options
