### ISSUE TITLE
Error with "logicalType": "timestamp-millis"

### ISSUE THREAD

**Issue by dmassimi** [tchiotludo/akhq#688]
Hi,
we discovered an issue on AKHQ when messages Avro are using this kind of objects:

    {
      "name": "dateCreation",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },

You can find attached:

- avsc schema [original-170.avsc.txt](https://github.com/tchiotludo/akhq/files/6403334/original-170.avsc.txt)
- smple message [message-test-170.txt](https://github.com/tchiotludo/akhq/files/6403325/message-test-170.txt)
- error screenshot: 
![error-akhq](https://user-images.githubusercontent.com/31727023/116657386-9a0e2300-a98e-11eb-89dd-fda0038a2b1b.png)

To fix the issue we had to modify class AvroToJsonSerializer : 

    protected void writeField(Object datum, Schema.Field f, Encoder out, Object state) throws IOException {
        if (datum instanceof GenericData.Record) {
            Schema fieldSchema = f.schema();
            LogicalType logicalType = fieldSchema.getLogicalType();
            Object value = getData().getField(datum, f.name(), f.pos());
            if (logicalType instanceof LogicalTypes.Decimal) {
                value = convert(DECIMAL_CONVERSION, fieldSchema, logicalType, value);
            }
            if (logicalType instanceof LogicalTypes.TimestampMillis) { // to manage "logicalType": "timestamp-millis"
                value= ChronoUnit.MICROS.between(Instant.EPOCH, (Instant)value);
            }
            writeWithoutConversion(fieldSchema, value, out);
        } else {
            super.writeField(datum, f, out, state);
        }
    }

After this modification the error on AKHQ disappeared : 

![image](https://user-images.githubusercontent.com/31727023/116657782-44864600-a98f-11eb-9b1f-a9798e06dbae.png)

PS: we use Tibco lib into AKHQ to serialize/deserialize messages

**Comment by tchiotludo** [comment]
Clearly, we need to better handle logicalType for Avro, but maybe you can add a PR for that ? 
Before we handle a full refactor on this part ?

**Comment by dmassimi** [comment]
Hi,
ok I just submitted a pull request .
