### ISSUE TITLE
Search for tombstones in a topic

### ISSUE THREAD

**Issue by BernhardBerbuir** [tchiotludo/akhq#691]
When a topic uses compaction than the latest version of a message is preserved. In order to delete a message, a message with the value `null` is produced. These messages are called tombstones as they mark a message as dead.

It would be nice to be able to search for these tombstones. The search field could add an additional option `null` for the drop down box of `Value`.

**Comment by xakassi** [comment]
Hi, @tchiotludo ! It really looks like a simple change! And I'm interested, thanks for mentioning me! 
But really big changes in my life are coming, so I cannot promise anything 🤔 Maybe I will have time in June or July and will try to do that!

**Comment by tchiotludo** [comment]
make a shortcut and you can type null to search a tombstone ;)
