### ISSUE TITLE
akhq.tar 0.17 contains an akhq-0.1 directory

### ISSUE THREAD

**Issue by gquintana** [tchiotludo/akhq#696]
The akhq 0.17 archive available at https://github.com/tchiotludo/akhq/releases/download/0.17.0/akhq.tar
contains a directory names akhq-0.1 . It's the same for the .zip archive.

0.1 is the version declared in Gradle config.

**Comment by tchiotludo** [comment]
I know, the gradle config doesn't follow the real version of akhq (and will never I think). 
Mostly, the better will be to remove the version on the tar / zip

**Comment by gquintana** [comment]
Having the version in the folder name is useful when upgrading: to test side by side different versions and be able to quickly rollback to previous version. I understand that archives are not the future of distribution nor deployment, sadly Docker is not everywhere yet.

**Comment by gquintana** [comment]
What about using https://github.com/palantir/gradle-git-version to get Git tag into Gradle version?

**Comment by tchiotludo** [comment]
Nice idea, I think I have also a bug on version displayed on ui, will look at both or PR are welcome ;)
