### ISSUE TITLE
Produce a msg generate a non empty header

### ISSUE THREAD

**Issue by raphaelauv** [tchiotludo/akhq#701]
If I set nothing to the header 
![Screenshot from 2021-05-15 16-58-25](https://user-images.githubusercontent.com/10202690/118365943-ff712f00-b59e-11eb-9faf-7dad009a15fc.png)

the header is not empty but compose of 

```json
[{"key":"","stringValue":""}]
```

With the control center UI of confluent I can see difference between an event produce by my producer and an event produce with AKHQ
![Screenshot from 2021-05-15 16-58-46](https://user-images.githubusercontent.com/10202690/118365937-fa13e480-b59e-11eb-9b6a-392a5a0436c0.png)

**Comment by tchiotludo** [comment]
Hi, 

It's fixed on dev image, see https://github.com/tchiotludo/akhq/issues/677
