### ISSUE TITLE
Override security per connection

### ISSUE THREAD

**Issue by sverrehu** [tchiotludo/akhq#710]
We use AKHQ to let anonymous (`micronaut.security.enabled: false`) users inspect two clusters/connections. We have set `akhq.security.default-group` to refer to a group that has the roles we wish to give our users.

In one of the clusters, AKHQ has no access to topic data, while in the other cluster AKHQ has unlimited access.

We would like to configure AKHQ to reflect this, ie. allow `topic/data/read` in only one of the clusters. When browsing the `README.md`, I get the impression that this is not currently possible.

So this is an RFE: Allow `akhq.connections.foo` to have a `security` key for overriding the global `akhq.security`. Or otherwise make it possible to specify a `default-group` per connection.

**Comment by tchiotludo** [comment]
Not possible for now, look at this for more insight : https://github.com/tchiotludo/akhq/discussions/523

**Comment by tchiotludo** [comment]
done in #1472
