### ISSUE TITLE
Query parameters don't survive a login

### ISSUE THREAD

**Issue by chiodonia** [tchiotludo/akhq#719]
We deployed AKHQ with LDAP integration and we are using deep linking with query params to jump i.e. into a topic.
However, if you are not previously logged in to AKHQ you are redirected to the login page. Once you log in you are then redirected to the main AKHQ page and initial query params are lost.

Would it be possible to make query parameters survive the login?

**Comment by tchiotludo** [comment]
I think it's possible ;)

**Comment by grosswilerp** [comment]
When will this issue be fixed?

**Comment by tchiotludo** [comment]
When someone (you) will make a PR :smile:

**Comment by grosswilerp** [comment]
> When someone (you maybe ?) will make a PR

@tchiotludo I have created a PR as requested. Let me know if I need to make any changes.
