### ISSUE TITLE
Unable to login when username contains at least one uppercase letter

### ISSUE THREAD

**Issue by erkexzcx** [tchiotludo/akhq#722]
Nothing happens, login screen just reloads. After changing username to lowercase, everything started to work fine.

I know that usernames should be lowercase, but that's not the point. It should not work like.

**Comment by tchiotludo** [comment]
What authentification are you using ?

**Comment by erkexzcx** [comment]
Hi. It's `basic-auth`, latest release.

**Comment by tchiotludo** [comment]
Hi, 
I've made a test & a unit test and it's working well. 
Can you try with `dev` version please and reopen if it's don't work ?
