### ISSUE TITLE
Minimum required roles to display Kafka Connect Error

### ISSUE THREAD

**Issue by twobeeb** [tchiotludo/akhq#723]
Hi,

I can't see the error messages from Kafka Connects with the role "connect/status".

All I can see is this : 
![image](https://user-images.githubusercontent.com/6431261/120472817-a67b0680-c3a6-11eb-87e9-592f42ec8f8e.png)
The Red button with ERROR is not clickable with my current roles : 
````yaml
  roles:
    - topic/read
    - topic/data/read
    - group/read
    - registry/read
    - connect/read
````

If I switch to a **different user with admin roles**, then the button is clickable and I get redirected to the following page with the error message : 
![image](https://user-images.githubusercontent.com/6431261/120473295-2a34f300-c3a7-11eb-84ab-ce6ca6ea5f30.png)

My problem is that to access the Kafka Connect Error message, it seems that I must also allow the user to PAUSE / RESTART and also modify the configuration (in the second tab)

**Is there a way to give access to the error message without also giving ``alter config``, ``pause``/``resume`` and ``restart`` ?**

Thanks,

Julien

**Comment by raphaelauv** [comment]
Very nice proposition, Accessing the full log of error with read access would be great

**Comment by twobeeb** [comment]
This is already implemented on the dev branch with only `connect/read` role.

I should have specified I was using v0.17.0
**Proof on DEV** 
no restart button
![image](https://user-images.githubusercontent.com/6431261/122636241-6aef7480-d0e8-11eb-9155-c73fca4ad713.png)

config is read only (everything is greyed out)
![image](https://user-images.githubusercontent.com/6431261/122636266-97a38c00-d0e8-11eb-8182-c799a4bfdb23.png)

Closing this ticket.
