### ISSUE TITLE
Improve doc about 8081 port and monitoring endpoints

### ISSUE THREAD

**Issue by miniwark** [tchiotludo/akhq#727]
8081 is the default port for schema-registry,
but it seem to be also a port used for endpoints monitoring in akhq

The documentation must better explain how to change this port in  the akhq configuration,
or how to disable monitoring.

Because, if 8081 port already used by schema-registry, then one of then fail to start.

**Comment by tchiotludo** [comment]
Good catch, I decided to changed the monitoring port to 28081 to avoid conflict :smile:
