### ISSUE TITLE
Error deserializing timestamp millis

### ISSUE THREAD

**Issue by alozano3** [tchiotludo/akhq#739]
Hi,

I think #689 introduced and error and it's not possible to deserialize the type timestamp millis.

I could read this message before and the type timestamp millis was deserialized as long, but now I get:
![image](https://user-images.githubusercontent.com/31214345/122351400-62633680-cf4e-11eb-93f9-655c171aa76c.png)

I have extended a test to reproduce the issue and the next error is thrown:
`class java.lang.Long cannot be cast to class java.time.Instant (java.lang.Long and java.time.Instant are in module java.base of loader 'bootstrap')`

You can reproduce the issue running [this test](https://github.com/alozano3/akhq/blob/deserialize-timestamp-error/src/test/java/org/akhq/modules/AvroToJsonSerializerTest.java#L26)

**Comment by tchiotludo** [comment]
must be done on `dev`, can you try ?

**Comment by alozano3** [comment]
It works perfectly!! Thanks!!
