### ISSUE TITLE
Cannot see nodes config on Kafka 2.8.0-1

### ISSUE THREAD

**Issue by schiric** [tchiotludo/akhq#744]
Hi, i'm using the latest version of akhq docker image, but i can't see cluster nodes configuration from the GUI, the loading screen remains indefinitely.

I've tried invoking the API from the URL http://<host>:<port>/api/nodes/id/<num>/config and i can see the result JSON containing all the properties settend on server.properties of the broker.
I've also tried to use the same configurations (AKHQ and KAFKA) on a previous kafka version and it worked well.

Is the last version compatible with the Kafka 2.8.0-1 version?

Thx!

**Comment by schiric** [comment]
I also specify that we are on AKS.

**Comment by schiric** [comment]
Another info:
i've tried invoke /api/kafka-dev/node/0/configs
and inside the JSON response i found:

**Comment by tchiotludo** [comment]
I can't reproduce the issue but I try to make a fix, please try `dev` branch please

**Comment by schiric** [comment]
the fix works! now i'm able to see al config of each node.
thx!
