### ISSUE TITLE
Topic list broken when logDirSize isn't a number

### ISSUE THREAD

**Issue by samudurand** [tchiotludo/akhq#750]
We are currently trying to upgrade from version 0.14.1 to version 0.17.0. There is an issue on the UI side, that prevents the topic list from displaying. No error is thrown on the server side, but the UI generates a JS error:

```
converters.js:81 Uncaught (in promise) TypeError: a.val.toFixed is not a function
    at m (converters.js:81)
    at TopicList.jsx:177
    at Array.forEach (<anonymous>)
    at a.value (TopicList.jsx:172)
    at a.<anonymous> (TopicList.jsx:152)
    at c (runtime.js:45)
    at Generator._invoke (runtime.js:274)
    at Generator.forEach.e.<computed> [as next] (runtime.js:97)
    at r (asyncToGenerator.js:3)
    at s (asyncToGenerator.js:25)
```

The line creating the issue is the following (in `converters.js`):

```
  return `${parseFloat(value.val.toFixed(dPlaces))} ${value.unit}`;
```

Looking at the JSON returned by the Rest endpoint, I noticed that sometimes `logDirSize` is a number (`"logDirSize": 622838`) , and sometimes it is a JSON object, which is probably why this piece of JS fails. This is an example of object returned:

```
      "logDirSize": {
        "empty": false,
        "present": true
      }
```

Does anyone know why this is happening and what we can do to deal with it ? Thank you.

**Comment by samudurand** [comment]
@tchiotludo has this fix been released ?

**Comment by tchiotludo** [comment]
It's not released but you can try dev version
