### ISSUE TITLE
How to enable debug root level for akhq?

### ISSUE THREAD

**Issue by vutkin** [tchiotludo/akhq#752]
Hi all, could you please advise how to enable root debug level for akhq?
I need more logs, because when I changed image version from 0.17.0 to 0.18.0 pod can't pass health-checks.

TIA, Regards, Viktor.

**Comment by vutkin** [comment]
@tchiotludo Could you please advise?

**Comment by tchiotludo** [comment]
I've updated the [helmcharts](https://github.com/tchiotludo/akhq/blob/dev/helm/akhq/templates/deployment.yaml#L83), the healthcheck now listen on [28081](https://github.com/tchiotludo/akhq/blob/dev/src/main/resources/application.yml#L70).

You can change the logger in configuration : 
```yaml
logger:
  levels:
    foo.bar: ERROR
```

**Comment by vutkin** [comment]
yep, with new management port works well
```
logger:
  levels:
    root: DEBUG
```
Will this config works as default level for all loggers?

**Comment by sadym** [comment]
as with this health check change, wouldn't be better to hardcode the image inside each helm release? I'm sure we're not the only ones that suddenly noticed that akhq is not starting anymore. Of course we can customize our local values, but it's a good practice to not use latest by default.

**Comment by tchiotludo** [comment]
@sadym : done here #768
