### ISSUE TITLE
Breaking change on new release with Helm

### ISSUE THREAD

**Issue by callaertanthony** [tchiotludo/akhq#754]
Hello,

Using new version (from `0.17.0` to `0.18.0` and Helm chart from `0.2.1` to `0.2.2`) implies breaking changes.
I have no time for the moment to check why but this is the error message at startup.
```
An exception 'java.lang.IllegalArgumentException: Couldn't find any clusters on your configuration file, please ensure that the configuration file is loaded correctly' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.IllegalArgumentException: Couldn't find any clusters on your configuration file, please ensure that the configuration file is loaded correctly
```

I had a check on documentation and my configuration seems correct (based on doc not on code 🙃). If I find time I will help you to resolve it.
Regards

**Comment by tchiotludo** [comment]
yes there is this change here : https://github.com/tchiotludo/akhq/commit/2bd7222918e7dddcdd4da9bfdecaf7b84352e140
secrets & config are is yaml and not string anymore

**Comment by callaertanthony** [comment]
Hi,

Thanks this solves my issue.

Regards
