### ISSUE TITLE
Add support for JsonSchema from confluent schema repository

### ISSUE THREAD

**Issue by ebrard** [tchiotludo/akhq#756]
Confluent schema repository supports Avro and JsonSchema (as well as protobuf) but currently only Avro schema are implemented in AKHQ. Since JSON is basically a string when the confluent wire format is used with JSON data, I think it would be enough to reference the schema but use the StringDeserializer to display the message and/or key.

I think the main challenge is that the schema type is not part of the registry responses.

**Comment by ebrard** [comment]
This seems to be implemented in https://github.com/tchiotludo/akhq/pull/755/files

**Comment by tchiotludo** [comment]
I think so but I never used this format on schema registry @ebrard maybe you can help and test the integration ? :smile:

**Comment by ebrard** [comment]
Certainly, I can compile the branch locally and try for JsonSchema. I'll come back to this thread with the result.

**Comment by ebrard** [comment]
I checked manually, this works for JsonSchema, I'll also add some Avro records to make sure there's no regression.

**Comment by ebrard** [comment]
Works as well for Avro, as before.
