### ISSUE TITLE
Regression with Avro producer in 0.18.0 as compared to 0.16.0

### ISSUE THREAD

**Issue by timtebeek** [tchiotludo/akhq#761]
Similar perhaps to #757, but with slightly different characteristics. Noticed after switching from 0.16.0 to 0.18.0 recently.

So as a bit of background: we use `org.springframework.kafka.listener.DeadLetterPublishingRecoverer`, so any messages that fail handling in our Kafka consumers, are pushed onto a dead letter topic with the exact same schema and body. Then, once the underlying handling issue is fixed, I used to copy-paste the key & value from the dead letter topic as viewed through AKHQ into the original topic producer form in AKHQ, selecting the appropriate value schema.

After switching to 0.18.0 I noticed I can no longer directly copy&paste the value for our Avro schemas, due to small incompatibilities in the (de)serializers used.

1. For instance, we have a timestamp-millis Avro field
```
{
  "name": "orderDateTime",
  "type": {
    "type": "long",
    "logicalType": "timestamp-millis"
  }
},
```
The viewer seems to convert this to an Instant: https://github.com/tchiotludo/akhq/blob/0.18.0/src/main/java/org/akhq/utils/AvroDeserializer.java#L150
Which is rendered in the form of `2011-12-03T10:15:30Z`

However, the producer form seems to use a slightly different date time format: https://github.com/tchiotludo/akhq/blob/0.18.0/src/main/java/org/akhq/utils/AvroSerializer.java#L44
Notice the additional 3 digits for microseconds rather than milliseconds.

2. We also have a field that's an array of records, with a default value of an empty array:
```
{
"name": "services",
"type": {
	"type": "array",
	"items": {
		"type": "record",
		"name": "Service",
		"fields": [...omitted...]
	}
},
"default": []
},
```
When empty the field is omitted in the viewer, but it's required (as empty array) in the producer, even though there's a default value for the field.

Both issues block us from copy&pasting from the view of a topic with Avro content to the producer form of a topic with the same Avro schema, with some tedious and error-prone manual intervention needed when we propagate from our DLT topic to our original topic.

Could the formatting & requirements for the viewer & producer be harmonized to return to a quick way to copy-paste content between topics?

**Comment by timtebeek** [comment]
@tchiotludo were you planning on a release any time soon? This issue in particular makes it hard for us to recover records pushed onto a dead letter topic, do a release would be much appreciated.

And on that note: have you considered adopting JReleaser? Seems like that could make the release flow easier. I'd be willing to help out if needed!

**Comment by tchiotludo** [comment]
I will release next week I think :smile: 

I never look at JReleaser, but for now the release is not so hard, I just tag a commit and the github actions handle all the things ;)

**Comment by tchiotludo** [comment]
Lot of weeks / month, release happen :smile:

**Comment by timtebeek** [comment]
Haha, glad to see the new release, congrats!
Already pinned in personal project & at work.
Plus the new docs look great; big improvement! :)
