### ISSUE TITLE
40408 error on /config/subject instead of 40401 cause AKHQ to break

### ISSUE THREAD

**Issue by twobeeb** [tchiotludo/akhq#763]
When running AKHQ against recent version of Schema Registry, the schema registry is throwing different errors codes than previous versions when calling /config/subject (which is allowed to return 404).

Because the error is not ignored, the SchemaRegistry page completely fails on AKHQ : 
![image](https://user-images.githubusercontent.com/6431261/126338334-d045c1a5-d9d8-497f-81a1-61e1f89f95b9.png)

This is the failing part, which requires specifically 40401 : 
https://github.com/tchiotludo/akhq/blob/dev/src/main/java/org/akhq/repositories/SchemaRegistryRepository.java#L222-L235

Change on Confluent side : 
https://github.com/confluentinc/schema-registry/pull/1920

**Comment by twobeeb** [comment]
I suggest replacing the above code with : 
````java
public Schema.Config getConfig(String clusterId, String subject) throws IOException, RestClientException {
        try {
            return new Schema.Config(this.kafkaModule
                .getRegistryRestClient(clusterId)
                .getConfig(subject)
            );
        } catch (RestClientException exception) {
            if (exception.getStatus() != 404) {
                throw exception;
            }

            return this.getDefaultConfig(clusterId);
        }
    }
````

What's your opinion ?

**Comment by tchiotludo** [comment]
Release happen :smile:
