### ISSUE TITLE
Feature suggestion: sort topics by size.

### ISSUE THREAD

**Issue by themoah** [tchiotludo/akhq#767]
Hey,

First of all - many thanks for akhq. Amazing service! Helps us a lot.
Any option to sort topics in web UI by size? I've got workaround with a script calling api, but it's too complicated.

thanks!
(I have no idea in front-end development, thus would have suggested pr).

**Comment by tchiotludo** [comment]
This one is not possible. 
It will need to fetch all the data for all the topic and sort on the akhq side. 
This will cause performance issue for cluster with lot of topic / partitions, sorry :smile:
