### ISSUE TITLE
Produce message error after upgrading to 0.18.0

### ISSUE THREAD

**Issue by fabiofilz** [tchiotludo/akhq#819]
Hi Team,

We upgraded the AKHQ to 0.18.0 using helm chart 0.2.2. After this upgrade when I try to Produce a new message into a topic it raises an error as per below.

I downgraded to 0.17.0 and helm chart 0.2.0 and I was able to produce the same message.

Please find the screenshot of :

![Produce_msg_payload](https://user-images.githubusercontent.com/45266582/133788511-b6a02375-4eec-4e1f-923f-b3b40fc5fc26.png)
![Produce_msg_error](https://user-images.githubusercontent.com/45266582/133788520-bdf713dd-1fdf-4ba6-8d7f-3e0aba6cc8db.png)

Thank you.
Fabio

**Comment by tchiotludo** [comment]
It's seems that there is mistake on report, you downgrade upgrade from the same version :smile: 

Can you try with last `dev` version please ? it will be release soon and there is a lot of fix for avro

**Comment by fabiofilz** [comment]
Hi @tchiotludo ,

You are too fast with the reply! :-)   ... I fixed the version on the report.

I will deploying the tag dev and re-test it.

Thanks,
Fabio

**Comment by fabiofilz** [comment]
Hi @tchiotludo,

I deployed the DEV tag and the error also happen.

![Produce_msg_error_dev_tag](https://user-images.githubusercontent.com/45266582/133799087-e4a130d1-8f07-4ebf-9838-60ae074bf47f.png)

![Produce_msg_payload_dev_tag](https://user-images.githubusercontent.com/45266582/133799083-8aa22ae5-ff83-4f06-8bd8-2c2d47a47a97.png)

**Comment by fabiofilz** [comment]
Testing Multi-message

![Produce_msg_error_dev_tag_multimessage](https://user-images.githubusercontent.com/45266582/133800626-faebdfd4-9880-4b9e-b85d-620732d7ff9d.png)
![Produce_msg_payload_dev_tag_multimessage](https://user-images.githubusercontent.com/45266582/133800635-c9a1be19-3211-40c5-8dd2-73e1868a796d.png)

**Comment by tchiotludo** [comment]
For multiple message, it must be on 1 row per key|value with value in json.
Why you enclose the key with quote ? I think this is the issue here

**Comment by fabiofilz** [comment]
In version 0.17 it complained that key was not string.

Please find the test without quotes

![Produce_msg_payload_dev_tag_key_number](https://user-images.githubusercontent.com/45266582/133824593-5803c195-6961-4594-801e-415a54ac4e84.png)


![Produce_msg_error_dev_tag_key_number](https://user-images.githubusercontent.com/45266582/133824579-1283bb69-de52-4708-a14e-95c0620c2103.png)

**Comment by tchiotludo** [comment]
ok I see the issue now, the key is numeric value it seems ? 
Can you provide the avro schema for the key ?

**Comment by fabiofilz** [comment]
This is the avro schema for the key

![Key](https://user-images.githubusercontent.com/45266582/133838695-2d9b63df-cae0-446a-b15d-fb7368aeb77d.png)

**Comment by tchiotludo** [comment]
I don't even know this kind of schema was valid :laughing: 
I made a fix to handle this but clearly I wouldn't use this schema it in production by myself :smile: 
please try `dev` branch in 5 minutes

**Comment by fabiofilz** [comment]
Hi @tchiotludo,

I tested here and it is working as expected. 

Thank you for fixing it :-)

Have a good weekend

**Comment by unixunion** [comment]
> I don't even know this kind of schema was valid 😆

@tchiotludo, primitives are a validd data-type for keys or values under Kafka, and historically I have registered these with SR as a "JSON" post. example: 

    res = kafkaSchemaRegistry.publishSchema(String.format("de-%s-key", eventName), new Schema.Parser().parse("{\"type\": \"string\"}"));
    
The only clue to this ability is documented here: 

https://docs.confluent.io/platform/current/control-center/topics/schema.html#create-a-topic-key-schema

/K
