### ISSUE TITLE
Protobuf types with the same name causes deserialization to fail

### ISSUE THREAD

**Issue by drurenia** [tchiotludo/akhq#822]
**Problem Description** 

Given two Protobuf message definition within the same file descriptor that are being used as the `message type: 
- `foo.v1.Bar`
- `foo.v2.Bar`

And the Protobuf deserialization mapping as follows:

```yaml
deserialization:
  protobuf:
    topics-mapping:
      topic-regex: 'topic.foo.*'
        descriptor-file-base64: <base64 file descriptor>
        value-message-type: 'Bar'
 ```

While deserializing AKHQ considers only the unqualified name of the descriptor and not the fully qualified name (`Descriptor#getName` vs `Descriptor#getFullName`), which in this instance would result in two descriptors being found: https://github.com/tchiotludo/akhq/blob/ff07a3d271179c286aa5b01b60a808a789e3a87c/src/main/java/org/akhq/utils/ProtobufToJsonDeserializer.java#L161

So far so good, finding two descriptors is not really the problem. The real issue is when AKHQ goes through all the available descriptors it found and try to deserialize the value. In some instances the first descriptor to be evaluated is not the correct one and this causes an `com.google.protobuf.InvalidProtocolBufferException` to be raised. Said exception will stop the other descriptors found to be evaluated which will result in an error to be displayed to the user. 

https://github.com/tchiotludo/akhq/blob/ff07a3d271179c286aa5b01b60a808a789e3a87c/src/main/java/org/akhq/utils/ProtobufToJsonDeserializer.java#L169

N.B: I am using AKHQ `0.18.0`

---
**Potential Solutions**

I see at least three ways of solving the problem:
1. Separate both messages in their own file descriptor files and this way avoiding the problem completely (no AKHQ code changes required). This of course is not always possible, since sometimes we have no control over the generation of the file descriptors and can't utilize such approach.
2. Support fully qualified names (maybe a new property `value-message-type-full-name` or something similar.
3. Only propagate the `com.google.protobuf.InvalidProtocolBufferException` once all descriptors in the `descriptorsForConfiguredMessageTypes` were tried and failed.

I would be more than happy to create a PR with solution number 2 or 3 (whatever you think is best), as well as with any other suggested solution that stem from this issue.

**Comment by tchiotludo** [comment]
I think the better solution will be fix the current behavior and to go to 2 (and only full qualified, we can go breaking compatibility I think). 
The previous implementation is beta, and there is some area of enhancement https://github.com/tchiotludo/akhq/pull/543.
What do you think about that ?

**Comment by drurenia** [comment]
Just to make sure we understand each other, are you suggesting we go with number 2 but with fully qualified name **only** and introduce a breaking change?

I think having two properties (`value-message-type-full-name` and `value-message-type`) will introduce a little bit of confusion to users, so having only `value-message-type` using fully qualified name has its benefits. If we are ok introducing a breaking change, I am all in for it.

Please let me know if I misinterpreted your message.

**Comment by tchiotludo** [comment]
Yes you clearly understand :) 
Go for breaking change to avoid confusion :+1: 
(There is already too many options on application.yml, don't want to add extra confusion for people)

**Comment by drurenia** [comment]
Awesome! I will create the PR as soon as possible.
