### ISSUE TITLE
Decode Avro messages without schema id

### ISSUE THREAD

**Issue by bgranvea** [tchiotludo/akhq#833]
I have a topic containing Avro messages without schema metadata. I would like to be able to display them in akhq but I can't modify the producer. All messages in this topic follow the same schema.

As far as I can tell, this is not possible today to configure a topic=>schema id mapping (or maybe topic => schema without using schema registry at all).

This feature was discussed in #181 but finally the need was for serialization and deserialization was never implemented. Is that right?

**Comment by tchiotludo** [comment]
Yes it's right, this was never done for now. 
The whole logic is [here](https://github.com/tchiotludo/akhq/blob/dev/src/main/java/org/akhq/models/Record.java) and specially [here](https://github.com/tchiotludo/akhq/blob/dev/src/main/java/org/akhq/models/Record.java#L186), if no schema is found, you can try to detect that message is an avro, and convert it to `GenericAvro` and call : 
```java
                GenericRecord record = (GenericRecord) toType;
                return avroToJsonSerializer.toJson(record);
```
 in order to have a json and it's done :smile: 

a PR is welcome on that

**Comment by bgranvea** [comment]
> Yes it's right, this was never done for now. The whole logic is [here](https://github.com/tchiotludo/akhq/blob/dev/src/main/java/org/akhq/models/Record.java) and specially [here](https://github.com/tchiotludo/akhq/blob/dev/src/main/java/org/akhq/models/Record.java#L186), if no schema is found, you can try to detect that message is an avro, and convert it to `GenericAvro` and call :

just to be sure that I have understood correctly: I'm not an Avro specialist but from what I understand, I need to have a schema to decode the message. 

My idea was to configure some topic=>schema mappings, just like `ProtobufToJsonDeserializer`. In `Record`, if no schemaId is embedded in message, I look at these mappings and if I find a match, I try to decode the message with this schema.

**Comment by tchiotludo** [comment]
ahh ok :smile: 
I don't understand, I think the schema was embed in the message (a normal avro is a binary file that contains in header the schema, and in the body the data). 
In your case, the schema was not in the message ? are you sure ? 
If not, the mapping is only a duplication off the worker of protobuf effectively
