### ISSUE TITLE
Oauth 2, support role as string or array 

### ISSUE THREAD

**Issue by l4crito** [tchiotludo/akhq#840]
Hi, whenever we try to login using pingf , if the user on pingf has only one role/group attached in oidc then it comes as a string instead of an array and akhq don't recognize that role/group, any advice on this ?

oidc clame retuns something like this, login fails
{
"client_id": "some_id",
  "lastName": "some_last_name",
  "firstName": "some_name ",
  "roles": "some_role",
}

oidc clame retuns something like this, login succeeds
{
"client_id": "some_id",
  "lastName": "some_last_name",
  "firstName": "some_name ",
  "roles": ["some_role","another_role"],
}

oidc config is like below

      oidc:
        enabled: true
        providers:
          pingf:
            label: "Login with Pingf"
            username-field: id
            groups-field: roles
            groups:
              - name: some_role
                groups:
                  - admin

**Comment by tchiotludo** [comment]
Does look suprinsing so far. 
When you say login failed ? do you have any error on the backend or front end ?

**Comment by l4crito** [comment]
it stays on login when just the string comes

**Comment by tchiotludo** [comment]
no error on backend log ?

**Comment by l4crito** [comment]
no backend error so far, think stays on login screen because it is not mapping any group/role

**Comment by tchiotludo** [comment]
OK so must be catch by micronaut and I think I can't do anything for that ...

**Comment by l4crito** [comment]
whenever the group-field:roles comes as a individual string instead of an array, akhq redirects  back to login screen always, when the group-field:roles comes as an array from oidc provider it works fine without issue, is there a way to support the string as well?

**Comment by tchiotludo** [comment]
I don't think it's possible, keep it open to look at in the future.
Or PR are welcome ☺️

**Comment by l4crito** [comment]
thanks for taking some time to this
