### ISSUE TITLE
Upgrade Micronaut to 3.x

### ISSUE THREAD

**Issue by timtebeek** [tchiotludo/akhq#846]
Upgrade guides:
- https://docs.micronaut.io/2.0.0/guide/index.html#upgrading - instructions for 1.x to 2.x
- https://docs.micronaut.io/2.5.13/guide/index.html#upgrading - instructions for 2.0 to 2.1+
- https://docs.micronaut.io/3.0.3/guide/index.html#upgrading - instructions for 2.x to 3.x, [including OpenRewrite automation](https://docs.openrewrite.org/tutorials/migrate-to-micronaut-3-from-micronaut-2)

**Comment by tchiotludo** [comment]
already on micronaut 2.x (2.5.5)  :smile:

**Comment by tchiotludo** [comment]
I try on another project, the change will take some time, even more if we decided to remove the RxJava2 deps. 
OpenRewrite will not handle special case on internal bean from micronaut. 

Are you willing to do that ?

**Comment by timtebeek** [comment]
I could look into it, but not that at home in Micronaut yet. Could be a nice challenge, could fail miserably. ;)
If nothing comes of my attempts anyone else is welcome to try as well!

**Comment by asatsi** [comment]
@RoachMJ have you been able to upgrade to 3.0.2? I am facing the same issue as the CVEs you mentioned above. Is there a way I can make local changes and do a gradle build?

**Comment by gquintana** [comment]
I am particularly interested in this change https://github.com/micronaut-projects/micronaut-security/issues/720 which is available in micronaut-security 3.0.0-RC1

**Comment by tchiotludo** [comment]
@timtebeek @gquintana @asatsi @RoachMJ @twobeeb

The upgrade to micronaut 3.2 is done on `dev` branch from this https://github.com/tchiotludo/akhq/commit/bf8c68eaba4bdba8bf865950e476eddb42f7a906. 

I will appreciate some test since there is a lots of changes, especially on the auth side that was breaking compatibility on micronaut 3. 

I planned to release a new version next week. 

Thanks

**Comment by twobeeb** [comment]
Hello, @tchiotludo 
I deployed dev branch on some instances and I experience the behavior documented in #907.

Other than that, everything seems ok.
