### ISSUE TITLE
Could you show message headers also in single message view?

### ISSUE THREAD

**Issue by pimpelsang** [tchiotludo/akhq#903]
Hi,

We are using message headers more and debugging would be much easier if we could see message headers in data as well. Only in single message view is enough.  Have you considered add support for it?

Thanks

**Comment by tchiotludo** [comment]
Hi, 
Not really sure to understand your need here ? 
Maybe you can provide a mockup of the display you want ?

**Comment by pimpelsang** [comment]
Actually it is there. Just need to double click headers number opens it up. Somehow had missed it and tried only regular click there.
