### ISSUE TITLE
Losing sort preference when searching

### ISSUE THREAD

**Issue by evaisman-tc** [tchiotludo/akhq#926]
Hi,

Forgive me if this has been filed before, but a few of my teamates have run into a scenario where their sorting preferences are being overwritten when using search functionality (forces sorting by oldest).

To reproduce, simply sort your data by "NEWEST"
![image](https://user-images.githubusercontent.com/73849911/143298623-19de1469-618d-4ede-b10a-a15b60a96d66.png)

Then provide a search paramater and clicking the hour glass

![image](https://user-images.githubusercontent.com/73849911/143298698-556588db-b0f8-4dfb-85dd-198df05b29a5.png)

After clicking the hourglass, search results will be present with sort=Oldest

![image](https://user-images.githubusercontent.com/73849911/143298820-2aad0647-edcc-4363-ac01-a453ae1e748a.png)

If you attempt to then switch your sorting preference, you will end up losing your search preference.

![image](https://user-images.githubusercontent.com/73849911/143299039-98c6b31b-c43e-4768-a95c-5eab7f9f3a47.png)

Desired behaviour would be to keep both sorting and search preferences.

Tested with versions 0.18, 0.19

**Comment by tchiotludo** [comment]
It's a intended behaviour with bad UX :smile: 
The search, by design and due to limitation of Kafka, MUST BE in oldest sort. 
There is no way to handle it as explain here : https://github.com/tchiotludo/akhq/issues/609

**Comment by evaisman-tc** [comment]
Gotcha, thanks.
