### ISSUE TITLE
topic-data.sort setting appears twice

### ISSUE THREAD

**Issue by gquintana** [tchiotludo/akhq#935]
In https://akhq.io/docs/configuration/akhq.html#pagination
There are 2 settings which look very close:
-  akhq.topic-data.sort
-  akhq.ui-options.topic-data.sort

Are there both in use?
- Yes -> Explain the difference in the doc
- No -> Remove one of them

**Comment by gquintana** [comment]
@tchiotludo You're too fast for me. Thanks for clarifying

The setting removed in  251e0b1 is also present here:
https://github.com/tchiotludo/akhq/blob/4140b333e121e8a4480ea9e9782801a1105e265c/src/main/resources/application.yml#L126

Digging through the code I also noticed a typo here `Setttings` with 3 Ts:
https://github.com/tchiotludo/akhq/blob/21a8574ba8367cc9c6c4ead20dee998e82466c4e/client/src/containers/Settings/Settings.jsx#L9

**Comment by tchiotludo** [comment]
also fix, thanks for the report
