### ISSUE TITLE
Allow to toggle "time ago" and timestamp

### ISSUE THREAD

**Issue by BernhardBerbuir** [tchiotludo/akhq#938]
After adding [feat(ui): display time ago on every datetime](https://github.com/tchiotludo/akhq/commit/d7343161362459d7fc196d5dbceda93ca0ef9daa) all timestamps are only available as mouse over labels. Therefore, it is no longer possible to copy a timestamp from the ui.

It would be great if this behaviour would be configurable: either the timestamp is displayed and a time ago label or vice versa.

**Comment by tchiotludo** [comment]
I see 2 way to handle this : 
- an option 
- better a boostrap tooltip that will allow to copy paste the date : 
![image](https://user-images.githubusercontent.com/2064609/144450987-a0986fc1-cb3d-4efc-a1b1-cf1f0b8d4b24.png)

PR are welcome :wink:
