### ISSUE TITLE
Basic-Auth passwords do not support colon char

### ISSUE THREAD

**Issue by nightswimmings** [tchiotludo/akhq#939]
I tested basic-auth on akhq and passwords that do contain ':' are not working, I presume that is because the .split() in order to tell apart the user and the pass from the encoded base64 Authorization: Basic value

**Comment by twobeeb** [comment]
You are absolutely correct. 
This is a behavior in Micronaut framework. 
https://github.com/micronaut-projects/micronaut-security/blob/master/security/src/main/java/io/micronaut/security/authentication/BasicAuthUtils.java#L47-L69

You could raise an issue on https://github.com/micronaut-projects/micronaut-security
It won't be fixed on AKHQ side.

**Comment by tchiotludo** [comment]
Seems that is valid to have a `:` on password, not on user 
https://dev.to/ethanarrowood/what-characters-should-be-allowed-in-http-basic-authentication-userid-and-password-48f0

**Comment by tchiotludo** [comment]
wait for this : https://github.com/micronaut-projects/micronaut-security/pull/894

**Comment by tchiotludo** [comment]
micronaut is updated for a long time
