### ISSUE TITLE
Reference to Record is ambiguous

### ISSUE THREAD

**Issue by EdwinFajardoBarrera** [tchiotludo/akhq#965]
In newer compilers, it marks an ambiguous reference error (TopicController.java):

`both class org.akhq.models.Record in org.akhq.models and class java.lang.Record in java.lang match
`

It could be caught by importing `org.akhq.models.Record;`

![image](https://user-images.githubusercontent.com/36389489/147149069-6875f5a9-b47f-42cc-9892-5f1bfdc56e34.png)

**Comment by EdwinFajardoBarrera** [comment]
@tchiotludo can I submit a PR with the solution?

**Comment by tchiotludo** [comment]
Yes you can, automatic clean for idea remove them always :confused:
