### ISSUE TITLE
Add extra information to nodes page - controller status, partition load

### ISSUE THREAD

**Issue by jgrammen-agilitypr** [tchiotludo/akhq#983]
Any chance the following extra information could be added to the nodes page?

![image](https://user-images.githubusercontent.com/22965146/149945486-4326e6d2-4343-4300-b2ac-d6f6b9a8221f.png)

Having the controller status and the partition load (% of total), is very helpful to see when the cluster has stabilized post reboot.

**Comment by jgrammen-agilitypr** [comment]
maybe the node page could also indicate when a node is missing:
![image](https://user-images.githubusercontent.com/22965146/149945971-5689c1b1-dea6-4200-b167-490c39027cc5.png)

**Comment by tchiotludo** [comment]
PR are welcome on that, 
- 1st is a simple ui. 
- 2nd seems to be more complicated (I don't know if the api return the valueà

**Comment by jgrammen-agilitypr** [comment]
so i see you have merged the controller status in. I will next tackle the partition information, now @tchiotludo has clarified that it needs back end updates.

**Comment by jgrammen-agilitypr** [comment]
I am struggling a little bit to figure out where in the backend java code I need to insert the code to fetch the partition information so that it can be included in the info passed to the /nodes page. Can anyone provide some guidance?

**Comment by jgrammen-agilitypr** [comment]
After some more looking through the code, it is apparent that somehow the NodeController needs access to the topic repository, but it is un clear to me how this can happen
any advice?

**Comment by tchiotludo** [comment]
You need to inject topic repository : 
```java
@Inject
TopicRepository topicRepository
```
and add some filtering on partitions based on node id

**Comment by jgrammen-agilitypr** [comment]
There is now a pull request to add the additional "partitions" column. Code is functional as far as I can test (I don't know how to join a second node to the Kafka cluster in docker). Comments are welcome, especially given this is my first time contributing Java code.
