### ISSUE TITLE
feature request: display offset metadata in consumer group details page

### ISSUE THREAD

**Issue by pimpelsang** [tchiotludo/akhq#988]
Hi,

Kafka consumers can send additional metadata when committing offsets, but right now it's hard to view it (other than searching through the __consumer_offset topic). 

I wish there was additional column "Metadata" next to "Offset", "Lag" that displays the last committed offse metadata string value for that topic partition.

**Comment by tchiotludo** [comment]
I don't it blindness, can you try the dev branch please ?
