### ISSUE TITLE
Alerting - Topic lag

### ISSUE THREAD

**Issue by gerardgorrion** [tchiotludo/akhq#989]
We are using akhq to monitor our kafka msk solution into aws. The data of the kafka is managed by eck stack operator into k8s. 

Issue:
Some days, the lag of some topics increases in a short time period. 
![image](https://user-images.githubusercontent.com/35425181/150495205-0f652bae-4634-4278-86a0-7a6f288ad4e3.png)

We want:
There are some way to alert into external solution, like MSTeams via webhook, when the spike of lag increases? Maybe when the lag is bigger than 1 000 000, or something like this.

Regards and good job, very usefull this GUI.

**Comment by tchiotludo** [comment]
for this usage, I don't think we will on this side, alerting is really complicated and need a lots of connector. 

I will suggest you to look at [this](https://a-great-day-out-with.github.io/kafka.html).
For myself, I use [kafka-lag-exporter](https://github.com/lightbend/kafka-lag-exporter) with prometheus / alertmanager to handle this.
