### ISSUE TITLE
Expose API

### ISSUE THREAD

**Issue by HungUnicorn** [tchiotludo/akhq#99]
Would it be useful to return json response by giving a query param?
`/topics?output=json` for example

**Comment by tchiotludo** [comment]
It will opt to a full api IMO (not only query string). 

Will add this when possible, PR welcome :pray:

**Comment by sebvelay** [comment]
Hi,
I'm not sure to have to aim of it, but I propose a PR. For moment it's just a "draft" for topic, but if it's OK for you, I will create the all CRUD for topics.
Moreover, do you think we need a swagger-ui ?
Seb

**Comment by tchiotludo** [comment]
Hey, 
It's still a good starting point ! 

For the swagger-ui I can add it after if needed, my preference is [redoc](https://github.com/Redocly/redoc), really clean output. 

For the swagger part, micronaut have a good starting point here : https://micronaut-projects.github.io/micronaut-openapi/latest/guide/index.html
I'have try it for another project and works well.

For the unit test part, just extend `AbstractTest` class, I have changed it few weeks for this part. It will works as I know with `@Client('/')` and test like `Integer result = client.toBlocking().retrieve(HttpRequest.GET('/math/compute/10'), Integer) ` from micronaut

**Comment by tchiotludo** [comment]
Done in `dev` branch and next release :+1:
