### ISSUE TITLE
Link from consumer group topics offset column to topic message

### ISSUE THREAD

**Issue by timtebeek** [tchiotludo/akhq#992]
When viewing consumer group topics it would be nice to link from the offset column directly to the associated message. So from:
`/ui/{cluster}/group/{consumergroup}/topics` to:
`/ui/{cluster}/topic/{topic}/data?single=true&partition={partition}&offset={offset}`.

That way it's easier to verify what is the last message that a consumer with lag has not yet processed.
Just a nice little touch to help link the two pages together, since they are different views on the same data.
Possibly not even that hard to do, but I've not yet looked in to this as I found it during the workday. :)

**Comment by tchiotludo** [comment]
I was thinking the same need for month, without the time to implement it. there is a lot of cross link like that can be useful. 
PR are welcome and that since that a simple one :smile:
